### ISSUE TITLE
Improve non-invasive BRMS inspection to determine version 

### ISSUE THREAD

**Issue by chambridge** [quipucords/quipucords#1014]
## Specify type:
- Enhancement

### Priority:
- Medium
___

## Description:
Currently, we don't determine the version of the BRMS product using the non-invasive scan. We need to improve our data collection to gather the necessary information to determine the version of BRMS.
___

## Acceptance Criteria:

- [ ] Verify that we can determine the version of BRMS a non-invasive scan

**Comment by noahl** [comment]
I've been looking into this and found two separate but related issues.

First, we don't collect version data for non-invasive scans. Oddly, we actually do gather the MANIFEST.MF file with the version in it, but all we do is check whether it contains "Red Hat" and drop the version stuff. I will fix that for this issue.

I'm also going to file another issue for a separate but related problem. BRMS renamed itself to Red Hat Decision Manager in version 7. At the same time, it also changed the name of the .war files it installs, which means that our fingerprints won't find v7 at all.
