### ISSUE TITLE
Ability to sort/filter connection and inspection job results

### ISSUE THREAD

**Issue by jeff-phillips-18** [quipucords/quipucords#1101]
## Type:
- Enhancement

### Priority:
- High
___

## Description:
The results of the call to get a scan job's connection and inspection results are paged, therefore sorting on the client is not accurate. Requesting we sort/filter the results in the API:
```
/jobs/2/connection/?page=1&page_size=100&ordering=name&status=failed
```
would sort by the system 'name' field and filter by status (failed) results.

Are there other statuses returned other than 'success' and 'failed'? The UI only distinguishes the two so if there are others it could be an issue we need to address (filter by failed returns all statuses that would fall into the failure category).
___
@

**Comment by kholdaway** [comment]
@jeff-phillips-18 Yes there are more status choices.
```
    CREATED = 'created'
    PENDING = 'pending'
    RUNNING = 'running'
    PAUSED = 'paused'
    CANCELED = 'canceled'
    COMPLETED = 'completed'
    FAILED = 'failed'
```
