### ISSUE TITLE
RFE: Distribute installer as rpm

### ISSUE THREAD

**Issue by kdelee** [quipucords/quipucords#1149]
## Specify type:
- Enhancement

### Priority:
- Medium
___

## Description:
To enhance the user experience, it has been suggested that the installer be packaged as an rpm -- (or perhaps wrapped in with qpc ??). Then instead of calling the install script directly, some executable `/usr/bin/quipucords-installer` will be installed on the users' system and will depend on ansible and any other packages necessary to use the installer (docker?). 

Alternatively, the RPM could just go ahead and install the whole shebang obviating the need for calling the installer.

___

## Acceptance Criteria:

- [ ] Verify that whatever rpm the installer is packaged with depends on all necessary prerequisites
- [ ] Verify that the user can get a default install by running a command that is placed in their $PATH after doing a `yum install -y $NAMEOFPACKAGE`

**Comment by kholdaway** [comment]
Handled in discovery release
