### ISSUE TITLE
Swagger failing validation on Travis

### ISSUE THREAD

**Issue by noahl** [quipucords/quipucords#1199]
The output is
```bash
$ make swagger-valid
node_modules/swagger-cli/bin/swagger-cli.js validate docs/swagger.yml
Validation failed. Property 'results' listed as required but does not exist in '/definitions/ListPagination'
make: *** [swagger-valid] Error 1
```

Looking at `docs/swagger.yml`, the error seems to be correct.

**Comment by noahl** [comment]
It looks like this is related to Travis moving from OpenAPI 2 to 3 by default.

**Comment by chambridge** [comment]
Seems like we just need to update:
https://github.com/quipucords/quipucords/blob/master/.travis.yml#L12

To lock at a specific version that still used Swagger 2.0
