### ISSUE TITLE
Satellite error encountered: HTTPSConnectionPool(host='10.15.108.24', port=443): Max retries exceeded with url: /api/status

### ISSUE THREAD

**Issue by syangsao** [quipucords/quipucords#1228]
## Specify type:
- Bug

### Priority:
- Medium
___

## Description:
Attempted scan of a Satellite 6.3 environment fails with the following error:
~~~
"status_message": "Satellite error encountered: HTTPSConnectionPool(host='10.15.108.24', port=443): Max retries exceeded with url: /api/status (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:815)'),)). Connect scan failed for source sat6test."
~~~
___

### Version Information:
0.0.42

### Expected behavior:
Assuming this a certificated related error, the certificate verification should work properly as https login access to the Satellite 6.3 server works fine.

### Actual behavior:
Attempted scan of a Satellite 6.3 server fails with the following status_message:
~~~
# qpc scan job --id 4
{
    "end_time": "2018-04-13T20:34:32.398286",
    "id": 4,
    "options": {
        "max_concurrency": 50
    },
    "scan": {
        "id": 4,
        "name": "scan4"
    },
    "scan_type": "inspect",
    "sources": [
        {
            "id": 5,
            "name": "sat6test",
            "source_type": "satellite"
        }
    ],
    "start_time": "2018-04-13T20:34:32.061239",
    "status": "failed",
    "status_message": "One of more tasks did not complete.  See tasks for details.",
    "systems_count": 0,
    "systems_failed": 0,
    "systems_scanned": 0,
    "tasks": [
        {
            "end_time": "2018-04-13T20:34:32.312885",
            "scan_type": "connect",
            "source": 5,
            "start_time": "2018-04-13T20:34:32.088387",
            "status": "failed",
            "status_message": "Satellite error encountered: HTTPSConnectionPool(host='10.15.108.24', port=443): Max retries exceeded with url: /api/status (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:815)'),)). Connect scan failed for source sat6test."
        },
        {
            "end_time": "2018-04-13T20:34:32.376858",
            "scan_type": "inspect",
            "source": 5,
            "start_time": "2018-04-13T20:34:32.351411",
            "status": "failed",
            "status_message": "Prerequisites scan task with id 7 failed."
        }
    ]
}
~~~

### Steps to reproduce:
1.  Fresh installation of RHEL 7.4 and Satellite 6.3 (not upgraded)
2.  Setup qpc server
3.  Ran the following commands to gather information from Satellite 6.3
~~~
# qpc cred add --type satellite --name sat6admin --username admin --password 
# qpc source add --type satellite --name sat6test --hosts 10.15.108.24 --cred sat6admin
# qpc scan add --name scan4 --sources sat6test
# qpc scan start --name scan4
# qpc scan job --id 4
~~~

### Environment information:
Provide detailed information on the *scanning* and *target* systems (if applicable); see example below.

Type            | Operating System | OS Version | Python Version | Virtualization
--------------- | ---------------- | ---------- | -------------- | --------------
Scanning System | RHEL             | 7.4        | 3.x            | RHV
Target System   | RHEL, Satellite              | 7.4, 6.3        | 2.x          | RHV

**Comment by syangsao** [comment]
quipucords log attached
[quipucords.log.gz](https://github.com/quipucords/quipucords/files/1908909/quipucords.log.gz)

**Comment by chambridge** [comment]
http://quipucords.readthedocs.io/en/0.0.41-pilot/working_with_sources.html#creating-a-satellite-source

```
IMPORTANT: By default, sources are scanned with full SSL validation, but you might need to adjust the level of SSL validation to connect properly to the Satellite server. The source add command supports options that are commonly used to downgrade the SSL validation. The --ssl-cert-verify option can take a value of False to disable SSL certificate validation; this option would be used for any server with a self-signed certificate. The Satellite server does not support disabling SSL, so the --disable-ssl option has no effect.
```

**Comment by chambridge** [comment]
Reopen the issue if this doesn't solve your problem.

**Comment by syangsao** [comment]
Verified, thanks guys!

# qpc source edit --name sat6test --ssl-cert-verify False
# qpc source show --name sat6test
# qpc scan start --name scan4
# qpc scan job --id 6
# qpc report detail --scan-job 6 --json --output-file=~/scan6_detail.json
# qpc report summary --scan-job 6 --json --output-file=~/scan6_summary.json

**Comment by kholdaway** [comment]
👍
