### ISSUE TITLE
UI/UX Bugs

### ISSUE THREAD

**Issue by bclarhk** [quipucords/quipucords#1233]
## Specify type:
- Bug

### Priority:
- High

## Description:
Downloading a previous scan is severely hindered by a scrolling issue.
 
![image](https://user-images.githubusercontent.com/32572198/38836551-8ae092ee-419c-11e8-8296-bd442b4c4def.png)

Clicking "Refresh" does not refresh the status of individual network sources
![image](https://user-images.githubusercontent.com/32572198/38836758-5ad3e9ba-419d-11e8-96f9-2efaeed513d3.png)

"Filter by Credential name" is being truncated
![image](https://user-images.githubusercontent.com/32572198/38836779-6ea2fec2-419d-11e8-90d1-c5e13353bbfb.png)

**Comment by kholdaway** [comment]
Issue moved to [quipucords/quipucords-ui #12](https://github.com/quipucords/quipucords-ui/issues/12) via [**ZenHub**](https://www.zenhub.com/)
