### ISSUE TITLE
RFE: Heartbeat logging for Scan Manager

### ISSUE THREAD

**Issue by kdelee** [quipucords/quipucords#1236]
## Specify type:
- Enhancement

### Priority:
- High
___

## Description:
We are running into an issue with the automated jobs where it appears that the server can sometimes enter into a broken state where scanjobs get stuck in the `created` state and never proceed. It has been postulated that the "Scan Manager" has died in these cases. 

It would be very helpful to understand the state of the server if the Scan Manger logged its status at some regular interval.
___

## Acceptance Criteria:

- [ ] Verify that additional logging is added that makes it clear whether the Scan Manger is alive

**Comment by elyezer** [comment]
I think a heatbeat at every minute or every other minute would help identify why scans are not starting. If the scan manager is not hear beating then it should be the culprit and we should be able to check the logs to see why it has died.
