### ISSUE TITLE
UI: Allow specification of SSL strictness

### ISSUE THREAD

**Issue by dozdowski** [quipucords/quipucords#1256]
## Specify type:
- Enhancement

### Priority:
- Medium

___

## Description:
the UI provides no option to specify the --ssl-cert-verify option, forcing users to the default of "True" . The use of self-signed certs which require "--ssl-cert-verify False" is proving common.

As a QPC user who applies self-signed certificates, I would like a creation option added to the UI for Satellite and vCenter source types.  This option would be a checkbox, checked by default, and would bear the label "Require CA signed security certificates" .  When a source is submitted, its value for "--ssl-cert-verify" will be driven by the value of the checkbox.
___

## Acceptance Criteria:

- [ ] Verify that users can use the UI to create a source with SSL verification set to False
- [ ] Verify that users can use the UI to create a source with SSL verification set to True
- [ ] Verify that users can use the UI to edit a source and change the SSL verification value

___

**Comment by cdcabrera** [comment]
@dozdowski @bclarhk have the basic layout here for a `Satellite` and `vCenter` resource... anything extra, missing?

![screen shot 2018-04-24 at 6 37 54 pm](https://user-images.githubusercontent.com/3761375/39217594-bdd3a6f2-47ee-11e8-81a2-374ad3d16101.png)

**Comment by dozdowski** [comment]
I'd love to adjust the label slightly.  Can we go with "Verify SSL Certificate"?  It's shorter than the label in my issue - but reads more naturally than the one from the image above.  I think most folks reading that will understand that it means "Verify the SSL certificate with a Certificate Authority."
