### ISSUE TITLE
Investigate Process.terminate issue in docker container

### ISSUE THREAD

**Issue by kholdaway** [quipucords/quipucords#1269]
## Specify type:
- Bug

### Priority:
- High
___

## Description:
This is a possible bug.  QE logs have shown instances where the pause/cancel task doesn't stop processing even though the python Process.terminate() method has been called.  This issue is to investigate whether the pause/cancel work differently when run in a docker container.
___

## Acceptance Criteria:
- [ ] Verify that pause/cancel work in a docker container

**Comment by elyezer** [comment]
Reading the terminate docs we can see the following example:

```python
>>> import multiprocessing, time, signal
>>> p = multiprocessing.Process(target=time.sleep, args=(1000,))
>>> print p, p.is_alive()
<Process(Process-1, initial)> False
>>> p.start()
>>> print p, p.is_alive()
<Process(Process-1, started)> True
>>> p.terminate()
>>> time.sleep(0.1)
>>> print p, p.is_alive()
<Process(Process-1, stopped[SIGTERM])> False
>>> p.exitcode == -signal.SIGTERM
True
```

As you can see some time is given after the terminate is called so maybe quipucords should wait until the process is really terminated?

PS.: I have not read the source code so I don't really know if this is already doing.

**Comment by kholdaway** [comment]
We do a join.
```
            job_runner.terminate()
            job_runner.join()
            killed = not job_runner.is_alive()
```

**Comment by elyezer** [comment]
Checking the logs using the dev server I see these messages:

```
INFO Job 2 (inspect, elapsed_time: 0s) - SIGNAL PAUSE received for scan job.
INFO Job 2 (inspect, elapsed_time: 0s) - TERMINATING JOB PROCESS
INFO Job 2 (inspect, elapsed_time: 0s) - Process successfully killed=False.
ERROR Job 2 (inspect, elapsed_time: 0s) - Request to kill process failed.
```

So the job is not really being killed. On the source it is only printing some log messages:

```python
            job_runner.terminate()
            job_runner.join()
            killed = not job_runner.is_alive()
            job.log_message(
                'Process successfully killed=%s.' % killed)
            if not killed:
                job.log_message(
                    'Request to kill process failed.',
                    log_level=logging.ERROR)
            self.current_task = None
```

So before making `self.current_task = None` it should ensure the task is actually killed.

**Comment by elyezer** [comment]
I've experimented with the following code:

```python
            job_runner.terminate()
            job_runner.join()
            import time
            while job_runner.is_alive():
                job.log_message('WAIT TO TERMINATE...')
                time.sleep(1)
            killed = not job_runner.is_alive()
            job.log_message(
                'Process successfully killed=%s.' % killed)
            if not killed:
                job.log_message(
                    'Request to kill process failed.',
                    log_level=logging.ERROR)
            self.current_task = None
```

And now I see this on the logs:

```
INFO Job 2 (inspect, elapsed_time: 0s) - SIGNAL PAUSE received for scan job.
INFO Job 2 (inspect, elapsed_time: 0s) - TERMINATING JOB PROCESS
INFO Job 2 (inspect, elapsed_time: 0s) - WAIT TO TERMINATE...
INFO Job 2 (inspect, elapsed_time: 1s) - Process successfully killed=True.
```

It seems that the job needs some time to actually be killed. I will experiment this code running on the container. Let's see how it goes.

**Comment by kholdaway** [comment]
That still seems odd given there is a join.

**Comment by kholdaway** [comment]
Addionally with the container we assume the server is restarted with the exceptions. So waiting will not remove that issue. When the server restarts the job will still ok be in the running state.
