### ISSUE TITLE
Missing entry in Summary report

### ISSUE THREAD

**Issue by mdvickst** [quipucords/quipucords#1300]
## Specify type:
- Bug

### Priority:
- High
___

## Description:
I scanned 3 VMs as seen in the detailed report but only 2 show up in the summary. They should all have different hostnames (one is rhel-5 and one is rhel5-6 so not sure if that matters), different IPs and macs. I scanned them with sudo and 1 of the servers the user didn't have access to sudo as seen in the detailed results. 

___

## Acceptance Criteria:

- [ ] Verify that all 3 systems show up in summary report

___

### Version Information:
78f646c624f732cff3fa976d0b895057c6b96a35

### Expected behavior:
All 3 VMs should have been added to summary even if some of the facts weren't collected on the server without sudo privleges

### Actual behavior:
Only the 2 servers with sudo privleges were added to summary

### Environment information:
Provide detailed information on the *scanning* and *target* systems (if applicable); see example below.

Type            | Operating System | OS Version | Python Version | Virtualization
--------------- | ---------------- | ---------- | -------------- | --------------
Scanning System | RHEL             | 7.4        | 3.6            | Bare Metal
Target System   | RHEL             | 5.9        | 2.4.6          | RHEV

**Comment by kholdaway** [comment]
@mdvickst Are these systems we can scan?  If not, could we get logs for the scan?

**Comment by mdvickst** [comment]
[issue1300.tar.gz](https://github.com/quipucords/quipucords/files/1960620/issue1300.tar.gz)

**Comment by kholdaway** [comment]
@mdvickst Could you also provide the details/deployment report as JSON?  We could use this to debug locally.

**Comment by kholdaway** [comment]
I see this in the logs:
`ERROR 2018-04-27 16:43:29,800 __init__ 1319 140694731421440 Fingerprint errors: {'bios_uuid': ['Ensure this field has no more than 36 characters.'], 'subscription_manager_id': ['Ensure this field has no more than 36 characters.']}`

Additionally, this in the report as the value that is longer than 36 characters. 
```
mvickstr is not in the sudoers file.  This incident will be reported.
```

It looks like we missed some error handling for non-sudo/non-root users.

**Comment by mdvickst** [comment]
[issue1300.json.zip](https://github.com/quipucords/quipucords/files/1961623/issue1300.json.zip)
