### ISSUE TITLE
redhat_packages_gpg_is_redhat Fact failing on RHEL 5.6 Possibly Others

### ISSUE THREAD

**Issue by mdvickst** [quipucords/quipucords#1302]
## Specify type:
- Bug

### Priority:
- Blocker
___

## Description:
The redhat_packages_gpg_is_redhat fact shows "N" for vanilla install of RHEL 5.6 due to the "check to see if any red hat rpms are installed" task failing. The `rpm -qa --qf "%{SIGPGP:pgpsig}\n"` part of the command returns:
```
[root@rhel5-6 ~]# rpm -qa --qf "%{SIGPGP:pgpsig}\n"
(not a blob)
(not a blob)
(not a blob)
....
```

___

## Acceptance Criteria:

- [ ] Verify that RHEL 5, 6, and 7 properly display "Y" for the redhat_packages_gpg_is_redhat fact.

___

### Version Information:
latest

### Actual behavior:
Provide the actual behavior for the program.

### Steps to reproduce:
Scan a 5.x system with quipucpords.

### Environment information:

Type            | Operating System | OS Version | Python Version | Virtualization
--------------- | ---------------- | ---------- | -------------- | --------------
Scanning System | RHEL             | 7.4        | 3.6            | VirtualBox
Target System   | RHEL             | 5.6        | 2.4.6          | VirtualBox

**Comment by mdvickst** [comment]
[Archive 3.zip](https://github.com/quipucords/quipucords/files/1971622/Archive.3.zip)
Still getting FALSE in redhat_packages_gpg_is_redhat fact for RHEL 5.

**Comment by kholdaway** [comment]
Mark confirmed 0.0.42 fixed the issue.
