### ISSUE TITLE
Scripted Installation on RHEL 6 fails to install qpc RPM

### ISSUE THREAD

**Issue by mdvickst** [quipucords/quipucords#1328]
## Specify type:
- Bug

### Priority:
- High

___

## Description:
It looks like the playbook is trying to install fc27 version of the qpc RPM on RHEL 6. Not sure about RHEL 7. 

TASK [qpc_cli : Install the latest version of QPC] *********************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "No package matching 'qpc-0.0.42-1.git.659.23c2bcb.fc27' found available, installed or updated", "rc": 126, "results": ["No package matching 'qpc-0.0.42-1.git.659.23c2bcb.fc27' found available, installed or updated"]}
	to retry, use: --limit @/root/install/qpc_playbook.retry

___

## Acceptance Criteria:

- [ ] Verify that users can X Y Z
- [ ] Verify that an expected error is encountered when a user does A B C

___

### Version Information:
0.0.42-1

### Expected behavior:
Describe the expected behavior for the program.

### Actual behavior:
Provide the actual behavior for the program.

### Steps to reproduce:
List clear steps to reproduce the bug.

### Environment information:
Provide detailed information on the *scanning* and *target* systems (if applicable); see example below.

Type            | Operating System | OS Version | Python Version | Virtualization
--------------- | ---------------- | ---------- | -------------- | --------------
Scanning System | RHEL             | 7.4        | 3.6            | Bare Metal
Target System   | RHEL             | 5.9        | 2.4.6          | RHEV

**Comment by kholdaway** [comment]
Should be fixed.  Give it another try.  Our automation installation tests passed.
