### ISSUE TITLE
UI: Remove SSH Key Cred Option for vCenter and Satellite Cred Types

### ISSUE THREAD

**Issue by mdvickst** [quipucords/quipucords#1337]
## Specify type:
- Enhancement

### Priority:
- Medium
___

## Description:
Provide a description of the issue being raised.

___

## Acceptance Criteria:

- [ ] Verify that users can't create a cred for Vcenter or sat with an SSH key.

**Comment by cdcabrera** [comment]
Examples...

### VCenter & Satellite 
![jun-05-2018 13-37-05](https://user-images.githubusercontent.com/3761375/40992755-a5894514-68c5-11e8-81ca-94763072a4ee.gif)


### Network Cred:
![screen shot 2018-06-05 at 1 06 39 pm](https://user-images.githubusercontent.com/3761375/40991414-bac216ee-68c1-11e8-855c-598c035686cf.png)
