### ISSUE TITLE
jboss.eap.packages fact reports systems without RPM command as having EAP packages

### ISSUE THREAD

**Issue by mdvickst** [quipucords/quipucords#1341]
## Specify type:
- Bug

### Priority:
- High
___

## Description:
Systems without RPM command show up as having 1 EAP package. I believe it's counting the error as a package. 
___

## Acceptance Criteria:

- [ ] Verify debian systems do not report EAP packages being installed

___

### Version Information:
CLI Server Version or commit information.

### Expected behavior:
Describe the expected behavior for the program.

### Actual behavior:
Provide the actual behavior for the program.

### Steps to reproduce:
List clear steps to reproduce the bug.

### Environment information:
Provide detailed information on the *scanning* and *target* systems (if applicable); see example below.

Type            | Operating System | OS Version | Python Version | Virtualization
--------------- | ---------------- | ---------- | -------------- | --------------
Scanning System | RHEL             | 7.4        | 3.6            | Bare Metal
Target System   | RHEL             | 5.9        | 2.4.6          | RHEV

**Comment by noahl** [comment]
@mdvickst do you happen to have the input logs from the quipucords machine that did this?

The postprocessing for `jboss.eap.packages` happens at https://github.com/quipucords/quipucords/blob/master/quipucords/scanner/network/processing/eap.py#L137 . I would have expected the processing framework to notice that the command failed with a nonzero return value and automatically discard the result. I want to figure out why that didn't happen.

**Comment by kholdaway** [comment]
@mdvickst Can you provide the details report/summary report for that system?

**Comment by kholdaway** [comment]
Issue moved to [quipucords/rho #589](https://github.com/quipucords/rho/issues/589) via [**ZenHub**](https://www.zenhub.com/)
