### ISSUE TITLE
DOC: Discuss QPC's ability to discern community upstream technologies

### ISSUE THREAD

**Issue by dozdowski** [quipucords/quipucords#1342]
## Specify type:
- Enhancement

### Priority:
- Low
___

## Description:
QPC can detect and differentiate the upstream, "community" version of many Red Hat technologies.  We should include a topic in the "Concepts" section that outlines which community products QPC can identify and report.

___

## Acceptance Criteria:

- [ ] Verify that users can read the "Concepts" documentation and understand what community technologies QPC can detect.
- [ ] Verify that the "Concepts" documentation explains what QPC does when it detects upstream software.

**Comment by kholdaway** [comment]
Issue moved to [quipucords/quipudocs #50](https://github.com/quipucords/quipudocs/issues/50) via [**ZenHub**](https://www.zenhub.com/)
