### ISSUE TITLE
Add ability to exclude IP addresses to the REST Source CLI for network scans

### ISSUE THREAD

**Issue by kholdaway** [quipucords/quipucords#1351]
## Specify type:
- Enhancement

## Description:
Modify the `qpc source add` and `qpc source edit` CLI to allow exclusion of IP addresses and ranges.  The focus of this story is the CLI.  Other issues will capture API and scanning.  This issue is dependent on #1350.

Add an option to both add/update called `--exclude-hosts`.  The command should have syntax, help, and documentation that is similar to the `--hosts` parameter.
___

## Acceptance Criteria:

- [ ] `qpc source add` with --exclude-hosts passes values to the create source REST API
- [ ] `qpc source edit` with --exclude-hosts passes values to the partial update source REST API
- [ ] Verify that omitting this --exclude-hosts attribute is allow
- [ ] Verify that the --exclude-hosts attribute will accept more than one ip, host, or range.
- [ ] Man page and user documentation is updated for the `qpc source add/edit` commands
- [ ] Unit tests cover newly created function

**Comment by elyezer** [comment]
I've created https://github.com/quipucords/camayoc/issues/261 to track the integration tests for this.
