### ISSUE TITLE
Add installed products (EAP, BRMS, FUSE) to the CSV report

### ISSUE THREAD

**Issue by kholdaway** [quipucords/quipucords#1360]
## Specify type:
- Enhancement

### Priority:
- High
___

## Description:
SEAP provided feedback that this would be useful in the CSV report.  This is a small enhancement to capture the installed products one or more CSV columns.

___

## Acceptance Criteria:

- [ ] Verify that users can see a clear indication of whether a product is installed.

___

**Comment by cixil** [comment]
These columns already exist in the CSV report:
jboss brms | jboss eap | jboss fuse
