### ISSUE TITLE
Allow users to specify paramiko for the connection type used by ansible

### ISSUE THREAD

**Issue by mdvickst** [quipucords/quipucords#1364]
## Specify type:
- Enhancement

### Priority:
- Medium
___

## Description:
Open-ssh is the default ansible connection method but certain customers have versions of open-ssh which aren't compatible so we should add an option to QPC to allow them to use paramiko. 

The option when running ansible is `-c paramiko` appended to the ansible or ansible-playbook command. 

The default should always be to not append -c paramiko but if there is a flag specified on the scan command like `--use_paramiko` then we should add the `-c paramiko` option to anywhere Ansible is used (discovery and fact collection). 

___

## Acceptance Criteria:

- [ ] Verify that users can specify an option and it forces ansible to use

**Comment by cixil** [comment]
Is this just in the CLI or does the Django api need to be modified as well?

**Comment by cixil** [comment]
And would it be best to include this `--use-paramiko` as an argument to the scan add and scan edit commands or only as a paramter to the scan start command?

**Comment by mdvickst** [comment]
I think it would be added to the scan add and edit commands. I'm not sure about if the API would need to be modified.

**Comment by chambridge** [comment]
@cixil does it make any sense to have it be a property of a network source?

**Comment by cixil** [comment]
@chambridge, @kholdaway thinks that's a better idea too. So I'll make it a property of network sources then @mdvickst
