### ISSUE TITLE
Replace recursive walk with a property collector

### ISSUE THREAD

**Issue by kholdaway** [quipucords/quipucords#1367]
## Specify type:
- Enhancement

### Priority:
- High

___

## Description:
Replace recursive walk with a property collector.  A property collector will dramatically improve performance of vCenter scanning.

___

## Acceptance Criteria:
- [ ] Verify results are the same as the recursive walk
- [ ] Verify that nested data centers are still supported

**Comment by cixil** [comment]
Closed by #1363
