### ISSUE TITLE
UI: Cancellation confirmation dialog for editing sources is the one for creating new sources

### ISSUE THREAD

**Issue by dsesami** [quipucords/quipucords#1374]
## Specify type:
- Bug

### Priority:
- Low
___

## Description:
Essentially, when editing an existing source from the UI, if you cancel the process, you get the pop-up for cancelling the addition of a new source, but the text should be that for cancelling the _editing_ of a source.

## Acceptance Criteria:

- [ ] Verify that when editing an existing source for the UI, that the pop-up mentions cancelling the editing of a source, rather than the addition of a new source.

___

### Version Information:
qpc 0.0.42

### Expected behavior:
Closing confirming dialog asks to cancel the editing of the source. 

### Actual behavior:
Closing confirmation dialog asks to cancel the addition of a new source.

### Steps to reproduce:
1) Create a new source if one does not exist.
2) Click the edit button symbol on the source.
3) Attempt to cancel the editing of the source.

### Environment information:
N/A

**Comment by kholdaway** [comment]
Issue moved to [quipucords/quipucords-ui #13](https://github.com/quipucords/quipucords-ui/issues/13) via [**ZenHub**](https://www.zenhub.com/)
