### ISSUE TITLE
UI should include a field during adding/editing sources that supports exclude-hosts API option

### ISSUE THREAD

**Issue by dsesami** [quipucords/quipucords#1375]
# Issue type
- Enhancement 

# Description
qpc CLI/API now supports an "exclude hosts" option that excludes addresses from the host list based on the same format of criteria as the "hosts" option. This is only for network type sources. The UI needs to have a field added that allows the user to modify the excluded hosts list.

# Completion checklist
To close this issue, the following items must be satisfied:
- [ ] Verify that creation and editing of network sources have a field where excluded hosts can be set as an option.
- [ ] Verify that non-network sources do not have exclude-hosts available as a settable option.

# Related development issues
https://github.com/quipucords/quipucords/issues/1350

**Comment by kholdaway** [comment]
Issue moved to [quipucords/quipucords-ui #14](https://github.com/quipucords/quipucords-ui/issues/14) via [**ZenHub**](https://www.zenhub.com/)
