### ISSUE TITLE
UI script for building UI against a development server

### ISSUE THREAD

**Issue by dsesami** [quipucords/quipucords#1376]
## Specify type:
- Enhancement

### Priority:
- Low (convenience script)
___

## Description:
Currently, if you've built the API server with `make serve` not in a container, there isn't a trivial script  to build the UI materials and have them use the API port for queries. This issue was opened after discussion with @cdcabrera .
___

## Acceptance Criteria:

- [ ] Verify that users who have a development server built with `make serve` can run an npm script that builds the UI and uses the server.

**Comment by cdcabrera** [comment]
Aspects of this are being resolved via #1833 and the NPM script `$ npm run test:qe` where we setup a test specific script to be run against GUI changes, either pulled in through `git` or made locally.

**Comment by cdcabrera** [comment]
Closing this one down since 
- some of the requirements have been met utilizing an updated Docker setup aimed at QE
