### ISSUE TITLE
Commas Present in virt field for RHV host and other fields

### ISSUE THREAD

**Issue by mdvickst** [quipucords/quipucords#1384]
## Specify type:
- Bug

### Priority:
- High
___

## Description:
When scanning RHV host it shows "RHEV,KVM" in the virt field which is causing CSV parsers to split the column. We have reports of this happening on other columns as well for example, entitlements if the SKU has a comma in the name it will cause and error in opening the file.

It would be good to just sanitize each datapoint before we write values out to CSV, replacing in commas with some other character. 

___

## Acceptance Criteria:

- [ ] Verify Scans of RHV hosts don't produce results with commas
- [ ] Verify that commas in SKU names and other fields don't get written to CSV file. 

___

### Version Information:
CLI Server Version or commit information.
All

### Expected behavior:
Describe the expected behavior for the program.

### Actual behavior:
Provide the actual behavior for the program.

### Steps to reproduce:
List clear steps to reproduce the bug.

### Environment information:
Provide detailed information on the *scanning* and *target* systems (if applicable); see example below.

Type            | Operating System | OS Version | Python Version | Virtualization
--------------- | ---------------- | ---------- | -------------- | --------------
Scanning System | RHEL             | 7.4        | 3.6            | Bare Metal
Target System   | RHEL             | 5.9        | 2.4.6          | RHEV

**Comment by kholdaway** [comment]
This fix is also being backported to 0.0.43 this evening.
