### ISSUE TITLE
Distinction between RHV, OpenStack and Libvirt for virt_type

### ISSUE THREAD

**Issue by mdvickst** [quipucords/quipucords#1387]
## Specify type:
- Enhancement

### Priority:
- Low
___

## Description:
Right now when scanning a RHV host the virt_type column displays "RHEV, KVM", it should just display RHV (no 'E' to match the latest branding). It would also be nice to be able to differentiate between RHV, OpenStack and libvirt which all show kvm right now.

___

## Acceptance Criteria:

- [ ] Verify that users can X Y Z
- [ ] Verify that an expected error is encountered when a user does A B C

___

### Version Information:
CLI Server Version or commit information.

### Expected behavior:
Describe the expected behavior for the program.

### Actual behavior:
Provide the actual behavior for the program.

### Steps to reproduce:
List clear steps to reproduce the bug.

### Environment information:
Provide detailed information on the *scanning* and *target* systems (if applicable); see example below.

Type            | Operating System | OS Version | Python Version | Virtualization
--------------- | ---------------- | ---------- | -------------- | --------------
Scanning System | RHEL             | 7.4        | 3.6            | Bare Metal
Target System   | RHEL             | 5.9        | 2.4.6          | RHEV

**Comment by justinkreft** [comment]
Related to RHV and HYPERV support
