### ISSUE TITLE
Add "number of hosts in cluster" to QPC scan

### ISSUE THREAD

**Issue by mdvickst** [quipucords/quipucords#1393]
## Specify type:
- Enhancement

### Priority:
- Medium
___

## Description:
Number of hosts in a cluster can typically be derived from looking at all the hosts reported by the VMs which are running but occasionally there is a host in the cluster with no VMs running on it which would not get reported. 

___

## Acceptance Criteria:

- [ ] Verify that cluster with x number of hosts in it, with VMs only running on x-1 hosts reports x hosts in cluster

**Comment by justinkreft** [comment]
Stale.

**Comment by justinkreft** [comment]
Stale

**Comment by justinkreft** [comment]
Collecting aggregated facts is not something we want to do.

**Comment by justinkreft** [comment]
closed
