### ISSUE TITLE
GET request isn't performed when saving a new credential in UI

### ISSUE THREAD

**Issue by dsesami** [quipucords/quipucords#1399]
## Specify type:
- Bug

### Priority:
- Low
___

## Description:
When creating a new credential on the Credentials page in the UI, after the "save" button is clicked, the credential isn't immediately viewable. A GET isn't being performed according to @cdcabrera , so the page has to be refreshed somehow.
___

## Acceptance Criteria:

- [ ] Verify that when a new credential is created, a GET is called and the page is updated.
___

### Version Information:
QPC master, latest

### Expected behavior:
The page is updated with the new credential information when the save button is clicked.

### Actual behavior:
The page needs to be refreshed to view new credential information.

### Steps to reproduce:
1) Go to the credentials tab and create a new credential.

**Comment by kholdaway** [comment]
Issue moved to [quipucords/quipucords-ui #15](https://github.com/quipucords/quipucords-ui/issues/15) via [**ZenHub**](https://www.zenhub.com/)
