### ISSUE TITLE
Database lock error in QPC results in large, unpleasant error message in UI

### ISSUE THREAD

**Issue by dsesami** [quipucords/quipucords#1402]
## Specify type:
- Enchancement

### Priority:
- Medium
___

## Description:
The database locking issue (documented in quipucords/quipucords/issues/1275) results in an alert/toast that appears on the page showing the entire error. The following screenshot shows this error after attempting to delete a source.

![screenshot from 2018-08-10 11-26-02](https://user-images.githubusercontent.com/19942822/43966663-7bce4f86-9c90-11e8-90e1-ae4d3ccc1c87.png)

___

## Acceptance Criteria:

- [ ] Verify that if the database lock error occurs, a more readable error is presented.

___

### Version Information:
Quipucords, master, latest (0.0.43)

### Steps to reproduce:
See quipucords/quipucords/issues/1275. Typically, using automation to delete sources quickly in succession can trigger the database lock.

**Comment by kholdaway** [comment]
This isn’t a UI bug. We have a bug open for this dblock already.

**Comment by dsesami** [comment]
Changed to an enhancement instead of a bug based on above commentary @kholdaway @cdcabrera.

Is there a better label for this besides UI/UX, or should I take that off completely? My main issue is that I think showing stack traces on the front end isn't the best, and that it should be confined to logs. We could specify a 500-type internal server error and say to refer to the logs somehow.

**Comment by kholdaway** [comment]
I guess it could be an enhancement for general server 500 handling. Not just DB lock.

**Comment by elyezer** [comment]
@kholdaway @cdcabrera should we close this since we are now using postgres and the DB lock won't happen or update so this can be used to improved 500 errors?

**Comment by elyezer** [comment]
@cdcabrera I like that :+1:. So I will leave this open then

**Comment by kholdaway** [comment]
Issue moved to [quipucords/quipucords-ui #16](https://github.com/quipucords/quipucords-ui/issues/16) via [**ZenHub**](https://www.zenhub.com/)
