### ISSUE TITLE
Document CLI features not available in the QPC UI

### ISSUE THREAD

**Issue by kholdaway** [quipucords/quipucords#1422]
### Describe the solution you'd like
The output of this issue will be a list of CLI features that cannot be done via the UI.

___

**Comment by abaiken** [comment]
Features in CLI that are not extended to UI:
- Credentials:
    - Viewing a credentials info (username/become method/etc.) without editing it
- Sources:
    - Create a source with a file for the hosts
    - Create a source with --exclude-hosts
        - Create a source with a file for exclude hosts
    - Create a source without kicking off a connection scan
    - Create a source with `--ssl-protocol`
    - Create a source with `--disable-ssl`
    - Create a source with `--use-paramiko`
- Scans: 
    - Create a scan with `--max-concurrency`
    - Create a scan with `--disabled-optional-products`
    - Create a scan with `--enabled-ext-product-search`
        - Create a scan with `--ext-product-search-dirs`
- Report:
    - Viewing a report without downloading it 
    - Downloading a json version of the report

**Comment by kholdaway** [comment]
👍 Nice job @abaiken.
