### ISSUE TITLE
Epic METER-E-27 - QPC RFE: Gather "Intent" in RHEL 8 (Beta)

### ISSUE THREAD

**Issue by kholdaway** [quipucords/quipucords#1432]
This epic mirrors https://redhatmbu.aha.io/epics/METER-E-27. It is a top level epic to capture work and dependencies required to deliver.

**Comment by elyezer** [comment]
#1691 add new fields related to the syspurpose but I don't see a field for the version. On the docs we have:

```
“_version”
Type. String
Required. Yes
This indicates to the tooling which schema this file is intended to be. Used along with the file name, the schema necessary is found at /etc/rhsm/syspurpose/schema/<_version>/syspurpose_fields.json
```

Maybe it will be interesting to get the version so we can know the related syspurpose_fields for a specific system.

Also maybe it would be better to rename from intent to purpose to match the same nomenclature used by the metadata.

**Comment by kholdaway** [comment]
@elyezer we do have the version in the details report.  The version is for the JSON file and not os-release (you probably knew that, but just to be clear)

**Comment by elyezer** [comment]
I meant the version for the JSON file. Because it is a required field and then it is probably an important information to gather.
