### ISSUE TITLE
User Story: Document JBoss detection algorithms 

### ISSUE THREAD

**Issue by kholdaway** [quipucords/quipucords#1443]
## Feature description:

Document algorithms for detecting JBoss products.  This involves scraping the details from the roles and creating a document describing them.  This should call out variations required per version.

Document: 
- [x] EAP
- [x] BRMS
- [x] FUSE
- [x] JWS

**Comment by abaiken** [comment]
View the documentation [here](https://docs.google.com/document/d/1VnX10v70zRzhCpA3bhoi8LurTg9vsGmZDLXyVnAdwgY/edit?usp=sharing).
