### ISSUE TITLE
Simplify threading for satellite

### ISSUE THREAD

**Issue by kholdaway** [quipucords/quipucords#1455]
### Is your feature request related to a problem?
Currently QPC performs db updates and other various operations on threads for satellite scans.  The intent of the satellite threading was to improve performance due to the many http requests.  When we added Postgres DB, deadlocks were introduced.

### Describe the solution you'd like
Isolate the threading to the HTTP requests.  Pre/post processing should be done on the main thread before and after forking.  This saves the benefits of threading but reduces complexity.  

___

## Acceptance Criteria:
- [ ] Satellite do not perform database operations on worker threads during satellite scans.
- [ ] Solution impacts satellite 5, 6.1, and 6.2.

**Comment by abaiken** [comment]
Closed by #1458  & #1464
