### ISSUE TITLE
Running automated installer doesn't work for upgrading between releases

### ISSUE THREAD

**Issue by mdvickst** [quipucords/quipucords#1456]
## Bug Description:
Could be an enhancement but running the ansible installer on a previously running version doesn't properly download and start the new version as expected. 

### Expected behavior:
Should stop old version (possibly remove the container) and start the new release. 

### Actual behavior:
Installer fails when trying to start new release since it never downloaded release. 

TASK [qpc_server : Start server] *************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "docker run --name \"quipucords\" -d -p \"443\":443 -v \"/root/quipucords\"/sshkeys:/sshkeys\":z\" -v \"/root/quipucords\"/data:/var/data\":z\" -v \"/root/quipucords\"/log:/var/log\":z\" -i \"quipucords:0.0.44\"", "delta": "0:00:01.717071", "end": "2018-09-13 13:55:27.778358", "msg": "non-zero return code", "rc": 1, "start": "2018-09-13 13:55:26.061287", "stderr": "Unable to find image 'quipucords:0.0.44' locally\nPulling repository quipucords\nError: image library/quipucords:0.0.44 not found", "stderr_lines": ["Unable to find image 'quipucords:0.0.44' locally", "Pulling repository quipucords", "Error: image library/quipucords:0.0.44 not found"], "stdout": "", "stdout_lines": []}

### Steps to reproduce:
List clear steps to reproduce the bug.

___

## Acceptance Criteria:

- [ ] Verify that users can X Y Z
- [ ] Verify that an expected error is encountered when a user does A B C

___

### Version Information:
CLI version, server version or git commit information.

### Environment information:
Provide detailed information on the *scanning* and *target* systems (if applicable); see example below.

Type            | Operating System | OS Version | Python Version | Virtualization
--------------- | ---------------- | ---------- | -------------- | --------------
Scanning System | RHEL             | 7.4        | 3.6            | Bare Metal
Target System   | RHEL             | 5.9        | 2.4.6          | RHEV

**Comment by kholdaway** [comment]
I know we don't support upgrade via this installer.  That's something we should take a look at.

**Comment by mdvickst** [comment]
I believe the issue is because it found a version in the packages directory so it didn't download the newer version. 

TASK [qpc_server : Set find_qpc_server_local_path] *******************************************************************************************************
ok: [localhost] => {"ansible_facts": {"find_qpc_server_local_path": "/root/install/packages/quipucords.0.0.43.tar.gz"}, "changed": false}

**Comment by kholdaway** [comment]
Yep.  It could check for version instead of `quipucords*.tar.gz`
