### ISSUE TITLE
Merging job reports causes 'Connection aborted' error inside of docker container

### ISSUE THREAD

**Issue by kholdaway** [quipucords/quipucords#1457]
## Bug Description:
When merging 7 reports, the QPC server fails with the following error:
A connection error occurred while attempting to communicate with the server. To troubleshoot this problem, check the configuration and the status of the server.
('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

### Expected behavior:
Reports would be merged

### Actual behavior:
'Connection aborted.', RemoteDisconnected('Remote end closed connection without response'

### Steps to reproduce:
Merge several large reports
___

**Comment by kholdaway** [comment]
Looks like gunicorn is just timing out.  I can bump the default timeout to 120 instead of 30.  

Additionally, I am seeing a these two errors:
```
ERROR Could not parse date 2017-11-21 13:42:21 -0500: unconverted data remains:  -0500
ERROR Could not parse date 2017-04-17 12:00:51 -0400: unconverted data remains:  -0400
```

```
{'vm_dns_name': ['This field may not be blank.']
```

**Comment by mdvickst** [comment]
I could see merge being used for a large number of scans, so I'm wondering if 120 seconds might still not be long enough. I'm talking with 1 customer who could have 100's of scans merged in one sweep.

**Comment by kholdaway** [comment]
We may need to rethink merge in that case. This is the http timeout. An async job may be a better fit.

**Comment by kholdaway** [comment]
Maybe as a stopgap I will add an environment variables to allow timeout to be configured when the docker container starts.
