### ISSUE TITLE
Some VMs which are present in Network and vCenter sources show "unknown" under infrastructure_type

### ISSUE THREAD

**Issue by mdvickst** [quipucords/quipucords#1521]
## Bug Description:
If a VMs does not have a virt.virt value from the Network scan but is in vCenter it currently shows "unknown" under infrastructure_type. 

### Expected behavior:
Anything that is present in a vCenter source should automatically be marked as a "virtualized" under infrastructure_type. 

### Steps to reproduce:
List clear steps to reproduce the bug.

___

## Acceptance Criteria:

- [ ] Verify that network scan with blank value for virt.virt but which is also seen in a vcenter source has virtualized under infrastructure_type. 
___

### Version Information:
CLI version, server version or git commit information.

### Environment information:
Provide detailed information on the *scanning* and *target* systems (if applicable); see example below.

Type            | Operating System | OS Version | Python Version | Virtualization
--------------- | ---------------- | ---------- | -------------- | --------------
Scanning System | RHEL             | 7.4        | 3.6            | Bare Metal
Target System   | RHEL             | 5.9        | 2.4.6          | RHEV

**Comment by kholdaway** [comment]
👍
