### ISSUE TITLE
Network scan results not properly merged if not registered and not using privilege escalation

### ISSUE THREAD

**Issue by mdvickst** [quipucords/quipucords#1546]
## Bug Description:
Given the de-duplicaiton logic below servers scanned that aren't registered to Satellite or RHSM won't have a subscription-manager ID and if they aren'te scanned with root/sudo we won't get the UUID either. 

> All systems from network sources are combined into a single network system set. Systems are considered to be duplicates if they have the same value for the subscription_manager_id or bios_uuid facts.

### Expected behavior:
We should fallback to a third alternate fact to compare hosts by which does not require elevated privileges. 

### Actual behavior:
treats these records as different systems. 

### Steps to reproduce:
List clear steps to reproduce the bug.

___

## Acceptance Criteria:

- [ ] Verify that users can X Y Z
- [ ] Verify that an expected error is encountered when a user does A B C

___

### Version Information:
CLI version, server version or git commit information.

### Environment information:
Provide detailed information on the *scanning* and *target* systems (if applicable); see example below.

Type            | Operating System | OS Version | Python Version | Virtualization
--------------- | ---------------- | ---------- | -------------- | --------------
Scanning System | RHEL             | 7.4        | 3.6            | Bare Metal
Target System   | RHEL             | 5.9        | 2.4.6          | RHEV

**Comment by kholdaway** [comment]
@mdvickst Are you thinking mac_addresses?  Do you have other ideas?

**Comment by justinkreft** [comment]
Stale
