### ISSUE TITLE
Support for non-bash shells

### ISSUE THREAD

**Issue by mdvickst** [quipucords/quipucords#1580]
### Is your feature request related to a problem?
Non-Bash shells might be in use (e.g. csh) which might not fully support our commands ( e.g. 2> isn't supported by csh) 

### Describe the solution you'd like
Detect different shells and either don't run incompatible commands or run a more compatible version. 

___

## Acceptance Criteria:

- [ ] Verify that users can X Y Z
- [ ] Verify that an expected error is encountered when a user does A B C

___

**Comment by gtanzillo** [comment]
It would be helpful to test this scenario on a RHEL machine that has bash disabled to see which commands fail. That would be a determining factor for the priority of this issue

**Comment by gtanzillo** [comment]
This is being tracked on the Discovery roadmap
