### ISSUE TITLE
Allow exclude_hosts to be modified after a scan is running

### ISSUE THREAD

**Issue by kholdaway** [quipucords/quipucords#1589]
## Feature description:
A very large scan may hang a scan.  It would be useful to exclude the problem host without restarting the entire scan.  My thought is that when the inspection scan starts, we consider excluded hosts.   Currently only the connection scan utilizes exclude hosts.  

Usage:
1) Inspection scan hangs so pause scan
2) Update source to exclude problematic host
3) Restart scan

**Comment by gtanzillo** [comment]
This is tracked on 1.x eng roadmap
