### ISSUE TITLE
Change qpc report merge-status command output

### ISSUE THREAD

**Issue by elyezer** [quipucords/quipucords#1593]
### Is your feature request related to a problem?
`qpc report merge-status` was added recently and its purpose is similar to the `qpc scan job`: to monitor a job. The problem is that now we have two output styles, the `qpc report merge-status` outputs plain text while `qpc scan job` outputs JSON. That is not a consistent behavior and is not intuitive to the users.

### Describe the solution you'd like
Given the description above, I think the output of the `qpc report merge-status` should be changed and be in the JSON style. Also I think it would be easier to users if the command was renamed to something like `qpc report job` or `qpc report merge-job` or `qpc report merge job` to be similar to `qpc scan job` since both are used to monitor a job.

___

## Acceptance Criteria:

- [ ] Verify that the `qpc report merge-status` is providing a JSON like output
- [ ] Verify that the `qpc report merge-status` is renamed to `qpc report job` or another name.

**Comment by kholdaway** [comment]
I chatted with @elyezer offline.  Some of the outputs.

Make `qpc scan job` more like `qpc report merge-status`.

Change `qpc scan job` to `qpc scan job-status` and modify output to match `qpc report merge-status` format.  This provides the user more guidance to know how to retrieve the report.
