### ISSUE TITLE
ActiveDirectory login fails when connecting to vCenter

### ISSUE THREAD

**Issue by tommyrico81** [quipucords/quipucords#1649]
## Bug Description:

When Active Directory is used to connect into vCenter and the service account that is used to login into the vCenter client is "Domain\SVC_satadmin". I am finding that the credential fails when running a scan with QPC.

When creating a credential with QPC using the domain user login "Domain\SVC_admin" with a fwd slash. QPC does not save this slash when it stores it in the cred. The fwd slash is missing when verifying the cred in QPC - "DomainSVC_satadmin". When adding 2 fwd slashes, both slashes are saved within the cred. "Domain\\SVC_satadmin"

### Expected behavior:

QPC should authenticate with vCenter as long as the credential is valid when logging into the vCenter client

### Actual behavior:

QPC provides an error stating that the credential is invalid when reviewing the scan job

### Steps to reproduce:

Create a credential
qpc cred add --type vcenter --name vcred1 --username Domain\SVC_satadmin --password

View credential 

qpc cred list
___

## Acceptance Criteria:

- [ ] Users can create a credential, create a source, create a scan, run the scan with QPC
- [ ] User cannot authenticate with vCenter using the provided credentials, preventing the scan from completing.

___

### Version Information:
CLI version, server version or git commit information.

version 0.0.44

### Environment information:
Provide detailed information on the *scanning* and *target* systems (if applicable); see example below.

Type            | Operating System | OS Version | Python Version | Virtualization
--------------- | ---------------- | ---------- | -------------- | --------------
Scanning System | RHEL             | 7.4        | 3.6            | Bare Metal
Target System   | RHEL             | 5.9        | 2.4.6          | RHEV

**Comment by kholdaway** [comment]
@mdvickst, @myersCody has been looking at this all day.  I will let him give updates as to what he has found.

**Comment by mdvickst** [comment]
Just confirmed potential workaround is to escape the username e.g. domain\\user.

**Comment by tommyrico81** [comment]
@myersCody @kholdaway - I second Mark's approach. Just received confirmation that the following command worked for my usecase. The confusion is when viewing the cred and seeing that a double slash is present. When actually running the scan, it is successful however.

qpc cred add --name newuser --type vcenter --username domain\\username --password

**Comment by kholdaway** [comment]
This is strange.  If you run the following commands:
```
qpc cred add --type network --username foo\bar --name t0  --password
qpc cred add --type network --username "foo\bar" --name t1  --password
qpc cred add --type network --username foo\\bar --name t2  --password
```

t1 and t2 are stored exactly in the db.
```qpc cred show --name t0
{
    "become_method": "sudo",
    "become_user": "root",
    "cred_type": "network",
    "id": 1,
    "name": "t0",
    "password": "********",
    "username": "foobar"
}
(qpc-yLOmrboY) bash-3.2$ qpc cred list
[
    {
        "become_method": "sudo",
        "become_user": "root",
        "cred_type": "network",
        "id": 1,
        "name": "t0",
        "password": "********",
        "username": "foobar"
    },
    {
        "become_method": "sudo",
        "become_user": "root",
        "cred_type": "network",
        "id": 2,
        "name": "t1",
        "password": "********",
        "username": "foo\\bar"
    },
    {
        "become_method": "sudo",
        "become_user": "root",
        "cred_type": "network",
        "id": 3,
        "name": "t2",
        "password": "********",
        "username": "foo\\bar"
    }
]```

I think @myersCody suggested using `"foo\bar"`.  @tommyrico81 Did that fail when you tried it?  I can't see how they would be any different based on how they are stored.

We cannot test this since we don't have a system.  I would like to update the troubleshooting section.  Could you test the method with quotes (e.g. "foo\bar") again so we can document it?

**Comment by tommyrico81** [comment]
Since Github escapes the fwd slash as well, the attached screen shot is the method that worked for my end-user.

![screen shot 2018-11-06 at 3 03 04 pm](https://user-images.githubusercontent.com/8271775/48099684-3a779800-e1d5-11e8-86da-693a4e300d28.png)

**Comment by kholdaway** [comment]
Nice!  Thanks.
