### ISSUE TITLE
Change default port for Quipucords server to 9443

### ISSUE THREAD

**Issue by mdvickst** [quipucords/quipucords#1651]
## Feature description:
Since QPC could potentially be installed on a system with other HTTPS services, we should choose a port other than the default. A good example is customers may have their Satellite server configured to be able to communicate with all RHEL servers in the network through SSH, so it's a good candidate to run QPC, but if QPC is installed, it will conflict with satellite on the default port. 

### Is your feature request related to a problem?
Potential to conflict with common applications

### Describe the solution you'd like
Change it to something less common through the automated installer and change the CLI to connect to that port by default. I think 8443 was suggested, but it might also be too common since JBoss EAP and others use it.

We will use 9443
___

## Acceptance Criteria:

- [ ] Verify that user who installs QPC with automated installer can log in without changing settings on CLI
- [ ] Verify that application configured for HTTPS already on the box are not affected by QPC's port

___

**Comment by cdcabrera** [comment]
Double checked, since it appears we only use root references for our UI build prod config, can confirm, looks like everything is covered for the client directory @myersCody @kholdaway
