### ISSUE TITLE
Simplify the subscription manager id collections

### ISSUE THREAD

**Issue by kholdaway** [quipucords/quipucords#1682]
See if we can replace
```subscription-manager facts --list 2>/dev/null | grep '^virt.uuid.' | sed -n -e 's/^.*virt.uuid.\s*//p'```

with 

```subscription-manager identity```

Additionally, Jesse indicated that bios_uuid is the same as subscription-manager identity.  The fingerprint engine should deduplicate on this also.

**Comment by myersCody** [comment]
After logging onto a test server and trying both commands I get different outputs
`$ subscription-manager identity`
Output: `This system is not yet registered. Try 'subscription-manager register --help` 


Whereas the command: 
`$ subscription-manager facts --list 2>/dev/null | grep '^virt.uuid.' | sed -n -e 's/^.*virt.uuid.\s*//p'`
Did return a valid `virt.uuid`.

**Comment by gtanzillo** [comment]
closing based on the above comment regarding investigation of this approach
