### ISSUE TITLE
Can't merge reports over the UI

### ISSUE THREAD

**Issue by elyezer** [quipucords/quipucords#1709]
## Bug Description:
An error is showed when trying to create a detailed or summary merge report.

See the screen shot:

![screenshot from 2018-11-22 16-10-29](https://user-images.githubusercontent.com/48132/48918056-4324cb00-ee71-11e8-9d32-e21795aa6f09.png)

It seems that the UI is trying to reach a non-existent endpoint.

### Expected behavior:
A merge report is created.

### Actual behavior:
An error is raised and no merge report is generated.

### Steps to reproduce:
1) Run two or more scans
2) On the Scans page, select at least two scan entries and try to generate a merge report by using the `Merge Report` dropdown button on the top right

___

## Acceptance Criteria:

- [ ] Verify that users can generate detailed merge reports
- [ ] Verify that users can generate summary merge reports

___

### Version Information:
1aa29c2175dd34e4f85b9e541b0479b0a08add88

### Environment information:

Any scan should produce this error.

**Comment by kholdaway** [comment]
Our team will take a look at this first.  We should make sure we didn't break the UI with an accidental API change.

**Comment by elyezer** [comment]
@kholdaway looking on the error message it seems that UI is trying to access the `/api/v1/reports/undefined/deployments/` mind the `undefined` which I think is some lost reference it has.
