### ISSUE TITLE
Can't pause or cancel a scan over the UI

### ISSUE THREAD

**Issue by elyezer** [quipucords/quipucords#1710]
## Bug Description:
It is not possible to cancel or pause a scan that is running on the `Scans` page.

Trying to push the Pause Scan or Cancel Scan buttons an error is raised and the requested action is not performed. See the screenshot below:

![screenshot from 2018-11-22 16-26-31](https://user-images.githubusercontent.com/48132/48918420-81bb8500-ee73-11e8-964c-a1afd167b962.png)

### Expected behavior:
The pause and cancel scan buttons should work

### Actual behavior:
The pause and cancel scan buttons are not working

### Steps to reproduce:
1) Create and start a scan
2) While it is running, try to pause or cancel the scan on the `Scans` page

___

## Acceptance Criteria:

- [ ] Verify that users can pause and restart a Scan over the UI
- [ ] Verify that users can stop a Scan over the UI

___

### Version Information:
1aa29c2175dd34e4f85b9e541b0479b0a08add88

### Environment information:

This should happen with any scan

**Comment by cdcabrera** [comment]
Note:
Looks like the UI and API are a little out of sync... per the Swagger spec there are several response codes being generated, the UI currently doesn't handle errors beyond the toast notification, just need to tweak the error handler for jobs

```
200 | Scan job paused
400 | Scan job not running
401 | Not authorized
404 | Scan job not found
```

**Comment by cdcabrera** [comment]
@kholdaway @himmAllRight closing this down for now. we can always re-open it if it pops back up.
