### ISSUE TITLE
Scan status is never updated on the UI when completed 

### ISSUE THREAD

**Issue by elyezer** [quipucords/quipucords#1711]
## Bug Description:
Starting a scan and checking its status on the Scans page will show that the `Job is pending.` but this status never updates unless the page is refreshed.

### Expected behavior:
The scan status should get updated when the scan job is completed.

### Actual behavior:
The `Job is pending` status is never updated.

### Steps to reproduce:
1) Create and start a scan
2) Navigate to the `Scans` page and check its status. It should be `Job is pending`.
3) Watch the quipucords server log until the started scan job is completed.
4) Come back on the UI and it should not be updated, saying that the scan was completed. (It will update the status if the page is refreshed).
___

## Acceptance Criteria:

- [ ] Verify that the scan status will be updated on the Scans page.

___

### Version Information:
1aa29c2175dd34e4f85b9e541b0479b0a08add88

### Environment information:

This should happen with any scan.

**Comment by cdcabrera** [comment]
This request is more related to a polling feature, something not currently implemented. Looking at working this into the parallel issue of #1822

**Comment by kholdaway** [comment]
Issue moved to [quipucords/quipucords-ui #17](https://github.com/quipucords/quipucords-ui/issues/17) via [**ZenHub**](https://www.zenhub.com/)
