### ISSUE TITLE
Deployment report should capture whether host facts were gathered with elevated privileges

### ISSUE THREAD

**Issue by benneteapen** [quipucords/quipucords#1722]
## Feature description:

I know QPC runs best with elevated privileges. But a lot of people end up running without the necessary privileges. Although it works fine, it doesn't end up scanning the networks properly. Can a warning message be provided if QPC is tried to be run without necessary privileges ?

**Comment by kholdaway** [comment]
@benneteapen Just for clarification.  Are you talking about CLI, UI, logging, or all?  This may not be something we know until we can.  A sudo user may not have access to all the required commands.  In other words, notification via CLI and UI may not be possible.  We could capture that after running a scan.

**Comment by benneteapen** [comment]
@kholdaway I totally get what you're saying Kevan. But is it possible to give some sort of a warning when a  sudo password or a become password is not provided when trying to run QPC ?

**Comment by kholdaway** [comment]
Not without running a scan.

**Comment by dozdowski** [comment]
What about at the source creation level?  When building a source we could look at the credentials associated with it.  Should none of the credentials match root OR contain a sudo, we could alert at that time that discovery will function with diminished capacity.

@benneteapen Can you confirm which method you're using?  CLI vs UI?

Cheers,
Dan

**Comment by kholdaway** [comment]
A scan has a many-to-many credential/source relationship.  One system may connect with the sudo and another may not.  Additionally, the `dan` user may have sudo on one system and not on another.

So really it's difficult to know this before a scan.  A single credential is used across various systems.  Until we try and run our check for sudo, we do not know the authorization level on that system.  Could we guess?  Only if they use root can say that looks good.  Other than that, it is a black box.  Even if they use become user/password we don't really know If that system has given that user sudo.  A warning ultimately would always need to be shown.  

My suggestion is to capture that as part of the report.  This is after a scan but it can be useful to know why things are this way.  We would need to capture this on a per system basis.  That way we can explain why a system's facts are so lean.  We mark the system as not having elevated privileges and thus understand why.

**Comment by benneteapen** [comment]
@dozdowski I'm using the CLI

**Comment by benneteapen** [comment]
I was going through the chat on the qpc_dev channel. I see where you're coming from Kevan. A warning prior to running a scan would probably generate false positives and can never be accurate. In that case would it be possible to include a line in the report which states if elevated credentials were used to run the scan?

**Comment by kholdaway** [comment]
Absolutely. I think that is useful metadata for interpreting results.
