### ISSUE TITLE
Add hypervisor cores to fields to pull from vCenter

### ISSUE THREAD

**Issue by mdvickst** [quipucords/quipucords#1725]
### Is your feature request related to a problem?
We pull vm_host CPU sockets right now but not the total number of CPU cores on the vm hypervisor host. This is needed for JBoss subscriptions since customers have the option to subscribe by the number of vCPUs where JBoss is running or by the number of CPU cores on the hypervisor. 

### Describe the solution you'd like
Add column in details report and summary report which shows the number of CPU cores on the hypervisor from VMware. 

___

## Acceptance Criteria:

- [ ] Verify that users can X Y Z
- [ ] Verify that an expected error is encountered when a user does A B C

___

**Comment by dozdowski** [comment]
This is a good one; I didn't realize that this fact wasn't in place already.  This is potentially an area where Adam could lend advice on how to pull the info.

**Comment by mdvickst** [comment]
I believe this is in the details report but not in the summary/deployments report. It would be nice to have it in the deployments report as well.
