### ISSUE TITLE
Stop connection scan when source is added through GUI

### ISSUE THREAD

**Issue by mdvickst** [quipucords/quipucords#1754]
### Is your feature request related to a problem?
When a source is added to QPC through the GUI it does a connection scan. For network sources this could take a really long time and will get repeated when the scan is started. Typical customers will add the source then pretty soon after start a scan with it so this doubles the connection scans done. 

For Satellite and vCenter I think it is helpful to make sure you can log in (e.g. no SSL cert errors etc.) but I think a scan would provide the same functionality.

### Describe the solution you'd like
I think just remoivng the initial connection scan would help but maybe moving some of the unreachable or login failed icons/counts to the scan might help get that same valuable information from the scan page so they don't have to jump back and forth between scans and sources. 

___

## Acceptance Criteria:

- [ ] Verify that users can X Y Z
- [ ] Verify that an expected error is encountered when a user does A B C

___

**Comment by kholdaway** [comment]
Issue moved to [quipucords/discovery #7](https://github.com/quipucords/discovery/issues/7) via [**ZenHub**](https://www.zenhub.com/)
