### ISSUE TITLE
Maybe Change "name" for sources, creds etc to "label"

### ISSUE THREAD

**Issue by mdvickst** [quipucords/quipucords#1762]
### Is your feature request related to a problem?
I find many users are confused on the difference between "name" and "username". I find when I describe that "name" is just a label to reference the credential by later they get it. Maybe "label" would be more intuitive as to what customers need to enter in that field. 

### Describe the solution you'd like

___

## Acceptance Criteria:

- [ ] Verify that users can X Y Z
- [ ] Verify that an expected error is encountered when a user does A B C

___

**Comment by kholdaway** [comment]
@mdvickst Is this a UI suggestion?

**Comment by mdvickst** [comment]
My thought is that it would be across the board, UI, CLI and docs but I
know that's a lot of changes so I'm not sure the effort is worth it. I just
wanted to throw this out there in case others are seeing the same thing.
--
Mark Vickstrom
Senior Solutions Architect | Subscription Education and Awareness
100 E Davie Street
Raleigh, NC 27604
T: +1 (919) 754-4479
M: +1 (704) 819-3222

**Comment by justinkreft** [comment]
Closed. current UI is sufficient

**Comment by justinkreft** [comment]
Closing
