### ISSUE TITLE
GUI doesn't allow CIDR notification for /23 and larger

### ISSUE THREAD

**Issue by mdvickst** [quipucords/quipucords#1783]
## Bug Description:
192.168.56.0/23 isn't a valid input in GUI, should allow for /23, /22 all the way down to /16. Anything larger than /16 might be a performance concern.

### Expected behavior:
Describe the expected behavior for the program.

### Actual behavior:
Provide the actual behavior for the program.

### Steps to reproduce:
List clear steps to reproduce the bug.

___

## Acceptance Criteria:

- [ ] Verify that users can X Y Z
- [ ] Verify that an expected error is encountered when a user does A B C

___

### Version Information:
CLI version, server version or git commit information.

### Environment information:
Provide detailed information on the *scanning* and *target* systems (if applicable); see example below.

Type            | Operating System | OS Version | Python Version | Virtualization
--------------- | ---------------- | ---------- | -------------- | --------------
Scanning System | RHEL             | 7.4        | 3.6            | Bare Metal
Target System   | RHEL             | 5.9        | 2.4.6          | RHEV

**Comment by cdcabrera** [comment]
As of 20190301 resolution has merged
