### ISSUE TITLE
UI: Update framework and syntax

### ISSUE THREAD

**Issue by cdcabrera** [quipucords/quipucords#1791]
### Is your feature request related to a problem?
React framework and general optimization updates (Or making the GUI devs lives easier by making this repository reflect updated knowledge for how we structure code bases). 

Currently the GUI is fixed on a specific version of React. In order to upgrade various syntax and React life cycle methods need to be altered. 

### Describe the solution you'd like
Behind the scenes GUI code updates:
- Update services to remove class based structure
- Update redux structure in an effort to simplify state
  - evaluate selectors 
  - update toolbar filters
- Update legacy React life cycle methods within components
  - this should bring with it a reduction in component complexity
- Expand unit tests and coverage to promote GUI code stability, and relax the need to always require another UI dev resource in addition to the QE team reviews
  - expose coverage and build aspects on the GUI Readme, aim for a minimum of 70% + coverage
___

## Acceptance Criteria:
- [x] Services should no longer contain class based structure
  - separate helper functions into `common/helpers`
- Clean up Redux structure, should include 
  - [x] removing unused types, actions, reducer checks
  - ~clean up lodash usage within redux, evaluate `lodash-es`~ until we can move to a newer version of the react scripts going to delay this
  - [x] unit tests expanded
- [x] Verify that users see no discernible negative difference within the GUI. increases in response and render time may be a positive outcome
- [ ] Verify that GUI unit tests are expanded and achieve a minimum of 70% coverage
  - [ ] Component testing 
  - [x] State / Redux testing
  - [x] Services testing
- [ ] Verify that legacy React life cycle methods have been removed... searching in the code base for `componentWillReceiveProps` should return 0 results 

## Related issues
#1520

**Comment by kholdaway** [comment]
Issue moved to [quipucords/quipucords-ui #18](https://github.com/quipucords/quipucords-ui/issues/18) via [**ZenHub**](https://www.zenhub.com/)
