### ISSUE TITLE
User Story: Method to mark a system as having a JBoss product on future scans

### ISSUE THREAD

**Issue by mdvickst** [quipucords/quipucords#1792]
### Is your feature request related to a problem?
If a user determines that JBoss EAP is present on a server that is marked as "Potential" there should be some way to mark it as "Present" on future scans.

### Describe the solution you'd like
Either QPC remembers the feedback on that server or it allows for deployment of some sort of marker that identifies that server as having JBoss EAP in future scans. 

___

## Acceptance Criteria:

- [ ] Verify that users can X Y Z
- [ ] Verify that an expected error is encountered when a user does A B C

___

**Comment by kholdaway** [comment]
@mdvickst This would be a very different paradigm from how we do things today.  We don't have a concept of hosts that are persisted between scans.  We would need a persistent way to uniquely identify and store hosts.  The insights service is doing exactly that in their host inventory service.  Duplications are very likely.  Taking this approach would be a very large undertaking.  

I would be interested to know why we think it is potential when it is really present.  Is there a way we can get more information about systems that have this problem?  

Another alternative if for QPC to define a method of marking the system the system (e.g. new file with this information for future scans).

**Comment by mdvickst** [comment]
Maybe we add a new fact that looks for the presence of a special file. E.g. /opt/EAP-present which would have a well defined value inside which customers could deploy to each server they want counted. 

An example of where we fail even with extended searches is if Java is not in the path then we cannot inspect the jars to determine which version they are so even if we find jboss-modules.jar we cannot know for sure if it is EAP or community so the customer would need to be able to force the tool to mark it as present rather than keep a manual list and have to edit the output each time they run the tool.

**Comment by dozdowski** [comment]
My suggestions here are to give the customer two things:

1) Simpler detection built into the product itself (I hope to get back to in-product subscription work sometime soon), and
2) Rich options at the platform level.  We can offer them matches against subnet, DNS name, etc, along with an automatic "this system has JBoss EAP" tag.

The first option helps everyone but is less imminent, and the second option at least helps customers engaging with our service offerings.

**Comment by justinkreft** [comment]
Closed. won't fix. current.
