### ISSUE TITLE
A user should be able to cancel or pause a satellite 5/6 connection scan

### ISSUE THREAD

**Issue by kholdaway** [quipucords/quipucords#1814]
## Feature description:

A user should be able to cancel or pause a satellite 5/6 connection scan

**Comment by gtanzillo** [comment]
This is about supporting partial scans. It's already supported for network scans. And Center scans are fast enough that it is likely not necessary. for satellite, it would still be good to have because those scans take a lot of time. But we'd only be interested in Satellite 6
