### ISSUE TITLE
QPC server should provide a new endpoint for obtaining insights formatted reports

### ISSUE THREAD

**Issue by kholdaway** [quipucords/quipucords#1815]
### Describe the solution you'd like
- Create new endpoint `GET` at path `/api/v1/reports/{id}/insights`
- Additionally modify `GET` at path `/api/v1/reports/{id}` to include the insights report in the tar.gz.
___

**Comment by abaiken** [comment]
Closed in https://github.com/quipucords/quipucords/pull/1830
