### ISSUE TITLE
UI: Sources, Add Creation Options

### ISSUE THREAD

**Issue by cdcabrera** [quipucords/quipucords#1821]
## Feature description:

As a QPC user, I want to use the UI to create my sources but it lacks several options present in the CLI.  The QPC source creation dialogue should include inputs for:

- Create a source with --ssl-protocol
- Create a source with --disable-ssl
- Create a source with --use-paramiko

### NOTES:
--ssl-protocol is mutually exclusive with --disable-ssl
--ssl-protocol accepts valid inputs of {SSLv23,TLSv1,TLSv1_1,TLSv1_2}
--use-paramiko is mutually exclusive with --disable-ssl
--use-paramiko is mutually exclusive with --ssl-protocol 

___

## Acceptance Criteria:

- [ ] Verify that users can create a source with --ssl-protocol
- [ ] Verify that users can create a source with --disable-ssl
- [ ] Verify that users can create a source with --use-paramiko
- [ ] Verify that validation resolves issue #1783 host validation

## Related Issues/Stories
#1783

**Comment by bclarhk** [comment]
![add network range](https://user-images.githubusercontent.com/32572198/52434696-fea6e400-2add-11e9-8792-78f25f9c7aeb.png)
![add satellite](https://user-images.githubusercontent.com/32572198/52434697-ff3f7a80-2add-11e9-9e43-58f389eac5c0.png)
![add vcenter](https://user-images.githubusercontent.com/32572198/52434698-ff3f7a80-2add-11e9-9f89-d61fb0ad1330.png)

**Comment by cdcabrera** [comment]
Primary resolution merged as of 20190228, temporarily leaving this open due to #1840

**Comment by kholdaway** [comment]
Issue moved to [quipucords/quipucords-ui #19](https://github.com/quipucords/quipucords-ui/issues/19) via [**ZenHub**](https://www.zenhub.com/)
