### ISSUE TITLE
UI: Scans, Add Creation Options

### ISSUE THREAD

**Issue by cdcabrera** [quipucords/quipucords#1822]
## Feature description:

As a user of the QPC UI I wish to create scans with options offered by the CLI.  The QPC UI shall add options allowing:

- Create a scan with --max-concurrency
- Create a scan with --disabled-optional-products
- Create a scan with --enabled-ext-product-search
- Create a scan with --ext-product-search-dirs

--disabled-optional-products accepts values of {jboss_eap,jboss_fuse,jboss_ws,jboss_brms} - labels should be obviously indicative but do not have SPECIFIC product requirements.
--ext-product-search-dirs is dependent on --enabled-ext-product-search=true and accepts a list of directories as valid input
___

## Acceptance Criteria:

- [ ] Verify that users can create a scan with --max-concurrency
- [ ] Verify that users can create a scan with --disabled-optional-products
- [ ] Verify that users can create a scan with --enabled-ext-product-search
- [ ] Verify that users can create a scan with --ext-product-search-dirs

## Related Issues/Stories
#1711

**Comment by bclarhk** [comment]
Wireframe:
![scan 1](https://user-images.githubusercontent.com/32572198/53580406-8ca84480-3b49-11e9-8b8a-38b416b92224.png)
