### ISSUE TITLE
Export All Feature

### ISSUE THREAD

**Issue by mdvickst** [quipucords/quipucords#1839]
## Feature description:
It is challenging to write easy instructions for users of the tool on how to properly merge and download the required reports from all scans. Often times users send just the reports from all scans run (usually 1 scan per source) and so manual merging is required. A feature that automatically merges the all scan-jobs and then executes the "qpc report download" command for that new "super" report would help tremendously because it would eliminate confusing documentation or constant back and forth with users to get them to properly merge all scans and download the report. 
Below are some of the scenarios that this feature would help solve
- customers run a scan but forget to export the report for that scan
- customers don't merge reports before sending the results
- customers send only details or only deployments reports

I think all scan-jobs should be included not just latest because it will help users who are running periodic check-up reports to have a record of all servers. They will be able to tell what servers were added based on install_date and which servers were decommissioned based on last_checkin. The master merge will have many duplicates but will need to take data from the most recent scan. 

### Describe the solution you'd like

___

## Acceptance Criteria:

- [ ] Verify that users can X Y Z
- [ ] Verify that an expected error is encountered when a user does A B C

___

**Comment by kholdaway** [comment]
@mdvickst We should probably have a conversation about this one.

**Comment by kholdaway** [comment]
Based on the discussion today.  * Solution: 
    * Server: new API to merge most recent scan results for all sources
    * CLI could kick off this scan, poll job to determine when complete, and download the report zip when done
