### ISSUE TITLE
Getting started wizard

### ISSUE THREAD

**Issue by mdvickst** [quipucords/quipucords#1840]
## Feature description:
It would be very helpful to have a wizard that prompts customers to add 1 or more network sources, 1 or more vcenters sources and 1 or more satellite sources. This would make sure that customers add all sources if they have them and not just rely on 1 or 2 sources. 

I think this is more targeted at the GUI but I could see a CLI prompt being helpful as well. 

### Is your feature request related to a problem?
Please describe.  A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

### Describe the solution you'd like

___

## Acceptance Criteria:

- [ ] Verify that users can X Y Z
- [ ] Verify that an expected error is encountered when a user does A B C

___

**Comment by cdcabrera** [comment]
This issue probably should have been linked to issue #1821 

@bclarhk thoughts?

**Comment by kholdaway** [comment]
Issue moved to [quipucords/quipucords-ui #21](https://github.com/quipucords/quipucords-ui/issues/21) via [**ZenHub**](https://www.zenhub.com/)

**Comment by kholdaway** [comment]
Issue moved to [quipucords/quipucords-ui #22](https://github.com/quipucords/quipucords-ui/issues/22) via [**ZenHub**](https://www.zenhub.com/)
