### ISSUE TITLE
Update docs to represent new "Report Download" feature

### ISSUE THREAD

**Issue by mdvickst** [quipucords/quipucords#1844]
### Is your feature request related to a problem?
The quick start guide on the docs still references downloading the deployments and details reports separately. I think we should change that to just reference the "download" command.

### Describe the solution you'd like

___

## Acceptance Criteria:

- [ ] Verify that users can X Y Z
- [ ] Verify that an expected error is encountered when a user does A B C

___

**Comment by kholdaway** [comment]
Issue moved to [quipucords/quipudocs #18](https://github.com/quipucords/quipudocs/issues/18) via [**ZenHub**](https://www.zenhub.com/)
