### ISSUE TITLE
Update Installer Download Link in Doc

### ISSUE THREAD

**Issue by benneteapen** [quipucords/quipucords#1893]
Currently the link to download the installer in the Quipucords Documentation is shown as :
# curl -k -O -sSL https://github.com/quipucords/quipucords/releases/download/0.0.46/quipucords.install.0.0.46.tar.gz
The file name in the link should be **quipucords.0.0.46.install.tar.gz**

**Comment by kholdaway** [comment]
Issue moved to [quipucords/quipudocs #17](https://github.com/quipucords/quipudocs/issues/17) via [**ZenHub**](https://www.zenhub.com/)

**Comment by kholdaway** [comment]
Moved issue to doc repo
