### ISSUE TITLE
Install script does not recognize install_offline=false

### ISSUE THREAD

**Issue by abaiken** [quipucords/quipucords#1922]
## Bug Description:
When i run `./install.sh -e install_offline=false` it still checks to see if the files necessary for offline install exist even though I specified it as false. 

### Expected behavior:
If a user sets install_offline=false we should not fail if the files needed for offline install do not exist.

### Actual behavior:
```
[vagrant@vrhel6 vagrant_data]$ ./install.sh -e install_offline=false
Checking if required files exist for an offline installation.
packages//quipucords.1.0.0.tar.gz is required for an offline installation.
```

### Steps to reproduce:
Install qpc on a vagrant machine with the `install_offline=false` argument. Make sure that you do not have the tar.gz in your packages directory.

___

## Acceptance Criteria:

- [ ] Verify that install_offline can be set to false & work as expected

___

### Version Information:
CLI version, server version or git commit information.

### Environment information:
Provide detailed information on the *scanning* and *target* systems (if applicable); see example below.

Type            | Operating System | OS Version | Python Version | Virtualization
--------------- | ---------------- | ---------- | -------------- | --------------
Scanning System | RHEL             | 7.4        | 3.6            | Bare Metal
Target System   | RHEL             | 5.9        | 2.4.6          | RHEV

**Comment by kholdaway** [comment]
Issue moved to [quipucords/quipucords-installer #7](https://github.com/quipucords/quipucords-installer/issues/7) via [**ZenHub**](https://www.zenhub.com/)
