### ISSUE TITLE
Expand coverage of RH Product offerings

### ISSUE THREAD

**Issue by williamlehman** [quipucords/quipucords#1931]
### Is your feature request related to a problem?
Clarifying for all users the exact details of the columns will help with user comprehension and allow us to import to a UI later. 

### Describe the solution you'd like
Consumers often don't know what they are looking at and find it hard to decode what the output is presenting to them.

___

## Acceptance Criteria:

- [ ] Verify that users can easily find and consume the data presented

___

## Additional context
The column data points are often unclear to some. Particularly non-technical people.

**Comment by kholdaway** [comment]
I am going to move this issue to the documentation repository.

**Comment by kholdaway** [comment]
Issue moved to [quipucords/quipudocs #35](https://github.com/quipucords/quipudocs/issues/35) via [**ZenHub**](https://www.zenhub.com/)
