### ISSUE TITLE
Include more RH Products

### ISSUE THREAD

**Issue by williamlehman** [quipucords/quipucords#1932]
### Is your feature request related to a problem?
Capturing more data relevant to asset management will be beneficial

### Describe the solution you'd like
I would like for this tool to capture the entirety of the RH Product Families so it can be an all-encompassing tool.
___

## Acceptance Criteria:

- [ ] Verify that the entirety of the RHEL Product Family is pulled
- [ ] Verify that the entirety of the RH Middleware Product Family is pulled
- [ ] Verify that the entirety of the RH Cloud Services Product Family is pulled
- [ ] Verify that the entirety of the RH Developer Product Family is pulled
- [ ] Verify that the entirety of the RH Cloud Platform Product Family is pulled
- [ ] Verify that the entirety of the RH Management Product Family is pulled
- [ ] Verify that the entirety of the RH Cloud Storage and Hyperconverged Product Family is pulled

___

**Comment by kholdaway** [comment]
This looks like several issues. We can keep this until it is prioritized and split. Thanks!  Great feedback!

**Comment by justinkreft** [comment]
This is being addressed internally.
