### ISSUE TITLE
Create/Update Jenkins slave with necessary Docker and Openshift CLI install dependencies to build Docker image from master branch

### ISSUE THREAD

**Issue by chambridge** [quipucords/quipucords#194]
## Specify type:
- Enhancement

## Description:
Create/Update Jenkins build slave with necessary Docker and openshift command line install dependencies.

Associated with user story #192.

**Comment by chambridge** [comment]
Following PR created:
https://github.com/quipucords/ci/pull/25

@elyezer Will make nodepool updates.

**Comment by elyezer** [comment]
@chambridge https://github.com/quipucords/ci/pull/25 installs docker on the slave but it does not enable it to start with the system, is this required or can we consider this issue done by just making sure the slaves have docker available?

**Comment by chambridge** [comment]
I think its ok that we just make sure the slave has docker available. Any necessary startup can be done in the specific Jenkins job that will create the nightly image.

**Comment by elyezer** [comment]
All images and slaves are now updated and have docker installed:

```console
[fedora@automation ~]$ ssh jenkins@10.8.241.207
[jenkins@f25-np-sonar-jenkins-1281 ~]$ rpm -q docker
docker-1.12.6-7.gitae7d637.fc25.x86_64
[jenkins@f25-np-sonar-jenkins-1281 ~]$ exit
logout
Connection to 10.8.241.207 closed.

[fedora@automation ~]$ ssh jenkins@10.8.242.135
[jenkins@centos7-np-sonar-jenkins-1280 ~]$ rpm -q docker
docker-1.12.6-61.git85d7426.el7.centos.x86_64
[jenkins@centos7-np-sonar-jenkins-1280 ~]$ exit
logout
Connection to 10.8.242.135 closed.

[fedora@automation ~]$ ssh jenkins@10.8.243.92
[jenkins@host-172-16-46-18 ~]$ rpm -q docker
docker-1.12.6-61.git85d7426.el7.x86_64
```
