### ISSUE TITLE
Servers with 0 Red Hat Packages Identified as RHEL Servers

### ISSUE THREAD

**Issue by benneteapen** [quipucords/quipucords#1942]
I came across multiple QPC o/p where the OS is shown to be RHEL but the '**is Redhat**' column is **NO** and the **Number of Red Hat packages** is also **0**. If the OS is RHEL (with a more or less recent release/version) why would the number of RH packages be 0? Or conversely why would a machine with 0 Red Hat packages be identified as a RHEL machine ?

[report_2_details_20190523_162147.xlsx](https://github.com/quipucords/quipucords/files/3251690/report_2_details_20190523_162147.xlsx)
[report_2_summary_20190523_160739.xlsx](https://github.com/quipucords/quipucords/files/3251691/report_2_summary_20190523_160739.xlsx)

In the summary and details sheet you can check out row 10 for eg. to see what I mean...

**Comment by kholdaway** [comment]
Comments from Dan on slack: 
That's an interesting ticket you submitted a bit ago.  Mark gave us 4 criteria he wanted to use for identifying RHEL for SEAP.

1) Installed packaged signed by the Red Hat GPG key
2) /etc/release* files identify it as RHEL
3) Product Certs in place that identify RHEL
4) Active RHEL repos (suggesting that the next time an update was run, Red Hat packages would likely come into play)
Seems like we could have one of factors 2-4 in play.

@benneteapen we still will take a look to make sure it is operating correctly.

**Comment by benneteapen** [comment]
I think I may have figured out what the issue is. The 2nd check point is checking if /etc/*-release files identify as RHEL. Oracle Linux identifies as RHEL in /etc/redhat-release.

The **etc_issue** column in the details file is identified as **Oracle Linux Server** for all machines that identifies as RHEL with 0 Red Hat packages.

This was a false alert I guess. Sorry. I'm closing this issue..
