### ISSUE TITLE
Investigate why we need drf-generators as it is not in fedora

### ISSUE THREAD

**Issue by kholdaway** [quipucords/quipucords#1947]
## Feature description:
Quipucords uses drf-generators==0.4.0 however Fedora does not contain this package.  Investigate why we need it and if we can remove it now that we use Django 2.0.

**Comment by myersCody** [comment]
The `drf-generators` package will generate views, serializers, and urls for the Django Rest Framework. It is an extension that is accessed through the `manage.py`. 

For example: 
	```python manage.py generate {app} {options}``` 

More Info: 
        [readme usage](https://github.com/brobin/drf-generators#usage)

After doing a quick search in the repo, I could not find any instance of `python manage.py generate` being used anywhere. Additionally I believe the intention of this package is to help initially setup the project. The project's [README.md](https://github.com/brobin/drf-generators) even states that it is `not intended to give you a production quality API. It was intended to jumpstart your development and save you from writing the same code over and over for each model`. 

Therefore, I believe we should remove this package from our production requirements, and we can have a discussion about whether or not we want to add it to the `dev-requirements.txt` considering that it seems like we don't actually use it.
