### ISSUE TITLE
Network Scan Error - Worker found in a dead state when scanning /16 subnet

### ISSUE THREAD

**Issue by tommyrico81** [quipucords/quipucords#1966]
## Bug Description:
When scanning a /16 subnet using the network scan which directs Quipucords to scan 65536 ip addresses, Error is encountered during the connection phase which terminates the scan and provided message "Error: A worker was found in a dead state"

### Expected behavior:
Expected behavior is that Quipucords would attempt to connect to each 65536 IP address to validate that a connection could be made prior to moving to inspection phase for data collection.

### Actual behavior:
The network scan groups the IP addresses then begins the connection phase process. After about 1-3 connection groups completed, the scan stops and and Error occurs stating that a worker was found in a dead state, and terminating the scan.

### Steps to reproduce:
qpc cred add --type network --name netcred --username user1 --sshkeyfile /sshkeys/svc_key --become-method sudo 

qpc source add --type network --name netsrc --hosts 10.14.0.0/16 --cred netcred

qpc scan add --name netscan --sources netsrc

qpc scan start --name netscan

## Acceptance Criteria:

Users are able to create a credential, source and scan as usual. What they are not able to do is complete the scan using the subnet provided which is hitting every system on a /16. If applying the same credentials to a individual target host or range of hosts [1:255] the scan is able to complete.

___

### Version Information: 
0.0.46

### Environment information:

These networks have a mix of Linux servers (mostly Centos 6 or 7, but a few random appliances running other versions),  Network devices (mostly Cisco) and Windows servers (2008 and 2016).
We do not have segregated networks for Linux and Windows, and we have network devices listening on every subnet.

**Comment by kholdaway** [comment]
@tommyrico81 Does this work with version 0.9?

**Comment by justinkreft** [comment]
This is addressed in Discovery 1.0
