### ISSUE TITLE
infrastructure_type could potentially have values outside of the allowed choices

### ISSUE THREAD

**Issue by abaiken** [quipucords/quipucords#1968]
## Bug Description:
The `infrastructure_type` is defined in the model with a defined set of choices [here](https://github.com/quipucords/quipucords/blob/master/quipucords/api/deployments_report/model.py#L78): 
```
- virtualized
- bare_metal
- hypervisor
- unknown
```
However, after looking at the [task.py](https://github.com/quipucords/quipucords/blob/master/quipucords/fingerprinter/task.py#L1238) and the [`virt_type` post processor](https://github.com/quipucords/quipucords/blob/master/quipucords/scanner/network/processing/virt.py#L105), it seems like setting the `infrastructure_type` has the potential to cause a traceback because the values it could potentially be set to are outside of those defined above. 

### Expected behavior:
The model should describe all possible choices for `infrastructure_type`

### Actual behavior:
`infrastructure_type` has the potential to be set to a value outside of those defined above, causing a traceback. 

### Steps to reproduce:
Look at the files linked above. 

___

## Acceptance Criteria:

- [ ] Verify that the model describes every choice for `infrastructure_type`
- [ ] Verify that swagger is updated. 

___

**Comment by kholdaway** [comment]
After reviewing the code [task.py](https://github.com/quipucords/quipucords/blob/master/quipucords/fingerprinter/task.py#L1235-L1254) code, I don't think this is a bug.  There will never be a value outside of the expected values.
