### ISSUE TITLE
JBoss Discovery for Windows Server

### ISSUE THREAD

**Issue by tommyrico81** [quipucords/quipucords#1969]
## Feature description:

This feature will be to enable QPC's network scan to detect JBoss Product Installations (EAP, Web Server, Fuse, Decision Manager) on Microsoft Windows Server.

### Is your feature request related to a problem?

The problem that this feature request is associated with are all customer environments that include Windows Server. If a customer is running JBoss on a Windows Server, and our detection method does not allow to inspect Windows machines, we will miss opportunities to detect JBoss installations. This will result in an inaccurate analysis of the customers JBoss usage. 

### Describe the solution you'd like

As part of the network scan, our scanning method would connect to a Windows server using a client that allows for Linux to Windows communication. This would then allow quipucords to run windows specific commands that would allow data to be gathered on a target Windows Server.

___

## Acceptance Criteria:

Users of quipucords should be able to create a network credential that accepts Windows server login credentials. Then create a network source that consists of the Windows Server hosts. Then create a scan and run it against the target Windows environment resulting in the generation of a report. The report will include Windows systems where JBoss product installations are present. This data will also include system info such cpu core counts, installation dates, file paths, etc.. which are necessary for determining consumption.

**Comment by gtanzillo** [comment]
This is tracked on 1.x eng roadmap
