### ISSUE TITLE
Feature to mask Hostname and IP Address

### ISSUE THREAD

**Issue by benneteapen** [quipucords/quipucords#1976]
## Feature description:
Option to mask hostnames / IP Addresses using MD5 hash or SHA256.
### Is your feature request related to a problem?
Customers are generally hesitant to share the qpc extract back because it gives access to their hostnames, IP addresses etc. The solution we give them is to mask their hostnames using MD5 or SHA256. But, it can be a cumbursome task to mask each hostname one by one using online portals like https://passwordsgenerator.net/md5-hash-generator/

### Describe the solution you'd like
Include an option within QPC to mask columns using MD5 or SHA256 hash. (Dates and system type - virtual or physical) should not be allowed to be masked.

___

## Acceptance Criteria:

- [ ] Output does not reflect any of the customer's confidential information like hostname, VM name, Cluster name or IP Address

___

**Comment by justinkreft** [comment]
Let's define a list of sensitive information based on GBDR requirements. I think Hostname, VM name, and Cluster / IP is sufficient. I don't see other fields that are highly sensitive for European purposes

**Comment by abaiken** [comment]
Closed by https://github.com/quipucords/quipucords/pull/2032
