### ISSUE TITLE
dmi_system_uuid post processor doesn't parse out warnings 

### ISSUE THREAD

**Issue by abaiken** [quipucords/quipucords#1977]
## Bug Description:
If the raw command used to get the `dmi_system_uuid` results in a warning, the post processor saves the entire output as the fact. This is a problem when creating fingerprints because the `dmi_system_uuid` maps to the `bios_uuid` which has a max_length of 36. 

### Expected behavior:
Our post processor should parse out warnings and only save the `dmi_system_uuid` as the fact. 

### Actual behavior:
If the `internal_dmi_system_uuid` command results in a warning before the bios_uuid like the following: 
```
'# SMBIOS implementations newer than version 2.7 are not\r\n# fully supported by this version of dmidecode.\r\nACTUAL_BIOS_UUID'
```
The post processor doesn't parse out the error which will result in an invalid fingerprint: 
```
Fingerprint errors: {'bios_uuid': [ErrorDetail(string='Ensure this field has no more than 36 characters.', code='max_length')]}
```

### Steps to reproduce:
This bug was externally reported -> but once the post processor has been modified a test case can be created with the result from the raw command set to mimic the above warning. 

___

## Acceptance Criteria:

- [ ] Verify that when the dmi_system_uuid raw command results in warnings, the post processor removes them in order to create a valid fingerprint 

___

### Version Information:
CLI version, server version or git commit information.

### Environment information:
Provide detailed information on the *scanning* and *target* systems (if applicable); see example below.

Type            | Operating System | OS Version | Python Version | Virtualization
--------------- | ---------------- | ---------- | -------------- | --------------
Scanning System | RHEL             | 7.4        | 3.6            | Bare Metal
Target System   | RHEL             | 5.9        | 2.4.6          | RHEV

**Comment by benneteapen** [comment]
Came across another customer facing the same issue. Attaching the log file for your reference
[quipucords.log](https://github.com/quipucords/quipucords/files/3925263/quipucords.log)
