### ISSUE TITLE
Investigate, size, design method to detect public cloud deployments via quipucords scans

### ISSUE THREAD

**Issue by kholdaway** [quipucords/quipucords#1978]
Investigate, size, design method to detect public cloud deployments via quipucords scans
QPC shall create an aws_hosted fact that is set to true if a scanned system reports a bios.version that matches the regexp in the following Mojo article:

https://mojo.redhat.com/docs/DOC-1138484

**Comment by abaiken** [comment]
I would estimate this at 3 person weeks, 1 per cloud. 

For `Amazon` & `Google` the code we add will be easy & straightforward. We will check that bios version fact that we are already collecting has a certain string inside using a regex or even just by parsing the result. 

For `Azure`, we will be collecting a new fact (dmi.chassis.asset_tag) and checking that it is equal to the value described in the mojo page. 

The majority of the work is going to be in testing/ testing setup. We will have to set up RHEL vms in each cloud. This will be somewhat of a time sink as we figure out the different setup methods & account charging details.
