### ISSUE TITLE
Spike: Consider hosting the quipucords images through DockerHub

### ISSUE THREAD

**Issue by myersCody** [quipucords/quipucords#2007]
Research how much work it would be to host our images through dockerhub. 

- [ ] Jenkinsfile
- [ ] Backwards Compatibility
- [ ] The ability to tag the most recent commit as latest.

**Comment by kholdaway** [comment]
Issue moved to [quipucords/qpc-tools #11](https://github.com/quipucords/qpc-tools/issues/11) via [**ZenHub**](https://www.zenhub.com/)
