### ISSUE TITLE
Report on if Nodes with VDC subscriptions have enough entitlements to cover the socket count of the node. 

### ISSUE THREAD

**Issue by williamlehman** [quipucords/quipucords#2016]
### Is your feature request related to a problem?
To make sure enough VDC subscriptions are used correctly for the nodes.

### Describe the solution you'd like
Report on if Nodes with VDC subscriptions have enough entitlements to cover the socket count of the node. If there is a discrepancy, output on if it is or is not properly subscribed based on system facts, and IF there is a discrepancy, report on the count of either what is there, what is needed, the diff, or something to that general effect that makes it human readable.

___

## Acceptance Criteria:

If there is a discrepancy, output on if it is or is not properly subscribed based on system facts. 
IF there is a discrepancy, report on the count of either what is there, what is needed, the diff, or something to that general effect that makes it clearly human readable.

___

## Additional context
Notes, this only works on 6.3+ 
https://access.redhat.com/solutions/3385031

**Comment by justinkreft** [comment]
Entitlements are going away, and this issue can't be solved without subscriptions of an account captured by discovery (backlogged issue), closing in favor of this dependency.
