### ISSUE TITLE
[UI] Few minor bugs

### ISSUE THREAD

**Issue by vlours** [quipucords/quipucords#2026]
## Bug Description:
I noticed a couple of minor bugs in the qpc UI (0.9.1):
- No availability to add/edit/remove scans in the **scan** section once there is at least one already setup (available from cli)
The "_scan_" availability which allow to create scans from the **source** section should be renamed to "_create scan_"
- When adding a Source in the UI, the syntax is checked against few rules. Unfortunately, you can create a network IP/rang using values over 255, this will cause the UI to loop 'indefinitely' during the creation process. In opposition, the cli is returning an expected error message.
- If you have multiple sources attached to a scan, **all of the related IPs** are displayed in **all network resources** as if they all belong to each network resource. The values are correct in the edition mode (no issue in cli)
- No ability to Edit credential (available from cli). The "**View**" option include a "**Save**" button which do not save modifications.
- There is no auto-refresh option available in the UI.
- Whatever the size of your browser, the number of previous visible scans are limited to 12, you have to scroll to get more result

Please ignore this Issue if this has already been addressed and fix in  future release.

### Steps to reproduce:
Connect to the UI and test them.

___

### Version Information:
```
[root@5420ccff8ac6 /]# podman images
REPOSITORY                   TAG      IMAGE ID       CREATED         SIZE
localhost/quipucords         0.9.1    a671dca9a206   3 months ago    960 MB
docker.io/library/postgres   9.6.10   89bf0dc0dee0   13 months ago   236 MB
[root@5420ccff8ac6 /]# rpm -q qpc-tools qpc
qpc-tools-0.2.1-1.git.109.596f45c.el7.noarch
qpc-0.9.2-1.git.79.9b2ce8c.el7.noarch
```

### Environment information:
Provide detailed information on the *scanning* and *target* systems (if applicable); see example below.

Type            | Operating System | OS Version | Python Version | Virtualization
--------------- | ---------------- | ---------- | -------------- | --------------
Scanning System | Centos             | 7.7        |7.2.5 + 3.6            | container

**Comment by kholdaway** [comment]
Move issue to the GitHub repository.

**Comment by kholdaway** [comment]
Issue moved to [quipucords/quipucords-ui #73](https://github.com/quipucords/quipucords-ui/issues/73) via [**ZenHub**](https://www.zenhub.com/)
