### ISSUE TITLE
RFE: Enable SSH2 authentication with QPC tool

### ISSUE THREAD

**Issue by justinkreft** [quipucords/quipucords#2036]
Our public sector customers have locked down STIG machines which block basic SSH access. To enable them to use this tool, we need to use SSH2. As is, QPC will be unable to be used in these environments.

**Comment by justinkreft** [comment]
Update from ongoing engagement with customer. I will continue to collect information on this feature request.

The DISA STIG does not mandate disabling SSH.  All it does is mandate that privileged users (root) is not allowed to connect remotely.  Users must connect using their user account and escalate privileges. (This is what QPC does normally)

I have never seen the use of ssh2 in DoD and it does not seem to be included in the RHEL 8 repos (my laptop is running RHEL 8).

You could try to install the same package that they are using for ssh2 on the QPC box and alias ssh2 to ssh.  That way if the QPC script tries to run SSH, it will actually use SSH2 (assuming all of the command options are the same).

If not, ask them to turn SSH back on so that they test can be run.

**Comment by gtanzillo** [comment]
This is tracked on 1.x eng roadmap
