### ISSUE TITLE
RFE - Always create columns (even if null) for all data collected by QPC

### ISSUE THREAD

**Issue by justinkreft** [quipucords/quipucords#2037]
CSV outputs should maintain a consisent format (meaning that even if a customer has not run an extended scan, all columns remain in the report). This will take the guesswork out of interpreting the data and serve as a red flag for when customer has not appropriately run the tool.

I think this question is open for debate. @TomRico and I feel that having all columns present will help us in our role, but open to community feedback.

**Comment by kholdaway** [comment]
@justinkreft The deployments report does this.  Is this for the details report?

**Comment by justinkreft** [comment]
@kholdaway 

The usecase that is the most problematic is the details.csv

Specifically, the main problem is that if the customer sends us like 10 network reports and we compile them to a single report, the columns don't line up.  

There may be a  good reason not to do this (column clutter), but since the QPC CLI merges reports/records from DB (right?) not files themselves, so my understanding there isn't a way to quickly merge several details.csv files into a single report if the customer themselves does not do it 

(additionally, it isn't infrequent that a customer shares scans from different dates after we request more information). The column mapping issue because annoying in that situation
vCenter and Satellite are not as concerning as the columns are much less columns there.

**Comment by williamlehman** [comment]
Unfortunately, I am seeing a problem with deployments data too. 
![Screenshot from 2020-09-02 11-15-37](https://user-images.githubusercontent.com/33132438/92002340-c3968200-ed0d-11ea-9122-54cfd9602b46.png)

**Comment by kholdaway** [comment]
@williamlehman I am unable to tell what the problem is from the screenshot. What column is missing there?

**Comment by williamlehman** [comment]
@kholdaway Good point, it would better if I stated that some of the data for each row does not align correctly to the columns. Does that help?

**Comment by kholdaway** [comment]
@williamlehman Two things.  This would be a different issue (open a bug for this).  This current ticket is a feature request.  2nd, when you do that could you also provide a details report in JSON format (could be offline).  That would allow me to try and recreate locally with the same data.

**Comment by gtanzillo** [comment]
Will be delivered in 1.0.1 release
