### ISSUE TITLE
'os_version' is a number instead of a string in sat6 scan reports

### ISSUE THREAD

**Issue by himmAllRight** [quipucords/quipucords#2039]
"os_version" is a number instead of a string in sat6 scan reports

## Bug Description:

The `os_version` is a number (float) instead of a string in the deployments report for `sat6` scans.

This was found from a failing automated test. It should be noted it seems that this bug *only* occurs in the `sat6` version of the test. The `Fuse` and `VcenterOnly` ones pass.

Snippet from deployments report with issue:

```json
"name": "hostname"
 "os_name": "RedHat",
 "os_release": "RedHat 7.7",
 "os_version": 7.7,
 "products": [
```

### Expected behavior:

The `os_version` value should be be a string in deployments reports.

### Actual behavior:

The `os_version` value is a number in the deployments report during the `sat6` test scan.

### Steps to reproduce:

-   Run a sat6 scan
    
-   Request a json deployments report
    
-   Check if the `os_version` is a number, or a string (it should have quotation marks)
    

---

## Acceptance Criteria:

-   [ ]  All values of `os_version` are a string in each scan type (including `sat6`)

---

### Version Information:

Node OS: rhel8-os

QPC-Tools: 0.2.4

Quipucords Version: 0.9.2

QPC: 0.9.3

Podman: podman-1.4.2-6

### Environment information:

The Jenkisn testing pipeline, using a `rhel8-os` node. Also, reproduced inside a local RHEL8 VM, scanning the test machines.

**Comment by kholdaway** [comment]
@himmAllRight Hmmm, I think a float is correct but what was the value produced by Sat 6?
