### ISSUE TITLE
Bad create/update request for network profile gets 500 (internal server error) 

### ISSUE THREAD

**Issue by kdelee** [quipucords/quipucords#204]
## Specify type:
- Bug

### Bug severity (if applicable):
- Medium
___

## Description:
If a user attempts to update a profile to use a credential that does not yet exist, they get a 500 error which tells them something is wrong with the server (happens with DEBUG = True and DEBUG = False), and in the logs it shows a traceback.

Instead, the user should ideally get a  `406 (Not Acceptable)`. According to [RFC 7231](https://tools.ietf.org/html/rfc7231#section-6.5.6) they should get back a list of acceptable credentials (i.e. ones that exist).
___

### Expected behavior:
If i attempt to update a profile with an credential id that does not exist, I should be told I did something wrong.

### Actual behavior:
If I do aforementioned bad thing, the server tells me it is broken.

### Steps to reproduce:
1) Create any number of credentials you like. 
2) Create a profile with some of these valid credentials. 
3) Attempt to update profile with invalid credentials (either add them to list or replace list with invalid)

### Environment information:

Type            | Operating System | OS Version | Python Version | Virtualization
--------------- | ---------------- | ---------- | -------------- | --------------
Server System | Fedora            | 25        | 3.6            | Bare Metal
Client System   | same

**Comment by chambridge** [comment]
I agree that a 500 is wrong. I think a 404 where the message clarifies no id exist for the host credential makes sense. Open to discussion though.

**Comment by kdelee** [comment]
I guess if the 404 doesn't come with more info, I would think that meant that the profile I'm trying to update does not exist.

Also, this appears to happen with host credentials too when you try and update them with bad information
