### ISSUE TITLE
CSV formatting does not open to a clean document

### ISSUE THREAD

**Issue by williamlehman** [quipucords/quipucords#2053]
## Bug Description:
When opening the csv outputs of the deployments and details files, facts are aligned to the wrong columns.

### Expected behavior:
When opening csv's, not modifications should be necessary to view a clean output. No data points should be in the wrong columns

### Actual behavior:
Currently, when opening the csv files, the facts are not aligned to the correct columns and cause a mess of data that makes it necessary for someone to heavily modify the files to make it human-readable. 

### Steps to reproduce:
open csvs

## Acceptance Criteria:

- [ ] Verify that users can simply open the csvs in a human-readable format that does not require modification to parse

___

### Version Information:
All csv files

### Environment information:
Will send data directly.

**Comment by williamlehman** [comment]
@kholdaway Sending you an email now with output for your review.

**Comment by kholdaway** [comment]
This turned out to be a bug in Libre Office.  It seemed to ignore the setting to not use `;` as a delimiter.
