### ISSUE TITLE
[RFE] Include Latest package name and version when checking RH package numbers build date and install dates

### ISSUE THREAD

**Issue by williamlehman** [quipucords/quipucords#2055]
### Is your feature request related to a problem?
Yes. Currently we get valuable information like redhat_packages_gpg_last_built, redhat_packages_gpg_last_installed, redhat_packages_gpg_num_installed_packages, and redhat_packages_gpg_num_rh_packages. However, we don't know what specific package we are talking about. That additional detail would be helpful.

### Describe the solution you'd like
Either add package name and version into the output per column for redhat_packages_gpg_last_built and redhat_packages_gpg_last_installed; or create a new column for this information.
___

## Acceptance Criteria:

- [ ] Verify that users can see the package name and version.

___

## Additional context
Specifics help.

**Comment by kholdaway** [comment]
Originally, the ansible script pulled this information back to the server and parsed it.  It was a ton of data and caused performance issues.  At the time, Mark was only concerned with if they were there. While this could be done (technically), it definitely could cause problems too.

**Comment by williamlehman** [comment]
@kholdaway From what I could tell the data is already in the command. So I am a little confused on where the load would be. 

Could we do something like change 
`rpm -qa --qf "%{INSTALLTIME} %{DSAHEADER:pgpsig}|%{RSAHEADER:pgpsig}|%{SIGGPG:pgpsig}|%{SIGPGP:pgpsig} |%{NAME}-%{VERSION} Installed:%{INSTALLTIME:date}\n" | grep 'Key ID 199e2f91fd431d51\|Key ID 5326810137017186\|Key ID 45689c882fa658e0\|Key ID 219180cddb42a60e\|Key ID 7514f77d8366b0d9\|Key ID 45689c882fa658e0' | sort -nr | head -n 1 | cut -d"|" -f2`
to 
`rpm -qa --qf "%{INSTALLTIME} %{DSAHEADER:pgpsig}|%{RSAHEADER:pgpsig}|%{SIGGPG:pgpsig}|%{SIGPGP:pgpsig} |%{NAME}-%{VERSION} Installed:%{INSTALLTIME:date}\n" | grep 'Key ID 199e2f91fd431d51\|Key ID 5326810137017186\|Key ID 45689c882fa658e0\|Key ID 219180cddb42a60e\|Key ID 7514f77d8366b0d9\|Key ID 45689c882fa658e0' | sort -nr | head -n 1`

**Comment by kholdaway** [comment]
Correct, but we don't send it over the network (back to qpc server). It is processed on the machine that is scanned.

**Comment by williamlehman** [comment]
Technically, wouldn't this be lighter because it's not having to 'cut'? I am asking because I genuinely have no idea.

**Comment by kholdaway** [comment]
That's not what we found.  It was sending tons and tons of data over the network.

**Comment by williamlehman** [comment]
Okay. Either way, we would like this feature to be included. However best you think it could be done.

**Comment by justinkreft** [comment]
This is addressed by the data dictionary in terms of confusion. Currently won't fix.
