### ISSUE TITLE
Better error messages for being unable to connect to satellite and vcenter

### ISSUE THREAD

**Issue by williamlehman** [quipucords/quipucords#2073]
### Is your feature request related to a problem?
Yes, when unable to connect to a satellite or vcenter, there is no clear error message as to why it fails. Can we use sat admin creds? Root creds? Unable to ping host? date and time not in sync? etc.

### Describe the solution you'd like
Clear errors in whichever logs are most appropriate
___

## Acceptance Criteria:

Provide logs for troubleshooting failed connections to satellite and vcenter

___

**Comment by gtanzillo** [comment]
This is tracked on 1.x eng roadmap
