### ISSUE TITLE
Add button for deleting failed scans

### ISSUE THREAD

**Issue by williamlehman** [quipucords/quipucords#2075]
## Feature description:

Add button for deleting failed scans

### Is your feature request related to a problem?

When lots of failed tests occur, there is a build up of failed scans. 

### Describe the solution you'd like

Add the ability to delete scans

___

## Acceptance Criteria:

- Add functionality to delete [failed] scans

___

**Comment by justinkreft** [comment]
This has come up quite a few times for me. It is possible to delete from the CLI, but that can be cumberson for the end user if they are expecting to use the GUI

**Comment by gtanzillo** [comment]
This is tracked on 1.x eng roadmap
