### ISSUE TITLE
Change how we pull install dates to accomodate clones

### ISSUE THREAD

**Issue by williamlehman** [quipucords/quipucords#2081]
## Feature description:

Change how we pull install dates to accomodate clones

### Is your feature request related to a problem?
As is, pulling anaconda.log can present false install dates in cloned systems. 

### Describe the solution you'd like
Instead of checking the anaconda.log (or in addition to the anaconda.log) please check system install date with the following command:

ls -lact --full-time /etc |awk 'END {print $6, $7}'

___

## Acceptance Criteria:

Tool will use the above command to check install date on a system. 

___

**Comment by justinkreft** [comment]
This issue has been partly addressed through the addition of uptime fact in 1.0. Closing as this was determined to be the best way to solve the problem
