### ISSUE TITLE
Add a feature to increase the timeout when executing scans

### ISSUE THREAD

**Issue by benneteapen** [quipucords/quipucords#2082]
### Is your feature request related to a problem?
When scanning a /16 or /8 subnet, the task fails with this error :
`...Additional status information: Unexpected ansible status timeout. Failing scan because there were no successful system connections. Ansible error: A timeout was reached while executing the Ansible playbook.`

### Describe the solution you'd like
There should be an option to increase the timeout via CLI/GUI
___

## Acceptance Criteria:

- [ ] User should have an option/command to increase the timeout value
- [ ] The user should be able to see the number of IPs to which connectivity was attempted or scanned before failing.

**Comment by gtanzillo** [comment]
This issue is on the 1.x roadmap
