### ISSUE TITLE
RFE: Pull and restore database of sources, creds, scans

### ISSUE THREAD

**Issue by justinkreft** [quipucords/quipucords#2084]
## Feature description:
Pull sources, creds, scans, etc from an active container database that is about to be decommisioned, and be able to restore that information to a new system at a later date.

### Is your feature request related to a problem?
End users often only use QPC/Discovery occasionally, and tear down the system hosting QPC/Discovery after use. In these cases (and in particular cases when end-user has many different creds), 

### Describe the solution you'd like
Phase 1) validate if a simple mongodump and mongorestore will work (document for users)
Phase 2) add commandline functionality 
Phase 3) add export/inport to GUI

___

## Acceptance Criteria:
End user can export a complete dump of the container database
End user can import a dump to a new container database
No data loss
Scanning is functional with imported data

**Comment by gtanzillo** [comment]
Planned for 1.0.1 release
