### ISSUE TITLE
RFE: Develop integration with customer portal for subscription data

### ISSUE THREAD

**Issue by williamlehman** [quipucords/quipucords#2094]
## Feature description:

RFE: Develop integration with customer portal for subscription data

### Is your feature request related to a problem?
Please describe.  A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

### Describe the solution you'd like

Integrate with the Red Hat Customer Portal to pull subscription information for one or more accounts.
___

## Acceptance Criteria:

- [ ] Verify that users can X Y Z
- [ ] Verify that an expected error is encountered when a user does A B C

- Subscription information pulls from Customer Portal from one or more accounts. 

___

**Comment by justinkreft** [comment]
Reopening this one. We should be able to connect to the Subswatch API the same way that crhc-cli (https://github.com/C-RH-C/crhc-cli) which would potentially save a step for users

**Comment by gtanzillo** [comment]
Planned for 1.0.1 release
