### ISSUE TITLE
RFE: Develop integration with Red Hat Subscription Management for systems registered to the Customer Portal

### ISSUE THREAD

**Issue by williamlehman** [quipucords/quipucords#2095]
## Feature description:

RFE: Develop integration with Red Hat Subscription Management for systems registered to the Customer Portal

### Is your feature request related to a problem?
Please describe.  A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

Right now, data is pulled from three sources. Let's increase it to 4, including the Customer Portal, for customers that want to accurately represent their deployments from all available data sources. 

### Describe the solution you'd like

Integrate with Customer Portal/Subscription Mangement to pull deployment/details for systems registered directly to Red Hat.

___

## Acceptance Criteria:

- [ ] Verify that users can X Y Z
- [ ] Verify that an expected error is encountered when a user does A B C

- Tool works with Red Hat Subscription Management
___

**Comment by justinkreft** [comment]
This won't quite work the way we envisioned it. Enabling a script that a customer could use to pull that information may work as an additional source

Instead, BIZ 404, we need to ensure that subscription watch can injest Discovery output through.

There is a current tool that is unofficial where we can also request an export of c-rh-c (cloud.redhat.com) using an existing. Subswatch also has a feature request for a proper "export tool" that is in the works.

Discovery's primary goal is to get a picture of the unknown, but it was designed as a data gathering tool, with little to no "business logic" or analysis

**Comment by gtanzillo** [comment]
This is tracked on 1.x eng roadmap
