### ISSUE TITLE
RFE: Gather Hyperthreading information on VMware Host

### ISSUE THREAD

**Issue by williamlehman** [quipucords/quipucords#2097]
## Feature description:

RFE: Gather Hyperthreading information on VMware Host

### Is your feature request related to a problem?
Please describe.  A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

Hyperthreading information is required for JBoss core counting.

### Describe the solution you'd like

From the Vcenter, gather information on if each host has hyperthreading enabled. 
___

## Acceptance Criteria:

- [ ] Verify that users can X Y Z
- [ ] Verify that an expected error is encountered when a user does A B C

- Add hyperthreading field to vcenter output. 

___

**Comment by justinkreft** [comment]
Hyperthreading from vCenter is not a consistent truth (often it is masked) this is similar to the OpenShift hyperthreading issue. Not sure that we should collect additional facts that we are not certain about.

**Comment by justinkreft** [comment]
Closing. This data fact would not be consistent.
