### ISSUE TITLE
[RFE] Add explanation of each field to a text file for download with reports or accessible on discovery server. 

### ISSUE THREAD

**Issue by williamlehman** [quipucords/quipucords#2103]
## Feature description:

Add explanation of each field to a text file for download with reports or accessible on discovery server. 

### Is your feature request related to a problem?
Understanding the output is crucial for the value proposition of the tool. Adding a non-code level explanation will help those that aren't experts.

### Describe the solution you'd like
Add explanation of each field to a text file for download with reports or accessible on discovery server. 
___

## Acceptance Criteria:

- [ ] Add a file to the downloaded files that explains each field breifly
OR
- [ ] Add an explanation of each field to discovery UI

**Comment by gtanzillo** [comment]
This will be handled in documentation

**Comment by justinkreft** [comment]
This will be addressed through documentation
