### ISSUE TITLE
[RFE] Add location of 'discovery-server.log to UI for customers that want to see why they are receiving failures. 

### ISSUE THREAD

**Issue by williamlehman** [quipucords/quipucords#2104]
## Feature description:

[RFE] Add location of 'discovery-server.log to UI for customers that want to see why they are receiving failures. 

### Is your feature request related to a problem?

Many customers encounter errors and are not sure where the logs are to troubleshoot their issues. 

### Describe the solution you'd like

Indicating in the UI, potentially when failures are seen, where the log file is will help customers troubleshoot their own issues. 

___

## Acceptance Criteria:

- [ ] Add something to the effect of "To review the cause for failures in your scans, please refer to '/root/discovery/server/volumes/log/discovery-server.log'"

___

**Comment by gtanzillo** [comment]
Current release 1.0
