### ISSUE TITLE
[RFE] Improve Failure reporting in UI to be more specific 

### ISSUE THREAD

**Issue by williamlehman** [quipucords/quipucords#2106]
## Feature description:

[RFE] Improve Failure reporting in UI to be more specific 

### Is your feature request related to a problem?

When customers do a scan and they get failures and often don't know why.

### Describe the solution you'd like
Instead of just showing that X number of scans failed, add more verbosity to explain why it failed. ie. Couldn't log in, no route to host, etc.

___

## Acceptance Criteria:

- [ ] Create list of potential failure reasons
- [ ] Add these fields to UI
- [ ] Indicate in the UI how many scans failed for the particular reasons 

___

**Comment by justinkreft** [comment]
closed. duplicate
