### ISSUE TITLE
Collect a common fact between sources to aid in de-duplicaiton

### ISSUE THREAD

**Issue by mdvickst** [quipucords/quipucords#257]
# Opening a new issue
___

## Specify type:
- Enhancement
___

## Description:
We need a common fact between Ansible (Rho), vCenter and Satellite in order to determine the number of unique systems. Some ideas that have been thrown around are:
- UUID (must be BIOS UUID for Ansible to capture it)
- MAC address of interfaces (would only help with duplicates between sources not with duplicates within data source e.g. Rho could scan a single system multiple times if it has multiple interfaces and the MAC addresses would all be unique). 
- Hostname - very weak and appears differently in different data sources. would likely need to be a secondary or tertiary check
- IP address - systems can have multiple IPs and could potentially have the same IP as another system (NAT environments)
___

**Comment by chambridge** [comment]
We capture this data across all three data source. We'll open another issue if we find more we want to collect.
