### ISSUE TITLE
I want to be able to query data from a VCenter source.

### ISSUE THREAD

**Issue by chambridge** [quipucords/quipucords#265]
## Specify type:
- Enhancement

## Description:
Add support for a VCenter connection scan task. A VCenter connection scan scan tasks should attempt authentication of VCenter and perform a query to collect the number of the systems managed.

Add support for a VCenter inspection scan task. A VCenter inspection scan task should obtain facts about the managed systems. 

Facts: 
- cluster name
- number of vmware hosts in cluster
- virtual sockets
- UUID (must be BIOS UUID for Ansible to capture it)
- MAC address of interfaces (would only help with duplicates between sources not with duplicates within data source e.g. Rho could scan a single system multiple times if it has multiple interfaces and the MAC addresses would all be unique). 
- Hostname - very weak and appears differently in different data sources. would likely need to be a secondary or tertiary check
- IP address - systems can have multiple IPs and could potentially have the same IP as another system (NAT environments)

___
Work items:

- [x] https://github.com/quipucords/quipucords/issues/266
- [x] https://github.com/quipucords/quipucords/issues/267

**Comment by kdelee** [comment]
@chambridge 
Will there be any ability to request certain facts, or is this going to be an all or nothing fact group?

**Comment by kdelee** [comment]
I have another clarification:

Must a host manager be defined in its own source with the type indicated (i.e. "vcenter") and then will I only be able to run a scan for the vcenter fact group on that machine?

I guess I'm asking if quipucords will enforce that the vCenter facts are the only thing you can scan for on a vCenter host manager source, and that you are not allowed to try and scan for vCenter host manager facts with a network source (i.e. ssh connection not vCenter api).

**Comment by chambridge** [comment]
@kdelee This user story is focused on just creating the pipeline of data (i.e. querying the VCenter APIs). A later story will focus on the fact group aspect.

A source type defines the mechanism used to inspect facts.

**Comment by kdelee** [comment]
Ok I'll keep my eyes peeled. I am going to go off of the list of facts mentioned here and in #267

**Comment by chambridge** [comment]
work items closed.
