### ISSUE TITLE
Inconsistent error response for adding duplicate sources

### ISSUE THREAD

**Issue by cdcabrera** [quipucords/quipucords#298]
# Opening a new issue
___

## Specify type:
- Bug

### Bug severity (if applicable):
- Low
___

## Description:
When ```POSTing```/adding to the source list under ```/api/v1/sources/``` with a ```name``` that already exists the response is returned as an array/list of strings. By itself this appears adequate, until additional submitted fields return a 400 status and create a conflict in the response format.
___

### Expected behavior:
Responses for all 400 status should be consistent. Since existing/duplicate source listings appear to be centered around the ```name```  a possible response could be:
```js
{
  "name":[
    "Source with name=test0 already exists"
  ]
}
```

### Actual behavior:
Duplicate source listings return a 400 status array response, i.e.
```js
[ "Source with name=test0 already exists" ]
```

If an ```duplicate source listing 400 status``` happens at the same time as an ```empty value 400 status``` it looks like the empty value message is given priority, i.e.
```js
{
  "address": [
    "This field may not be blank."
  ]
}
```

### Steps to reproduce:
1. Make sure you've setup credentials
2. Next, through the API interface add a source under  ```/api/v1/sources/```, like
```js
{
  "name": "SAME_NAME",
  "source_type": "network",
  "address": null,
  "ssh_port": 22,
  "hosts": ["00.00.000.000"],
  "credentials": [1]
}
```
3. Next, add the same source making sure that the ```name``` param is the same as the first. You should see a response, like
```js
  [ "Source with name=SAME_NAME already exists" ]
```
4. Next, you'll submit ALMOST the same source again, making sure the ```name``` is the same as the first 2 times. But this time add an empty value for something like ```address```, like
```js
{
  "name": "SAME_NAME",
  "source_type": "network",
  "address": "",
  "ssh_port": 22,
  "hosts": ["00.00.000.000"],
  "credentials": [1]
}
```
The response should appear as
```js
{
  "address": [
    "This field may not be blank."
  ]
}
```

**Comment by chambridge** [comment]
https://github.com/quipucords/quipucords/pull/332
