### ISSUE TITLE
Merge rho fingerprinting into Sonar

### ISSUE THREAD

**Issue by noahl** [quipucords/quipucords#307]
EDIT: here is the updated to-do list. This has to be in the first comment so that GitHub will make it the overall issue status.

- [x] brms
- [x] check_dependencies (mostly migrated, I think just locate, systemctl and chkconfg are left)
- [x] cleanup
- [x] dmi (role has been moved to Sonar, but almost all of it is commented right now)
- [x] etc_release (already in Sonar, but version in Rho has much more detailed when clauses)
- [x] file_contents
- [x] fuse
- [x] jboss_eap
- [x] jboss_eap_scan
- [x] jboss_fuse_on_karaf
- [x] redhat_packages
- [x] redhat_release
- [x] subman
- [x] uname
- [x] virt (same as etc_release. Already in sonar, but need to understand why when clauses are more detailed in Rho)

What this used to say:

This is intended as an overall tracking issue and a way to discuss the plan as a whole. I will file issues for the individual points, but I'm planning to wait until after the plan stabilizes to avoid flooding everyone's inbox.

Outline of moving rho fingerprints to Sonar:
-  Switch rho's `utilities.log` to standard Python style to match Sonar
-  Make sure non-middleware facts are the same in Rho and Sonar (I'm expecting this to be a small task)
-  Make Sonar fingerprinting engine that knows how to route fact information to pluggable processors
-  Import EAP (roles and postprocesing) into Sonar
-  Import Fuse (roles and postprocessing)
-  Import BRMS (roles and postprocessing)

Deliberately omitted from this plan: any forward-looking refactoring to support Doppler. I told the team that I want to support their use-case, but I think we should wait until they have more of an idea what they want before we spend cycles doing things they might not need.

**Comment by chambridge** [comment]
Unfortunately I don't think the non-middleware facts to Rho is as small as you would hope. We have only moved a minimal set from Rho to Sonar and the set in Sonar is stale so updates in Rho need to be brought over.

I'm not clear on what your third item is I think that is related to terminology. I think essentially you are talking about having a handler in the ResultCallback that understands how to route each fact to a "processor". Dealing with raw facts? If that is not what you are talking about please elaborate.

I think porting all the roles & post processing makes sense and should be the first priority. I think the summary facts would be left out of the "raw facts" as that is work we can move into the "fingerprinter" code.

I think phase one is collect all the "raw facts". Then we can worry about updating the fact endpoint and fingerprinter code to create the appropriate fingerprints. Currently the fact endpoint doesn't care if you send it data its not looking for, so you can incrementally grow the raw facts until everything is done and then we can update the engine flow.

**Comment by noahl** [comment]
@chambridge thanks! I hadn't really looked at the non-JBoss facts.

Clarifying question - are you considering the "raw facts" to be the information coming directly from Ansible, or what is reported in Rho after postprocessing? I was imagining that "raw facts" are literally Ansible results with no processing, and the fingerprinter would do everything that Rho considers "postprocessing". I'm not sure from your message if that is your view too.

**Comment by chambridge** [comment]
“raw facts” would be what we have parsed/extracted from Ansible in a meaningful way. For non-middleware facts this is usually the direct fact value except for the rpm data which needs processing. But the resulting rpm facts I would still refer to as a raw fact. 

A fact I wouldn’t consider raw would be the middleware summary fact where we have inferred something based on the raw data we collected from the system.

**Comment by noahl** [comment]
@chambridge thank you! I think I'm set to merge stuff.

**Comment by noahl** [comment]
Given what Chris said, I've been going through the roles already in Sonar and I made a more detailed list of what is still to be merged:

- [ ] brms
- [ ] check_dependencies (mostly migrated, I think just locate, systemctl and chkconfg are left)
- [ ] cleanup
- [ ] dmi (role has been moved to Sonar, but almost all of it is commented right now)
- [ ] etc_release (already in Sonar, but version in Rho has much more detailed when clauses)
- [ ] file_contents
- [ ] fuse
- [ ] jboss_eap
- [ ] jboss_eap_scan
- [ ] jboss_eap_scan
- [ ] jboss_fuse_on_karaf
- [ ] redhat_packages
- [ ] redhat_release
- [ ] subman
- [ ] uname
- [ ] virt (same as etc_release. Already in sonar, but need to understand why when clauses are more detailed in Rho)

etc_release and virt might or might not need more migrating. I don't know if we want to make the when clauses match or dynamically choose to include or exclude them from the playbook instead.

**Comment by noahl** [comment]
I'll replace the list in my first comment with the new list, since it is more accurate. It looks like GitHub will consider the status of this issue to be whatever the checklist in the initial comment is.

**Comment by noahl** [comment]
All subsidiary issues are done, so this is closed!
