### ISSUE TITLE
Compute top level ScanJob metrics (e.g. systems_scanned)

### ISSUE THREAD

**Issue by kholdaway** [quipucords/quipucords#317]
# Opening a new issue
___

## Specify type:
- Enhancement

### Bug severity (if applicable):
- High

___

## Description:
Currently metrics are only counted at the ScanTask level.  The same metrics should be calculated at the scan job level.

**Comment by chambridge** [comment]
Calculating values for `systems_count, systems_scanned, systems_failed` based on the Scan Job's scan_type.
