### ISSUE TITLE
Update facts endpoint to support multiple network sources (tolerate vcenter but ignore)

### ISSUE THREAD

**Issue by kholdaway** [quipucords/quipucords#329]
# Opening a new issue
___

## Specify type:
- Enhancement

### Bug severity (if applicable):
- High

___

## Description:
Update facts endpoint to support multiple network sources (tolerate vcenter but ignore)

/facts/:
```
{
    "sources": [
        {
            "source":"id",
            "source_type":"network",
            "facts":[
                
            ]
        }
    ]
}
```

**Comment by chambridge** [comment]
We should allow external data from here, but for now we should pass data from our scans programmatically, rather than by REST to by pass the service account authentication steps for 1.0.

**Comment by kholdaway** [comment]
@chambridge I am breaking the change of how we pass facts (REST -> programmatic) to keep this PR smaller.  See https://github.com/quipucords/quipucords/issues/348
