### ISSUE TITLE
Can't edit a single field of a credential using qpc cli

### ISSUE THREAD

**Issue by elyezer** [quipucords/quipucords#330]
## Specify type:
- Bug

### Bug severity (if applicable):
- Medium
___

## Description:
Can't update credential username without providing other options. One should be able to update only one field and other fields should continue with the same values.
___

### Expected behavior:
Be able to edit a single field of a credential.

### Actual behavior:
Can't edit a single field of a credential.

### Steps to reproduce:
```console
$ qpc cred add --name 1 --type network --username root --password
Provide connection password.
Password: 
Credential "1" was added

$ qpc cred edit --name 1 --username newuser
Error: A host credential must have either a password or an ssh_keyfile.
...
```

### Environment information:
Not needed to manage credentials

**Comment by abaiken** [comment]
Closed by branch Iss371.
