### ISSUE TITLE
Error when building Sonar container from non-clean source tree

### ISSUE THREAD

**Issue by noahl** [quipucords/quipucords#341]
When building the Sonar Docker container from a quipucords checkout that I have previously run Sonar from, I get `django.db.utils.OperationalError: table "api_credential" already exists`. This happens because the Dockerfile copies the Sonar source directory into the container with `COPY . /tmp/`. Since my old sqlite database was at `quipucords/db.sqlite3` inside the source tree, it got copied into the container along with everything else. Removing the database from the source tree fixes the problem. A better solution would be to only copy source files from a clean directory tree, or have git only copy checked-in files, or something like that.

Marking this low-priority because it should only affect development, and there's a workaround.

**Comment by chambrid** [comment]
Should be able to add the db to the dockerignore file.

**Comment by noahl** [comment]
I'll send a PR, just a minute while I write it :)
