### ISSUE TITLE
Merge fuse fingerprints from rho to sonar

### ISSUE THREAD

**Issue by noahl** [quipucords/quipucords#355]
Part of #307 .

**Comment by ilyavw** [comment]
As per @chambridge we are not moving tasks with find commands over yet. Since this role is built entirely out of tasks with find commands it can not be moved currently. Moving back to backlog.

**Comment by noahl** [comment]
This is confusing because the fuse on EAP tasks in Rho are not in the `fuse` role, they are in the `jboss_eap` role. I ported them over when I ported the `jboss_eap` role, but I don't know if I got all of the postprocessing for them.

**Comment by ilyavw** [comment]
I'm not sure I understand your comment. If there is work that _can_ be done right now this issue needs a lot more detail. As it stands now, if I open the `fuse` role in rho all I see are three tasks that all use `find`.  That is as much detail as I can gather from this issue title and description.

**Comment by noahl** [comment]
I agree this is confusing. In Rho, the data that we use to decide whether a system has Fuse is partly in the `fuse` role and partly in the `jboss_eap` role. (This is my fault. I don't remember why I put it there. Maybe because it has to run after the eap stuff.)

Even though we're not porting the `fuse` role to Sonar right now (since it contains only find commands), we still have fuse data collection in Sonar. It's in the `jboss_eap` role, like it was in Rho. And the data that is collection should have postprocessing done (as it was in Rho), but the postprocessing has not yet moved from Rho to Sonar.

So that's the work that is left to do right now.
