### ISSUE TITLE
Unable to add auth due to required cred_type 

### ISSUE THREAD

**Issue by mdvickst** [quipucords/quipucords#390]
# Opening a new issue
___

## Specify type:
- Bug

### Bug severity (if applicable):
- Medium

___

## Description:
When trying to add an auth it gives an error saying it requires cred_type. cred_type is not a valid option for an auth. 
___

### Expected behavior:
Describe the expected behavior for the program.

### Actual behavior:
[root@mvickstr-rhel7 quipucords-master]# qpc auth add --name=first_cred --username=root --password
Provide connection password.
Password: 
cred_type: cred_type is required for credential creation
usage: qpc auth add [-h] --name NAME --username USERNAME
                    (--password | --sshkeyfile FILENAME) [--sshpassphrase]
                    [--sudo-password]

optional arguments:
  -h, --help            show this help message and exit
  --name NAME           auth credential name
  --username USERNAME   user name for authenticating against target system
  --password            password for authenticating against target system
  --sshkeyfile FILENAME
                        file containing SSH key
  --sshpassphrase       ssh passphrase for authenticating against target
                        system
  --sudo-password       password for running sudo
[root@mvickstr-rhel7 quipucords-master]# qpc auth add --name=first_cred --username=root --password --cred_type=network
usage: qpc [-h] [--version] [-v] {server,auth,profile,scan} ...
qpc: error: unrecognized arguments: --cred_type=network

### Steps to reproduce:
List clear steps to reproduce the bug.

### Environment information:
Build 699587

**Comment by chambridge** [comment]
Looks like a COPR setup issue where the repo isn't getting updated with the latest. I believe I found the difference from this and rho.

**Comment by chambridge** [comment]
This was a COPR setup issue. It has been fixed with the following PR to add support for `tito_test`.
https://github.com/quipucords/quipucords/pull/398
