### ISSUE TITLE
Enhance "become support" in network inspection scans

### ISSUE THREAD

**Issue by chambridge** [quipucords/quipucords#414]
## Specify type:
- Enhancement

## Description:
Currently, the network credentials support sudo password. We want to extend and enhance the capabilities of our network scans to support the range of capabilities in Ansible.

Update the Credentials model to support:
- become_method (default is sudo; like ansible --  valid choices: [ sudo | su | pbrun | pfexec | doas | dzdo | ksu | runas ])
- become_user (default is root; like ansible)
- become_password  (null if not set; repaces sudo_password, should still be encrypted)

#### Post API
- Swagger should be update to show new object structure

#### PUT/PATCH API
- Swagger should be update to show new object structure

### Add CLI
- Add cli should support these new options
- Man page updates needed

### Edit CLI
- Edit cli should support these new options as a patch
- Man page updates needed

#### Inspection
The variables for the Ansible task runner should utilize these updated variables.

_____
Work items:

- [x] https://github.com/quipucords/quipucords/issues/415
- [x] https://github.com/quipucords/quipucords/issues/416
- [x] https://github.com/quipucords/quipucords/issues/417

**Comment by abaiken** [comment]
Closed by https://github.com/quipucords/quipucords/pull/453

**Comment by chambridge** [comment]
🥇 Nice Job!
