### ISSUE TITLE
API support for enhanced become support in network credentials

### ISSUE THREAD

**Issue by chambridge** [quipucords/quipucords#415]
## Specify type:
- Enhancement

## Description:
Currently, the network credentials support sudo password. We want to extend and enhance the capabilities of our network scans to support the range of capabilities in Ansible.

Update the Credentials model to support:
- become_method (default is sudo; like ansible --  valid choices: [ sudo | su | pbrun | pfexec | doas | dzdo | ksu | runas ])
- become_user (default is root; like ansible)
- become_password  (null if not set; repaces sudo_password, should still be encrypted)

#### Post API
- Swagger should be update to show new object structure

#### PUT/PATCH API
- Swagger should be update to show new object structure

**Comment by abaiken** [comment]
Closed by https://github.com/quipucords/quipucords/pull/453
