### ISSUE TITLE
CLI support for enhanced become support in network credentials 

### ISSUE THREAD

**Issue by chambridge** [quipucords/quipucords#416]
## Specify type:
- Enhancement

## Description:
Currently, the network credentials support sudo password. We want to extend and enhance the capabilities of our network scans to support the range of capabilities in Ansible.

Update the Credentials model to support:
- become_method (default is sudo; like ansible --  valid choices: [ sudo | su | pbrun | pfexec | doas | dzdo | ksu | runas ])
- become_user (default is root; like ansible)
- become_password  (null if not set; repaces sudo_password, should still be encrypted)

### Add CLI
- Add cli should support these new options
- Man page updates needed

### Edit CLI
- Edit cli should support these new options as a patch
- Man page updates needed

**Comment by abaiken** [comment]
Closed by https://github.com/quipucords/quipucords/pull/453
