### ISSUE TITLE
I want to be able to scan data sources for selected fact groups  (i.e. RHEL, EAP, Fuse, BRMS)

### ISSUE THREAD

**Issue by chambridge** [quipucords/quipucords#418]
## Specify type:
- Enhancement

## Description:
Currently every scan collects data on all facts for all products. We need to extend the scan capabilities to be able to capture a limitation on the facts to be collected.

### Model updates
Create `ScanOptions` model to detail the product capture limitations:
- JBoss EAP (True/False; default True)
- JBoss Fuse (True/False; default True, if true must also collect EAP)
- JBoss BRMS (True/False; default True, if true must also collect EAP)

### API updates
Post with scan options
Get should display scan options
- Update Swagger with scan options object

### CLI Updates
- Add flags to scan start to enable optional products (`--optional-products  jboss-eap jboss-fuse`)
- CLI will transform flags into options object for post
- Update man pages with new options and detail optional product values

### Inspection Scans
- Network inspection scan will use extra_vars to pass enabling optional product scans
- Satellite inspection scan will execute APIs to collect optional product facts
- VCenter is not effected

_____
Work items:

- [ ] https://github.com/quipucords/quipucords/issues/419
- [ ] https://github.com/quipucords/quipucords/issues/420
- [ ] https://github.com/quipucords/quipucords/issues/421
- [x] https://github.com/quipucords/quipucords/issues/422

**Comment by abaiken** [comment]
Update on this issue: After talking with Chris and Noah, we decided to go about this by disabling the optional products rather than adding optional products `(--disable-optional-products jboss-eap)` because all products default to true because it will make more sense as the optional products grow.

**Comment by abaiken** [comment]
Closed by https://github.com/quipucords/quipucords/pull/517
