### ISSUE TITLE
Enable Scan options in API for optional product collection

### ISSUE THREAD

**Issue by chambridge** [quipucords/quipucords#419]
## Specify type:
- Enhancement

## Description:
Currently every scan collects data on all facts for all products. We need to extend the scan capabilities to be able to capture a limitation on the facts to be collected.

### Model updates
Create `ScanOptions` model to detail the product capture limitations:
- JBoss EAP (True/False; default True)
- JBoss Fuse (True/False; default True, if true must also collect EAP)
- JBoss BRMS (True/False; default True, if true must also collect EAP)

### API updates
Post with scan options
Get should display scan options
- Update Swagger with scan options object

**Comment by abaiken** [comment]
Closed by https://github.com/quipucords/quipucords/pull/517
