### ISSUE TITLE
Enable Scan options in CLI for optional product collection

### ISSUE THREAD

**Issue by chambridge** [quipucords/quipucords#420]
## Specify type:
- Enhancement

## Description:
Currently every scan collects data on all facts for all products. We need to extend the scan capabilities to be able to capture a limitation on the facts to be collected.

### CLI Updates
- Add flags to scan start to enable optional products (`--optional-products  jboss-eap jboss-fuse`)
- CLI will transform flags into options object for post
- Update man pages with new options and detail optional product values

**Comment by abaiken** [comment]
Closed by https://github.com/quipucords/quipucords/pull/517
