### ISSUE TITLE
Use Scan options in Network inspection for optional product collection

### ISSUE THREAD

**Issue by chambridge** [quipucords/quipucords#421]
## Specify type:
- Enhancement

## Description:
Currently every scan collects data on all facts for all products. We need to extend the scan capabilities to be able to capture a limitation on the facts to be collected.

### Inspection Scans
- Network inspection scan will use extra_vars to pass enabling optional product scans

**Comment by abaiken** [comment]
Closed by https://github.com/quipucords/quipucords/pull/517
