### ISSUE TITLE
Dictionary key errors in subman role causing scan to fail

### ISSUE THREAD

**Issue by kdelee** [quipucords/quipucords#438]
## Specify type:
- Bug

### Bug severity (if applicable):
- High
___

## Description:
It appears there needs to be some more guarding of tasks based on whether or not a dictionary contains expected keys.

The offending line is reported as [`quipucords/roles/subman/tasks/main.yml': line 88, column 3`](https://github.com/quipucords/quipucords/blob/d5a37f9b0c7eeb8f6031716a7bc7bc256d09d2e3/roles/subman/tasks/main.yml#L88) but the whole role should probably be inspected.
___

### Expected behavior:
Scan completes without encountering key errors if data is unavailable.

### Actual behavior:
Scan aborts because Ansible quits complaining about syntax errors.

```
{'host': 'localhost', 'result': {'rc': 0, 'stdout': '\r\nfedora-release\r\n25\r\n2\r\n', 'stdout_lines': ['', 'fedora-release', '25', '2'], 'stderr': 'Shared connection to localhost closed.\r\n', 'changed': True, '_ansible_no_log': False}}
{'host': 'localhost', 'result': {'failed': True, 'msg': "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'dict object' has no attribute 'stdout'\n\nThe error appears to have been in '/home/jenkins/workspace/qcs-nightly-automation/quipucords/roles/subman/tasks/main.yml': line 88, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: add subman.has_facts_file to dictionary\n  ^ here\n"}}
An error occurred while executing the Ansible playbook. A task failed to execute properly on a remote host. See logs for further details.
An error occurred while executing the Ansible playbook. A task failed to execute properly on a remote host. See logs for further details.

No facts gathered from scan.
Error: Facts not sent to fingerprint engine.  See logs.
ScanJob status is already failed
ScanJob 1 ended
```

### Steps to reproduce:
I have been able to reproduce by scanning a Fedora machine. My guess is you need to scan something that does not have subscription manager.

### Environment information:

Type            | Operating System | OS Version | Python Version | Virtualization
--------------- | ---------------- | ---------- | -------------- | --------------
Scanning System | Fedora             | 26        | 3.6            | Bare Metal
Target System   | (same as scanning system)

**Comment by abaiken** [comment]
Closed by https://github.com/quipucords/quipucords/pull/441
