### ISSUE TITLE
qpc source add/edit does not really enforce single hosts if a range or CIDR is specified

### ISSUE THREAD

**Issue by elyezer** [quipucords/quipucords#449]
## Specify type:
- Bug

### Bug severity (if applicable):
- High
___

## Description:
qpc only checks the number of hosts entries but a single entry can mean more than one host. For example the ansible range notation (e.g. 192.168.0.[1:100]) and CIDR notation (e.g. 192.168.0.0/24) means many hosts and not a single one. If one of those notations is passed as the `--host` no matter if a string or inside a file the source will be added or edited and it should not.  
___

### Expected behavior:
The validation of the hosts value should consider ansible range and CIDR notations and fail if those are used when a source of type vcenter is being created/edited.
 
### Actual behavior:
The validation accepts ansible range and CIDR notations as valid value

### Steps to reproduce:

Example of a source creation:

```console
$ qpc source add --name test1 --cred a4105bad-4cb4-4979-8a0f-4f1441f0d3d5 --hosts "192.168.0.0/24" --type vcenter
Source "test1" was added

$ qpc source show --name test1
{
    "credentials": [
        {
            "id": 72,
            "name": "a4105bad-4cb4-4979-8a0f-4f1441f0d3d5"
        }
    ],
    "hosts": [
        "192.168.0.[0:255]"
    ],
    "id": 385,
    "name": "test1",
    "port": 443,
    "source_type": "vcenter"
}
```

Example of an edit:

```console
$ qpc source edit --name test1 --hosts "127.0.0.0/24"
Source "test1" was updated

$ qpc source show --name test1
{
    "credentials": [
        {
            "id": 72,
            "name": "a4105bad-4cb4-4979-8a0f-4f1441f0d3d5"
        }
    ],
    "hosts": [
        "127.0.0.[0:255]"
    ],
    "id": 385,
    "name": "test1",
    "port": 443,
    "source_type": "vcenter"
}
```

### Environment information:
Not applicable

**Comment by abaiken** [comment]
Solved by https://github.com/quipucords/quipucords/pull/461
