### ISSUE TITLE
I want results to be available at any point during a scan in case I need to pause or stop the scan or it crashes due to a bug.

### ISSUE THREAD

**Issue by chambridge** [quipucords/quipucords#45]
## Specify type:
- Enhancement
___

## Description:
As a user collecting partial results from the scan will be helpful if there are issues with the scan or the scan is taking more time than expect (or if a crash occurs). Being able to obtain as much data from the result as possible will help minimize any need for reruns of a scan.

Related to: 
https://github.com/quipucords/rho/issues/19

**Comment by kholdaway** [comment]
This functionality is complete
