### ISSUE TITLE
qpc gives missing source error when not logged in

### ISSUE THREAD

**Issue by noahl** [quipucords/quipucords#478]
If I run `python bin/qpc scan start --sources sonar-jbossfuseonkaraf-rhel-7-vc` before I log in, I get
```
Source "sonar-jbossfuseonkaraf-rhel-7-vc" does not exist.
```

When I log in, the source appears. It would be helpful if the error message reflected the fact that I am not logged in, rather than talking about a missing source.

**Comment by noahl** [comment]
I also tried to add a source when not logged in and got this exciting error message:
```
An error occurred while processing the "--cred" input values. Failed to add source "kevan-scan". For more information, see the server log file.
```

Logging in fixed the problem.

**Comment by noahl** [comment]
This was closed by @tgerla 's PR. I'l assign it to him and close the issue.

**Comment by kholdaway** [comment]
It seems to be a duplicate issue.
