### ISSUE TITLE
Ansible stops on errors in the playbook

### ISSUE THREAD

**Issue by noahl** [quipucords/quipucords#502]
Ansible can recover from errors in task execution, but if there are errors in the playbook itself, it stops.

Steps to reproduce:
  1. Set up an environment where ssh will fail. Get Sonar to start an inspect scan anyway (you'll need to bypass the connect scan first)
  2. Get failure in `redhat_packages` role. It can't get the `['stdout_lines']` of a task that failed.

I can fix any individual instance of this, but the overall pattern is a hit to reliability. We need to think about this.

**Comment by noahl** [comment]
I talked to @tgerla about it. The short-term plan to fix these issues is to move the processing into Python, which also helps our situation with the replayable logs.

If we had a situation where we had to keep the processing in the playbook, maybe because we needed the output for another task, Tim pointed out Ansible blocks for error handling.

**Comment by chambridge** [comment]
@noahl Are you making this change before working on https://github.com/quipucords/quipucords/issues/484?

**Comment by noahl** [comment]
@chambridge I want to make the short-term fix before #484 , because otherwise the test I wrote to verify #484 will fail with playbook errors.

To clarify the above, the only things I want to move into Python are the ones that error when ssh crashes, and the reason is so I can fix #484 (and to help in general, I guess). It's looking like a pretty small number of tasks at this point.

**Comment by noahl** [comment]
Unfortunately, the fix I wanted to do above won't work, at least not for everything. One of the failing tasks is `redhat_packages_gpg_is_redhat`, which is used later on in the same file in a `when` clause. This means that we have to keep the processing in Ansible, since we have no way to send facts from a task back to Sonar Python code and then back to another task. (@tgerla FYI).

I got it working by using `redhat_packages_gpg_is_redhat | json_query("stdout_lines[0]")` instead of `redhat_packages_gpg_is_redhat['stdout_lines'][0]`. I'll plan to stick with that for now unless someone objects.

**Comment by kdelee** [comment]
One way I could conceive of calling python in anisble and using the result in the playbook would be to have ansible call a python script and delegate the task to localhost and register the result in a variable.

**Comment by kholdaway** [comment]
This fix for this breaks network scan.  I am going to re-open and revert the PR.

**Comment by kholdaway** [comment]
I got it to work.  There was a configuration error due to merge to master.  Sorry for the false alarm.
