### ISSUE TITLE
JBoss/EAP printing errors to log when run against our VCenter systems

### ISSUE THREAD

**Issue by kholdaway** [quipucords/quipucords#515]
# Opening a new issue
___

## Specify type:
- Bug

### Bug severity (if applicable):
- High

___

## Description:
I ran a network scan of our VCenter systems with log level set to INFO.  I noticed that EAP/JBoss had a few errors output.

Here are sample errors:
```Bad result from ps (1 processes)
Remote command returned bash: systemctl: command not found

Remote command returned chkconfig version 1.3.30.2 - Copyright (C) 1997-2000 Red Hat, Inc.
This may be freely redistributed under the terms of the GNU Public License.

usage:   chkconfig --list [name]
         chkconfig --add <name>
         chkconfig --del <name>
         chkconfig [--level <levels>] <name> <on|off|reset|resetpriorities>

Remote command returned 
```

To reproduce:

1. Set env with export DJANGO_LOG_LEVEL='INFO'
2. Run a network scan on our VCenter hosts.  I used these IPs
```
10.10.181.14
10.10.181.132
10.10.181.154
10.10.181.221
10.10.182.250
10.10.181.13
10.10.182.244
10.10.181.72
10.10.181.192
10.10.181.50
10.10.182.194
10.10.181.9
10.10.182.95
10.10.182.201
10.10.181.147
10.10.181.253
10.10.181.3
10.10.182.50
10.10.182.110
10.10.181.205
10.10.181.209
10.10.182.46
10.10.182.81
10.10.181.135
10.10.182.141
10.10.182.216 
```
3. Watch output and look fo errors.

Here are several lines that look like the potential source:

- https://github.com/quipucords/quipucords/blob/4e4f24b3566b78ff1de9cf734f51f777d776a06f/quipucords/scanner/network/processing/process.py#L103
- https://github.com/quipucords/quipucords/blob/0e6b253fb2d80bb15035a2884f0f485e657731b3/quipucords/scanner/network/processing/eap.py#L116

I suggest adding the host to the error messages so that future issues (I opened a separate issue for this --> https://github.com/quipucords/quipucords/issues/514)

**Comment by noahl** [comment]
I've reproduced the issue.

**Comment by noahl** [comment]
There seem to be several different problems, so I'll be filing new issues for each bug and mentioning that they are part of this one.
