### ISSUE TITLE
Add detail report CLI for a scan

### ISSUE THREAD

**Issue by chambridge** [quipucords/quipucords#526]
## Specify type:
- Enhancement

## Description:
A detailed report utilizes the `/api/v1/facts/<fact_collection_id>/` endpoint.

Interaction with the CLI should be as follows:

`qpc report detail  --id <scan_id>  (--json | --csv) --output-directory <path>`
Detail report outputs to a file per source information. Files should be named with a <source_name>_<source_id>.<format> 

The CLI code can extract the `fact_collection_id` from the scan, if available, and return the resulting data. Supporting output of JSON and CSV.  If the user selects CSV then any multi-dimensional data like a list will be converted into a string separated with semi-colons `;`, dictionaries will be key `:` value separated by semi-colons.

**Comment by kholdaway** [comment]
Does anyone have a suggestion for csv output?  Is the build in python csv the best choice or is there a 3rd party library that would be better?

**Comment by chambridge** [comment]
The built-in csv module was pretty simple to use. I would suggest utilizing it. If you look for a magical 3rd party library, it must be one that is widely available via RPM (i.e. in EPEL6 & EPEL7 repos if the conversion will be client-side). 

However, perhaps we should think about pushing it back to the API layer with a `format` query param of sorts and returning a zip for the detailed report that we could still expand on the CLI if that was appropriate.
