### ISSUE TITLE
Add start/end times to the scantask/job models and have the connect/inspect tasks populate

### ISSUE THREAD

**Issue by kholdaway** [quipucords/quipucords#542]
# Opening a new issue
___

## Specify type:
- Enhancement

## Description:
Add start/end times to the scantask/job models and have the connect/inspect tasks populate
___

**Comment by kdelee** [comment]
@abaiken So is this just adding data about when the scantask/jobs started and stopped?

**Comment by abaiken** [comment]
@kdelee Yes it is just adding the time that the job/task starts and ends.

**Comment by abaiken** [comment]
Closed by https://github.com/quipucords/quipucords/pull/556
