### ISSUE TITLE
RFE: Expiring authentication tokens

### ISSUE THREAD

**Issue by kdelee** [quipucords/quipucords#554]
## Specify type:
- Enhancement

### Bug severity (if applicable):
- Medium
___

## Description:
Currently the authentication tokens that the server generates never expire. This has the effect of never really being able to "logout" and stop anyone else from re-using my token at a later date.
___
### Expected behavior:
As a user, I'd like to believe that I could destroy my token after I am done with it and the server will no longer honor it.

### Actual behavior:
Tokens last for indefinite period of time.

**Comment by chambridge** [comment]
Looks like it might be doable with https://github.com/JamesRitchie/django-rest-framework-expiring-tokens

Note: That if you are running in *PRODUCTION* mode, your session will expire if you close the browser.
```
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
```
