### ISSUE TITLE
RFE: As a user of the CLI client, I'd like long output paginated

### ISSUE THREAD

**Issue by kdelee** [quipucords/quipucords#555]
## Specify type:
- Enhancement

### Bug severity (if applicable):
- Medium
___

## Description:
Output from the command line client `qpc` can easily exceed normal terminal scroll-back limits. As a user, I'd like long output sent to the system pager if I have one set. This would have the effect of allowing me to use search functions as well if it is sent to something like `less` (this is what I've found most systems have their `$PAGER` set to).
___
### Expected behavior:
The command line client output is human-consumable.

### Actual behavior:
It is easy to evoke very long output that spews past my scroll-back limit so I cannot review or understand the results.

**Comment by kholdaway** [comment]
Remaining lists are paginated.  This was removed from CLI.
