### ISSUE TITLE
Some facts still need post processing

### ISSUE THREAD

**Issue by kholdaway** [quipucords/quipucords#565]
# Opening a new issue
___

## Specify type:
- Bug

### Bug severity (if applicable):
- High

___

## Description:
Some raw facts have ansible output.  They need post processing.

For example, 
``` 
 "cpu_model_ver": {
                        "rc": 0,
                        "stdout": "62\r\name\t: Intel(R) Xeon(R) CPU E5-2697 v2 @ 2.70GHz\r\n",
                        "stdout_lines": [
                            "62",
                            "ame\t: Intel(R) Xeon(R) CPU E5-2697 v2 @ 2.70GHz"
                        ],
                        "stderr": "Shared connection to 10.10.181.154 closed.\r\n",
                        "changed": True,
                        "_ansible_no_log": False
                    },
```
Should be:
```
 "cpu_model_ver": "Intel(R) Xeon(R) CPU E5-2697 v2 @ 2.70GHz"
___

## Bug Report

### Steps to reproduce:
Run a network scan and view raw output using /facts/{fact_collection_id}.

Here is a complete scan that shows many facts with this issue.
```
{
    "id": 1,
    "sources": [
        {
            "source_id": 5,
            "source_type": "network",
            "facts": [
                {
                    "have_java": True,
                    "have_locate": False,
                    "connection_host": "10.10.181.154",
                    "connection_port": 22,
                    "connection_uuid": "0c57b628-91e7-57bc-b0c7-a4ffaa0b8b44",
                    "cpu_vendor_id": {
                        "rc": 0,
                        "stdout": "GenuineIntel\r\n",
                        "stdout_lines": [
                            "GenuineIntel"
                        ],
                        "stderr": "Shared connection to 10.10.181.154 closed.\r\n",
                        "changed": True,
                        "_ansible_no_log": False
                    },
                    "cpu_model_name": {
                        "rc": 0,
                        "stdout": "Intel(R) Xeon(R) CPU E5-2697 v2 @ 2.70GHz\r\n",
                        "stdout_lines": [
                            "Intel(R) Xeon(R) CPU E5-2697 v2 @ 2.70GHz"
                        ],
                        "stderr": "Shared connection to 10.10.181.154 closed.\r\n",
                        "changed": True,
                        "_ansible_no_log": False
                    },
                    "cpu_bogomips": {
                        "rc": 0,
                        "stdout": "5400.00\r\n",
                        "stdout_lines": [
                            "5400.00"
                        ],
                        "stderr": "Shared connection to 10.10.181.154 closed.\r\n",
                        "changed": True,
                        "_ansible_no_log": False
                    },
                    "cpu_cpu_family": {
                        "rc": 0,
                        "stdout": "6\r\n",
                        "stdout_lines": [
                            "6"
                        ],
                        "stderr": "Shared connection to 10.10.181.154 closed.\r\n",
                        "changed": True,
                        "_ansible_no_log": False
                    },
                    "cpu_model_ver": {
                        "rc": 0,
                        "stdout": "62\r\name\t: Intel(R) Xeon(R) CPU E5-2697 v2 @ 2.70GHz\r\n",
                        "stdout_lines": [
                            "62",
                            "ame\t: Intel(R) Xeon(R) CPU E5-2697 v2 @ 2.70GHz"
                        ],
                        "stderr": "Shared connection to 10.10.181.154 closed.\r\n",
                        "changed": True,
                        "_ansible_no_log": False
                    },
                    "cpu_count": "1",
                    "cpu_core_per_socket": "1",
                    "cpu_siblings": "1",
                    "cpu_hyperthreading": False,
                    "cpu_socket_count": "1",
                    "cpu_core_count": "1",
                    "date_date": {
                        "rc": 0,
                        "stdout": "Wed Jan 31 13:41:20 EST 2018\r\n",
                        "stdout_lines": [
                            "Wed Jan 31 13:41:20 EST 2018"
                        ],
                        "stderr": "Shared connection to 10.10.181.154 closed.\r\n",
                        "changed": True,
                        "_ansible_no_log": False
                    },
                    "date_anaconda_log": "2017-07-25",
                    "date_machine_id": {
                        "rc": 0,
                        "stdout": "2017-07-25\r\n",
                        "stdout_lines": [
                            "2017-07-25"
                        ],
                        "stderr": "Shared connection to 10.10.181.154 closed.\r\n",
                        "changed": True,
                        "_ansible_no_log": False
                    },
                    "date_filesystem_create": {
                        "rc": 0,
                        "stdout": "tune2fs: Bad magic number in super-block while trying to open /dev/mapper/rhel_dhcp182--50-root\r\nCouldn"t find valid filesystem superblock.\r\n\r\n", "stdout_lines": ["tune2fs: Bad magic number in super-block while trying to open /dev/mapper/rhel_dhcp182--50-root", "Couldn"t find valid filesystem superblock.",
                        ""
                    ],
                    "stderr": "Shared connection to 10.10.181.154 closed.\r\n",
                    "changed": True,
                    "_ansible_no_log": False
                },
                "date_yum_history": "2017-07-25",
                "dmi_bios_vendor": "Phoenix Technologies LTD",
                "dmi_bios_version": "6.00",
                "dmi_system_manufacturer": "VMware, Inc.",
                "dmi_processor_family": "Unknown",
                "dmi_system_uuid": "2B5D1E42-0959-5095-6E32-A673E9A1CF2D",
                "etc_release_name": "Red Hat Enterprise Linux Server",
                "etc_release_version": "7.4 (Maipo)",
                "etc_release_release": "Red Hat Enterprise Linux Server release 7.4 (Maipo)",
                "etc_issue": "\\S\r\nKernel \\r on an \\m\r\n\r\n",
                "jboss_eap_running_paths": """",
                "eap_home_candidates": [],
                "jboss_eap_common_files": "[]",
                "jboss_eap_processes": "0",
                "jboss_eap_packages": "0",
                "jboss_eap_id_jboss": "false",
                "jboss_eap_systemctl_unit_files": "[]",
                "jboss_eap_chkconfig": "[]",
                "jboss_brms_business_central_candidates": [],
                "jboss_brms_kie_server_candidates": [],
                "business_central_candidates_eap": [],
                "kie_server_candidates_eap": [],
                "business_central_candidates": [],
                "kie_server_candidates": [],
                "jboss_brms_locate_kie_api": [],
                "karaf_homes": [],
                "karaf_home_system_org_jboss": {
                    "failed": True,
                    "msg": "the field "args" has an invalid value, which appears to include a variable that is undefined. The error was: "item" is undefined\n\nThe error appears to have been in "/Users/kholdawa/dev/quipucords/roles/jboss_fuse_on_karaf/tasks/main.yml": line 72, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: check system/org/jboss/fuse\n      ^ here\n"
                },
                "jboss_fuse_systemctl_unit_files": "["sys-fs-fuse-connections.mount                 static"]",
                "ifconfig_mac_addresses": [
                    "00:50:56:9e:3a:1f"
                ],
                "ifconfig_ip_addresses": [
                    "10.10.181.154"
                ],
                "redhat_packages_gpg_is_redhat": True,
                "redhat_packages_gpg_num_rh_packages": "371",
                "redhat_packages_gpg_num_installed_packages": "371",
                "redhat_packages_gpg_last_installed": "java-1.8.0-openjdk-devel-1.8.0.141 Installed:Wed 30 Aug 2017 12:45:39 PM EDT",
                "redhat_packages_gpg_last_built": "java-1.8.0-openjdk-headless-1.8.0.141 Built:Fri 14 Jul 2017 12:27:41 PM EDT",
                "redhat_release_name": "redhat-release-server",
                "redhat_release_version": "7.4",
                "redhat_release_release": "18.el7",
                "subman_cpu_cpu": "1",
                "subman_cpu_core_per_socket": "1",
                "subman_cpu_cpu_socket": "1",
                "subman_virt_host_type": "vmware",
                "subman_virt_is_guest": True,
                "subman_virt_uuid": "2B5D1E42-0959-5095-6E32-A673E9A1CF2D",
                "uname_os": "Linux",
                "uname_hostname": "dhcp181-154.gsslab.rdu2.redhat.com",
                "uname_processor": "x86_64",
                "uname_kernel": "3.10.0-693.el7.x86_64",
                "uname_all": "Linux dhcp181-154.gsslab.rdu2.redhat.com 3.10.0-693.el7.x86_64 #1 SMP Thu Jul 6 19:56:57 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux",
                "uname_hardware_platform": "x86_64",
                "virt_virt": "virt-guest",
                "virt_type": "vmware",
                "virt_what_type": "vmware"
            }
        ]
    }
],
"status": "complete"
}
```

**Comment by kdelee** [comment]
@kholdaway I'm getting an ansible traceback in a fact

```
 'karaf_home_system_org_jboss': {'failed': True,
                                 'msg': "the field 'args' has an invalid "
                                        'value, which appears to include a '
                                        'variable that is undefined. The error '
                                        "was: 'item' is undefined\n"
                                        '\n'
                                        'The error appears to have been in '
                                        "'/home/elijah/sfw/quipu/quipucords/roles/jboss_fuse_on_karaf/tasks/main.yml': "
                                        'line 72, column 7, but may\n'
                                        'be elsewhere in the file depending on '
                                        'the exact syntax problem.\n'
                                        '\n'
                                        'The offending line appears to be:\n'
                                        '\n'
                                        '\n'
                                        '    - name: check '
                                        'system/org/jboss/fuse\n'
                                        '      ^ here\n'},
```

You want to lump that in this issue or should I open a new one?

**Comment by abaiken** [comment]
@kdelee I'm going to file a new issue for the bug in the `jboss_fuse_on_karaf` role before I fix the post processing.

**Comment by abaiken** [comment]
Closed by https://github.com/quipucords/quipucords/pull/599
