### ISSUE TITLE
Add product and entitlement data to the system fingerprint model and engine processing

### ISSUE THREAD

**Issue by noahl** [quipucords/quipucords#571]
Take all of the information we are getting from network, vcenter and satellite scans and output a series of yes/maybe/no decisions describing what products are on or not on a particular host.

This comes from a discussion with @chambridge . Chris, did I get this right?

**Comment by chambridge** [comment]
Yep, its really about modeling products and entitlements within the Fingerprint model so its available from the reports endpoint.

**Comment by chambridge** [comment]
Captured more specifically with #701
