### ISSUE TITLE
DOC: quipucords/README.rst edits

### ISSUE THREAD

**Issue by jlprevatt** [quipucords/quipucords#578]
Edits for readme.rst."Round 1" timeframe=beta. Multi-level edit includes copyedit, style consistency, info quality/clarity edit.

The beta.rst is looking great, so would lift/massage any needed text (e.g., intro info) from here vs. using this doc as a beta deliverable.

**Comment by chambridge** [comment]
👍 Agree with focusing on using beta.rst doc over README as the README tends to be more developer focused than consumer focused.

**Comment by chambridge** [comment]
Don't know if this is helpful I know you were looking for a way to generate html on a per build basis.

I completed issue #173 yesterday so we now (like ansible) are hosting our documentation on readthedocs.io here: [http://quipucords.readthedocs.io/en/latest/](http://quipucords.readthedocs.io/en/latest/)

Top level content lives in `docs/source/index.rst` and pulls in data from `man.rst` and `beta.rst` for not. We can certainly re-orient as needed.

If this isn't what you were looking for we can still extend the Makefile to generate one-off html for which ever files we want to make available for customers.

**Comment by jlprevatt** [comment]
I'm not much of one for emoji-ing, being a words person, but this is cool. I had seen the discussion about readthedocs, but I'm not very familiar with it. Tana and I had an extended conversation yesterday about the doc delivery possibilities for beta and what makes the most sense, but this readthedocs step was not part of the discussion. Especially since we don't exactly know how the beta will "launch" and how the invitation/agreement/legalese/docs will get in customer hands--email with links/attachments, or if Bindi/Dan are required to create a more formalized website, etc.
