### ISSUE TITLE
The UI needs data from the API that is not there currently

### ISSUE THREAD

**Issue by jeff-phillips-18** [quipucords/quipucords#607]
## Type:
- Enhancement

### Bug severity (if applicable):
- High
___

## Description:
The UI needs data from the API that is not there currently.
```
GET /sources:
  for each source:
        most recent connection scan:
            id
            start time
            end time
            status
            success_systems
            failed_systems

GET /scans (inspections)
  for each scan:
        name
        most recent scan job
                id
                start time
                end time
                status
                success_systems
                failed_systems
        total count of # runs for this scan

GET /credentials:
  for each credential:
        sources using this credential
```

See https://docs.google.com/presentation/d/12TU-gVCg6XXmPPrwl1esQpIs_AFS3hw97G_NpsoCZXY/ for current UI mock ups.

@chambridge @kholdaway @serenamarie125 @quipucords/ux-ui

**Comment by chambridge** [comment]
This is an enhancement to the API not a bug. We plan to address these items following the initial beta drop.
