### ISSUE TITLE
Support pagination in credentials List API and CLI

### ISSUE THREAD

**Issue by chambridge** [quipucords/quipucords#613]
## Specify type:
- Enhancement

## Description:
Current credentials List API does not support pagination. We need to update this prior to the initial release. We will be utilizing the standard Django format: http://www.django-rest-framework.org/api-guide/pagination/#pagenumberpagination

The current output should be rolled into the `results` field.

CLI should support paging by being able to make a new request if a `next` value exists. We will prompt with an `Press enter to see the next set of results.`

_____
Related to issue: https://github.com/quipucords/quipucords/issues/607

**Comment by kdelee** [comment]
Looks like this is related https://github.com/quipucords/quipucords/issues/555
