### ISSUE TITLE
Support pagination in sources List API and CLI

### ISSUE THREAD

**Issue by chambridge** [quipucords/quipucords#614]
## Specify type:
- Enhancement

## Description:
Current sources List API does not support pagination. We need to update this prior to the initial release. We will be utilizing the standard Django format: http://www.django-rest-framework.org/api-guide/pagination/#pagenumberpagination

The current output should be rolled into the `results` field.

CLI should support paging by being able to make a new request if a `next` value exists. We will prompt with an `Press enter to see the next set of results.`

_____
Related to issue: https://github.com/quipucords/quipucords/issues/607

**Comment by jeff-phillips-18** [comment]
The API should also support sorting as we don't want client side sorting on the sub-set of results.

**Comment by chambridge** [comment]
makes sense, but sorty would be a different issue. Looks like it should be doable with the following: http://www.django-rest-framework.org/api-guide/filtering/#orderingfilter

But we need to know the fields we want to sort on for each API.

**Comment by kdelee** [comment]
Looks like this is related https://github.com/quipucords/quipucords/issues/555
