### ISSUE TITLE
Access to username and logout function in API

### ISSUE THREAD

**Issue by jeff-phillips-18** [quipucords/quipucords#616]
# Opening a new issue
___

## Type:
- Enhancement
___

## Description:
The API should provide a means to retrieve the username associated with the current auth token and a means to invalidate the current auth token.
___

**Comment by chambridge** [comment]
Looks like logout should be doable as the following:
https://docs.djangoproject.com/en/2.0/topics/auth/default/#how-to-log-a-user-out

We can likely expose an API that provides the username from the token by quering the User model.
