### ISSUE TITLE
Check Python version in `bin/qpc`

### ISSUE THREAD

**Issue by noahl** [quipucords/quipucords#618]
Running `qpc` with the wrong version of Python can produce confusing error messages that make `qpc` look bad, like this one:

```
User name:admin
Traceback (most recent call last):
  File "bin/qpc", line 30, in <module>
    CLI().main()
  File "/home/nlavine/rho/quipucords/qpc/cli.py", line 131, in main
    action.main(self.args)
  File "/home/nlavine/rho/quipucords/qpc/clicommand.py", line 89, in main
    self._validate_args()
  File "/home/nlavine/rho/quipucords/qpc/server/login_host.py", line 58, in _validate_args
    self.username = input(_(messages.LOGIN_USERNAME_PROMPT))
  File "<string>", line 1, in <module>
NameError: name 'admin' is not defined
```

Instead, we should put a Python version check in `bin/qpc` that prints out a nice error explaining the problem before the user gets far enough to see that error message.

**Comment by noahl** [comment]
Never mind, this was a Python version issue. I was running qpc with Python 2.7.5.

Maybe we should have a Python version check in the initial script to prevent this sort of mistake?

**Comment by chambridge** [comment]
Is this still a problem? Or are you asking if we should change it to a Python version check issue? If the latter, I'm fine wit that.

**Comment by noahl** [comment]
I'll change to a Python version check issue.
