### ISSUE TITLE
DOC: quipucords/docs/source/beta.rst edits

### ISSUE THREAD

**Issue by jlprevatt** [quipucords/quipucords#620]
Edits for man.rst."Round 1" timeframe=beta. Multi-level edit includes copyedit, style consistency, info quality/clarity edit.

**Comment by kdelee** [comment]
@jlprevatt @chambridge I'm going to post my notes from walking through the beta doc here

**Comment by kdelee** [comment]
FWIW I think maybe this section could get refactored:

```
Verify the server is responding correctly by launching a browser to https://<ip_address>:<port>/admin. If 
your browser is on the same system as the server and you exposed port 443 the URL would be 
https://localhost/admin. When your browser loads you should see the administrative login dialog. From 
here you can log into the server and change the default password. The server comes defaulted with a user 
admin and password pass. You should find the “Change Password” selection in the upper right navigation 
bar.
```

Maybe a heading that says "Verify install" and line break and new sub heading "Change admin password"

Blew right past this and had to resort to searching through the page to find it.

**Comment by jlprevatt** [comment]
@kdelee I got bogged down in this section too when I was trying to mark it up, and I have some notes about breaking up the sections. So stay tuned.

RE your comment about the `https:/serverlocation/admin` or `https://serverlocation`. How good is the messaging on the dummy page (if any)? In general, documentation does not try to cover the "Here is your step. And if you didn't read the step and follow it like *(ahem)* I just told you to, here is how you get out of the mess you just made for yourself." use case. Otherwise, doc could go on and on forever with those type of fix-it steps. Or am I misunderstanding that part of the comment?

And thanks for your input. I really appreciate that you tried walking through the steps.

**Comment by kdelee** [comment]
I understand how you cannot provide all the "maybe you decided to pour gasoline on your computer and light it on fire after step 2" scenarios.

There is no messaging on the `https://serverlocation` page. It looks like a real login page. And, you can actually login. But then it takes you to dummy UI for general quipucords usage and does not tell you that it is not supposed to be used. 

Really, this problem may be best solved by @quipucords/development either redirecting people or adding big "NOT FOR USE" warnings to the some-day-soon-UI page. OR...adding a link to the admin console. :)
