### ISSUE TITLE
Check if Running RHEL for SAP

### ISSUE THREAD

**Issue by mdvickst** [quipucords/quipucords#65]
# Openning a new issue
___

## Specify type:
- Enhancement

### Bug severity (if applicable):
- Low
___

## Description:
We should be able to detect if a RHEL Server is running the RHEL for SAP applications or RHEL for SAP HANA variant. 
Possible Indicators for SAP Applications
- Presence of compat-sap-c++ RPM (or anything that contains that text e.g. compat-sap-c++-5)
- Has repos enabled for rhel-sap-for-rhel
- 146.pem certificate in /etc/pki/products

Possible Indicators for SAP HANA
- Presence of compat-sap-c++ RPM (or anything that contains that text e.g. compat-sap-c++-5)
- Has repos enabled for rhel-sap-hana-for-rhel
- 241.pem certificate in /etc/pki/products
___

**Comment by justinkreft** [comment]
This is an ongoing effort.

**Comment by justinkreft** [comment]
Will be required after we complete export to SubsWatch
