### ISSUE TITLE
Beta doc updates for SELinux and simpler usability

### ISSUE THREAD

**Issue by chambridge** [quipucords/quipucords#664]
## Specify type:
- Enhancement

## Description:
Capture some of the updates from Elijah on SELinux and usability.

**Comment by kdelee** [comment]
@chambridge here are my notes about that section


-Typo/malformated area in section about making the directories to mount to the container:


    Create directories to house the SSH keys (/opt/quipucords/sshkeys), database (/opt/quipucords/data), and log output (/opt/quipucords/log):

    mkdir sshkeys mkdir data mkdir log

If users did this verbatim they'd make a dir called mkdir. Just tell them `mkdir sshkeys data log`

- Reccomend users create the quipucords data directories in userspace (e.g. `~/quipucords`)
	mkdir -p ~/quipucords/sshkeys
        mkdir -p ~/quipucords/data
        mkdir -p ~/quipucords/log
- Need section that says "If SELinux is enabled, the selinux lables on the mounted volumes will need to be changed to allow docker to have read/write access. Docker can do this for you if you append the `:z` option to each volume mounted. So, the command will instead look like:"

```
docker run --name quipucords -d -p443:443 -v ~/quipucords/sshkeys:/sshkeys:z -v ~/quipucords/data:/var/data:z -v ~/quipucords/log:/var/log:z -i quipucords:latest

```

- Need to mention that need to copy PRIVATE sshkeys into ~/quipucords/sshkeys
