### ISSUE TITLE
Help message should not be displayed when a scan can't be restarted because it was previously canceled

### ISSUE THREAD

**Issue by elyezer** [quipucords/quipucords#684]
# Opening a new issue
___

## Specify type:
- Enhancement

### Bug severity (if applicable):
- Medium
___

## Description:
`qpc` shows the message `Error: Scan cannot be restarted. The scan must be paused for it to be restarted.` when trying to restart a canceled scan. It also shows the usage/help message which indicates to the user that the command may have a syntax error.

In terms of usability it seems that only the error message is enough. So the usage/help message should not be displayed.
___

### Expected behavior:
Usage instructions is shown even when the command have no syntax problem in addition to an error message.

### Actual behavior:
Only the error message should be shown and the usage instructions should not be displayed.

### Steps to reproduce:
1. Start a scan
2. Cancel it
3. Try to restart

### Environment information:
N/A

**Comment by chambridge** [comment]
This is already fixed in `master` as part of the work that was done for: https://github.com/quipucords/quipucords/pull/742
