### ISSUE TITLE
UI front-end sprint: Testing & View refinement, Initial authentication and compile

### ISSUE THREAD

**Issue by cdcabrera** [quipucords/quipucords#690]
## Specify type:
- Enhancement
- UI

## Description:
- [x] Build updates #727 #754  #774 #804 #832 
- [x] Form refinement #728 #749 #689 #804
  - Wizard ```689, 804``` 
  - Credential ```749```
- [x] Testing updates #774 #781 #804 
  - Travis, coordinate
  - Unit ```774, 781, 804``` 
- [x] User authentication #713 #761 
- [x] View refinement #712 #728 #749 #761 #798 #805 #809 #833 #846 
  - Login ```712, 761``` 
  - Sources ```805, 809```
  - Scans ```728, 805, 809, 833```
  - Credentials ```728```

**Comment by kdelee** [comment]
@cdcabrera, @elyezer was wondering about your progress on this. Should he wait to merge his UI test until this issue is done? He was getting authentication errors and was wondering if you all were not yet collecting and passing the authentication token after login.

**Comment by cdcabrera** [comment]
@kdelee @elyezer indeed, the authentication error your seeing is related to that, and yes, it would probably be good for you to wait for part of this issue to be resolved.  

We've been using these collected issues as tracking for sprint UI work. In fact, saying that, I may update the issue name to reflect that better.

#### What the UI still has to implement... 
Basically we have to place an authentication component with the token in-between the API calls and the UI. We created the base for this last sprint, the integration piece is this sprint. We'll keep you guys in the loop.

**Comment by chambridge** [comment]
Should this be closed?

**Comment by cdcabrera** [comment]
@chambridge close, we have one remaining bit for today #846
