### ISSUE TITLE
I want a scan object that allows me to easily re-run scans of defined sources

### ISSUE THREAD

**Issue by chambridge** [quipucords/quipucords#693]
## Specify type:
- Enhancement

## Description:
I want to be able to scan the same sources over easily by having a representative model instead of just one off jobs.

### Model:
Scan Model should be composed of:
- id
- name
- sources
- options
- jobs (array; when serialized should be ordered most recent with a slim set of: `id`, `report_id)
- most_recent (object with details on most recent run: `id`, `report_id`, `start_time`, `end_time`, `systems_count`, `systems_scanned`, `systems_failed`, `status`) **computed

### API
Updates will move the current scan jobs under the scan object.

*POST* - `/api/v1/scans/` : create a scan
*GET*   - `/api/v1/scans/` :  get list of named scans
*GET*   - `/api/v1/scans/<scan_id>/` :  get a scan
*PUT/PATCH* - `/api/v1/scans/<scan_id>/`: update a scan
*DELETE* - `/api/v1/scans/<scan_id>/`: delete a scan

*POST* - `/api/v1/scans/<scan_id>/jobs/`: start a scan job
*GET* - `/api/v1/scans/<scan_id>/jobs/`: get list of jobs for a scan

*GET* - `/api/v1/jobs/<job_id>/`: get a scan job
*PUT* - `/api/v1/jobs/<job_id>/pause/`: pause a scan job
*PUT* - `/api/v1/jobs/<job_id>/cancel/`: cancel a scan job
*PUT* - `/api/v1/jobs/<job_id>/restart/`: restart a scan job

### CLI

Add a scan:
```
qpc scan add --name <scan name> --sources <sources ...> [--max-concurrency val] [--disable-optional-products prod1 ...]
```

Edit a scan:
```
qpc scan add --name <scan name> --sources <sources ...> [--max-concurrency val] [--disable-optional-products prod1 ...]
```

Clear a scan:
```
qpc scan clear --name <scan name>
```

List scans:
```
qpc scan list
```

Show a scan:
```
qpc scan --name <scan name>
```

List scan jobs for a scan:
```
qpc scan job --name <scan name>  (--id <job_id> | --all) [--status STATUS]
```

Start a scan:
```
qpc scan start --name <scan name>
```

Show a job's status:
```
qpc scan status --id <job_id>
```

Pause/Cancel/Restart a scan job. (stay the same just using job_id:
```
qpc scan (pause | cancel | restart) --id <job_id>
```
____

Work items:

- [x] https://github.com/quipucords/quipucords/issues/696
- [x] https://github.com/quipucords/quipucords/issues/697
- [x] https://github.com/quipucords/quipucords/issues/698
- [x] https://github.com/quipucords/quipucords/issues/700

**Comment by jeff-phillips-18** [comment]
The UI wants to show a list of previous runs as well, the id, time, status, success hosts count and failed hosts count per previous run.

**Comment by chambridge** [comment]
@jeff-phillips-18 Those items should already be accounted for in the model described above with the `jobs` & `most_recent` data.

**Comment by jeff-phillips-18** [comment]
👍  Thanks @chambridge I wasn't sure if that's what the jobs were.
