### ISSUE TITLE
Support Scan model and APIs

### ISSUE THREAD

**Issue by chambridge** [quipucords/quipucords#696]
## Specify type:
- Enhancement

## Description:
Support the scan model object and its associated APIs.

### Model:
Scan Model should be composed of:
- id
- name
- sources
- options
- jobs (array; when serialized should be ordered most recent with a slim set of: `id`, `report_id)
- most_recent (object with details on most recent run: `id`, `report_id`, `start_time`, `end_time`, `systems_count`, `systems_scanned`, `systems_failed`, `status`) **computed

### API
Updates will move the current scan jobs under the scan object.

*POST* - `/api/v1/scans/` : create a scan
*GET*   - `/api/v1/scans/` :  get list of named scans
*GET*   - `/api/v1/scans/<scan_id>/` :  get a scan
*PUT/PATCH* - `/api/v1/scans/<scan_id>/`: update a scan
*DELETE* - `/api/v1/scans/<scan_id>/`: delete a scan

**Comment by kdelee** [comment]
@chambridge re: deleting a scan.

I imagine a `DELETE` will also cancel any currently running tasks associated with the scan. 
I also imagine that the resources usually available at `/api/v1/scans/<scan_id>/results/` will no longer be available.
But how will this propogate though the rest of the system? Will anything that has made it into a fact collection at the `/api/v1/facts/<fact_collection_id>` location still exist, and thus still end up in available reports? Or will these be destroyed as well?

**Comment by chambridge** [comment]
@kdelee 
- Yes,  `DELETE` should have that effect.
- Yes, `/api/v1/scans/<scan_id>/results/` will be going away (it was really more useful for development and demo early on, but didn't scale well for 24K systems)

- Reports would continue to exist. We create them with their own identifier so we can split the model of the scan and the report itself. Currently, via the CLI we perform a look up of the `fact_collection_id` from the Scan Job model to make it simple for the user, but the report is processed with the `fact_collection_id` to keep the report data around.

**Comment by chambridge** [comment]
https://github.com/quipucords/quipucords/pull/808
