### ISSUE TITLE
Add CLI support for Scan object

### ISSUE THREAD

**Issue by chambridge** [quipucords/quipucords#698]
## Specify type:
- Enhancement

## Description:
Support new CLIs for the scan model:

### CLI

Add a scan:
```
qpc scan add --name <scan name> --sources <sources ...> [--max-concurrency val] [--disable-optional-products prod1 ...]
```

Edit a scan:
```
qpc scan edit --name <scan name> --sources <sources ...> [--max-concurrency val] [--disable-optional-products prod1 ...]
```

Clear a scan:
```
qpc scan clear (--name <scan name> | --all)
```

List scans:
```
qpc scan list
```

Show a scan:
```
qpc scan --name <scan name>
```

**Comment by abaiken** [comment]
@chambridge for the clear command, do we want to have the option to clear all scans, or just one?
 ie. `qpc scan clear (--name <scan name> | --all)`

**Comment by chambridge** [comment]
yes to:
`qpc scan clear (--name <scan name> | --all)`

**Comment by abaiken** [comment]
Closed by https://github.com/quipucords/quipucords/pull/789
