### ISSUE TITLE
Create Jenkins job to build beta image

### ISSUE THREAD

**Issue by chambridge** [quipucords/quipucords#717]
## Specify type:
- Enhancement

## Description:
Build beta image from beta branch on Jenkins and provide a *tar.gz* as a Jenkins artifact at the completion of the job.

## Acceptance Criteria: 
- [ ] Verify that the Job produces a tar.gz
- [ ] Verify that a Docker users can load the image and run the server

**Comment by kdelee** [comment]
FYI for the beta doc, on docker 1.7.1 which is what I got pulled in on a RHEL 6,
Once I scp'd the image up to the server, the way that worked for me was
```
docker load < quipucords.tar.gz
```
I don't think that `docker import` takes files until a later version, but that is not clear from the docker documentation.

https://docs.docker.com/engine/reference/commandline/import/
https://docs.docker.com/engine/reference/commandline/load/
