### ISSUE TITLE
Trying to login to qpc without configuring the server does not provide good message

### ISSUE THREAD

**Issue by kdelee** [quipucords/quipucords#718]
## Specify type:
- Bug

### Bug severity (if applicable):
- Medium
___

## Description:
If I attempt to login to the server with `qpc` but I have not yet configured the server, I get a trace back that is probably a bit cryptic for users and just looks bad because it has a traceback.

___

### Expected behavior:
If I use `qpc` incorrectly, it gives me helpful information so I can do better next time.

### Actual behavior:
If I have not configured the server, and I attempt to login, this is what I see:
```
[scanbasic@dhcp181-3 ~]$ qpc server login
User name: admin
Password: 

Server config /home/scanbasic/.config/qpc/server.config was not found.
Traceback (most recent call last):
  File "/usr/bin/qpc", line 30, in <module>
    CLI().main()
  File "/usr/lib/python3.4/site-packages/qpc/cli.py", line 131, in main
    action.main(self.args)
  File "/usr/lib/python3.4/site-packages/qpc/clicommand.py", line 91, in main
    self._do_command()
  File "/usr/lib/python3.4/site-packages/qpc/clicommand.py", line 74, in _do_command
    headers=self.req_headers)
  File "/usr/lib/python3.4/site-packages/qpc/request.py", line 113, in request
    return post(path, payload, req_headers)
  File "/usr/lib/python3.4/site-packages/qpc/request.py", line 37, in post
    url = get_server_location() + path
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

### Steps to reproduce:
Attempt to login to the server without configuring where it is first.

### Environment information:

Type            | Operating System | OS Version | Python Version | Virtualization
--------------- | ---------------- | ---------- | -------------- | --------------
Scanning System | RHEL             | 6        |             | ESXi

## QPC package
qpc-0.0.1-1.git.330.8b15512.el6.noarch

**Comment by chambridge** [comment]
Fix should go into beta & master branches
