### ISSUE TITLE
RFE: Have "latest" version of docs not refer to specific commit

### ISSUE THREAD

**Issue by kdelee** [quipucords/quipucords#740]
## Specify type:
- Enhancement
___

## Description:
Since we are versioning the docs, I think it would be nice if the master docs did not refer to a specific package for `qpc`, so the latest will get pulled in.

## Acceptance Criteria: 

- [ ] Verify that doc users on "latest" version are directed to download latest version of all packages

**Comment by chambridge** [comment]
Plan on doing this and restructuring a bit after Jamie's next/final sweep through the docs.
