### ISSUE TITLE
Providing `ssl-cert-verify` xor `satellite-version` on creation or edit overwrites other option

### ISSUE THREAD

**Issue by kdelee** [quipucords/quipucords#741]
## Specify type:
- Bug

### Bug severity (if applicable):
- High
___

## Description:
Providing only one of the child items of "options" from the CLI overwrites the other option.
___

### Expected behavior:
On creation OR edit, providing only one of `ssl-cert-verify` or `satellite-version` does not overwrite the default or previously set value of the other option.

### Actual behavior:
If I use the CLI to create a satellite source and provide `--ssl-cert-verify=False`, then the default satellite version is wiped out and does not show when I call `qpc source list`. Likewise, if I use `qpc source edit` to attempt to only update one field, the other gets wiped out.

### Steps to reproduce:
1) Create a satellite source and specify `--ssl-cert-verify=False`
2) Run `qpc source list` and observe no satellite version is set in `options`
3) Run `qpc source edit` and only update the satellite version
4) Observe that the `ssl_cert_verify` option is wiped out and only the satellite version is now present

This has the side effect of not being able to run a scan on a satellite 6 source unless on creation and every edit I specify both `ssl-cert-verify` and `satellite-version` options.

### Environment information:
Provide detailed information on the *scanning* and *target* systems (if applicable); see example below.

Type            | Operating System | OS Version | Python Version | Virtualization | HTTPS | ssl-verify 
--------------- | ---------------- | ---------- | -------------- | -------------- | -------------- |-------------- |
QPC System | RHEL             | 7.4        | 3.4            | ESXi
quipucords server| docker container |               |            |        | yes   | no
Target System   | Satellite 6.2             |         |           |  | yes | no

**Comment by kdelee** [comment]
This was using the beta qpc package `qpc-0.0.1-1.git.342.44b5e58.el7.centos.noarch`
And the beta image I downloaded from Jenkins `qpc_docker_beta` job build # 14

**Comment by chambridge** [comment]
https://github.com/quipucords/quipucords/pull/751
https://github.com/quipucords/quipucords/pull/752
