### ISSUE TITLE
Systems scanned arithmetic off for vcenter connect scan

### ISSUE THREAD

**Issue by kdelee** [quipucords/quipucords#743]
## Specify type:
- Bug

### Bug severity (if applicable):
- Medium
___

## Description:
For any scan task, it is my understanding that the following equality should always hold:
` systems_scanned == system_count - systems_failed ` but this is not the case for the a vcenter scan I just ran.

### Expected behavior:
` systems_scanned == system_count - systems_failed `

### Actual behavior:
` systems_scanned != system_count - systems_failed `

Source info:
```
[scanadmin@dhcp182-239 ~]$ qpc source show --name vcenter
{
    "credentials": [
        {
            "id": 4,
            "name": "vcenter"
        }
    ],
    "hosts": [
        "vcenter.toledo.satellite.lab.eng.rdu2.redhat.com"
    ],
    "id": 2,
    "name": "vcenter",
    "options": {
        "ssl_cert_verify": false
    },
    "port": 443,
    "source_type": "vcenter"
}
```

Scan show output:
```
[scanadmin@dhcp182-239 ~]$ qpc scan show --id 3
{
    "end_time": "2018-02-15T16:00:53.441704",
    "fact_collection_id": 3,
    "id": 3,
    "options": {
        "max_concurrency": 50
    },
    "scan_type": "inspect",
    "sources": [
        {
            "id": 2,
            "name": "vcenter",
            "source_type": "vcenter"
        }
    ],
    "start_time": "2018-02-15T16:00:31.612702",
    "status": "completed",
    "status_message": "Job is complete.",
    "systems_count": 106,
    "systems_failed": 0,
    "systems_scanned": 106,
    "tasks": [
        {
            "end_time": "2018-02-15T16:00:33.645529",
            "scan_type": "connect",
            "source": 2,
            "start_time": "2018-02-15T16:00:31.619928",
            "status": "completed",
            "status_message": "Task is complete.",
            "systems_count": 106,
            "systems_failed": 0,
            "systems_scanned": 0
        },
        {
            "end_time": "2018-02-15T16:00:52.505237",
            "scan_type": "inspect",
            "source": 2,
            "start_time": "2018-02-15T16:00:33.649093",
            "status": "completed",
            "status_message": "Task is complete.",
            "systems_count": 106,
            "systems_failed": 0,
            "systems_scanned": 106
        }
    ]
}
```

### Steps to reproduce:
1) Create a vcenter credential and source
2) Run a scan on the vcenter (I used our vcenter instance)
3) Inspect results of scan with `qpc scan show --id {scan_id}

### Environment information:
Provide detailed information on the *scanning* and *target* systems (if applicable); see example below.

Type            | Operating System | OS Version | Python Version | Virtualization | HTTPS | ssl-verify 
--------------- | ---------------- | ---------- | -------------- | -------------- | -------------- |-------------- |
QPC System | RHEL             | 7.4        | 3.4            | ESXi
quipucords server| docker container |               |            |        | yes   | no
Target System   | vCenter            |         |           |  | yes | no

This was using the beta qpc package `qpc-0.0.1-1.git.342.44b5e58.el7.centos.noarch`
And the beta image I downloaded from Jenkins `qpc_docker_beta` job build # 14

**Comment by chambridge** [comment]
@kholdaway did you just fix this in `master`?

**Comment by kdelee** [comment]
Oops, my bad. 
https://github.com/quipucords/quipucords/issues/735

But guess might need to merge that into beta
