### ISSUE TITLE
Beta Docs - download docker RPM for RHEL 6

### ISSUE THREAD

**Issue by mdvickst** [quipucords/quipucords#783]
# Opening a new issue
___

## Specify type:
- Enhancement

### Bug severity (if applicable):
- Medium
___

## Description:
Required -k for curl to work for me since the cert wasn't recognized as valid on my system.

**Comment by jlprevatt** [comment]
To make a change in the #766 edit pass, I would need a bit more info about how the command/section needs to change. Thanks.

**Comment by chambridge** [comment]
I believe the suggestion is to update the command to:
`# curl -k -O -sSL https://yum.dockerproject.org/repo/main/centos/6/Packages/docker-engine-1.7.1-1.el6.x86_64.rpm`

**Comment by chambridge** [comment]
Corrected with:
https://github.com/quipucords/quipucords/pull/802

[Installing Docker on Red Hat Enterprise Linux 6.6 or later](http://quipucords.readthedocs.io/en/beta/beta.html#installing-docker-on-red-hat-enterprise-linux-6-6-or-later)
