### ISSUE TITLE
Beta Docs - Example uname -r output for RHEL 

### ISSUE THREAD

**Issue by mdvickst** [quipucords/quipucords#784]
# Opening a new issue
___

## Specify type:
- Enhancement

### Bug severity (if applicable):
- Medium
___

## Description:
The exmaple output of uname -r for RHEL 6 should probably show a el6 kernel. 

3.10.0-229.el7.x86_64 is what is shown now, should be something more like 2.6.32-573.el6.x86_64

**Comment by jlprevatt** [comment]
As part of work for #766, changed the output of the `# uname -r` command to the 2.6.32-573.el6.x86_64 value above.

**Comment by chambridge** [comment]
Corrected with:
https://github.com/quipucords/quipucords/pull/802

[Installing Docker on Red Hat Enterprise Linux 6.6 or later](http://quipucords.readthedocs.io/en/beta/beta.html#installing-docker-on-red-hat-enterprise-linux-6-6-or-later)
