### ISSUE TITLE
Beta Docs - No Credtionals provided for login

### ISSUE THREAD

**Issue by mdvickst** [quipucords/quipucords#785]
# Opening a new issue
___

## Specify type:
- Enhancement

### Bug severity (if applicable):
- High

___

## Description:
Should provide default username and password (admin/pass) for sonar in the docs.

**Comment by chambridge** [comment]
@mdvickst 
Is there something wrong with the current documentation?

http://quipucords.readthedocs.io/en/beta/beta.html#changing-the-default-password-for-the-quipucords-server

**Comment by chambridge** [comment]
reopen if you feel changes are need to the existing doc.
