### ISSUE TITLE
Beta Docs - qpc scan missing 'start'

### ISSUE THREAD

**Issue by mdvickst** [quipucords/quipucords#787]
# Opening a new issue
___

## Specify type:
- Bug

### Bug severity (if applicable):
- High
___

## Description:
First example under "Running a scan" section is missing "start"
# qpc scan --sources source_name1 source_name2

**Comment by jlprevatt** [comment]
Yes. This is still true in my latest edit. While working on #766 changes, I made that change to beta.rst:

Run the scan by using the ``scan start`` command, specifying one or more sources for the ``sources`` option:

  ``# qpc scan start --sources source_name1 source_name2``

**Comment by chambridge** [comment]
Corrected with:
https://github.com/quipucords/quipucords/pull/802

[Running a Scan](http://quipucords.readthedocs.io/en/beta/beta.html#running-a-scan)
