### ISSUE TITLE
Sat 6 Error - Certificate verify failed

### ISSUE THREAD

**Issue by mdvickst** [quipucords/quipucords#790]
# Opening a new issue
___

## Specify type:
- Bug

### Bug severity (if applicable):
- High
___

## Description:
Running scan of Sat 6.2.12 server and get an error that looks like it's related to SSL certs. 
"status_message": "Satellite error encountered: HTTPSConnectionPool(host='sat6.rhsat.rdu.salab.redhat.com', port=443): Max retries exceeded with url: /api/status (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)'),))\nConnect scan failed for {id:2, scan_type:connect, status:running, source:{ id:2, name:sat6_rdu_lab, type:satellite}, sequence_number:1, systems_count: None, systems_scanned: None, systems_failed: None, start_time: 2018-02-08 05:06:14.447297 end_time: None, connection_result: { id:2, sytems:api.SystemConnectionResult.None }, inspection_result: None}."

___

### Steps to reproduce:
qpc cred add --type satellite --name sat6_rdu_lab --username admin --password
qpc source add --type satellite --name sat6_rdu_lab --hosts sat6.rhsat.rdu.salab.redhat.com --cred sat6_rdu_lab --satellite-version 6.2
qpc scan start --sources sat6_rdu_lab local_vms

contact me for credentials and to book time before attempting to connect since this is a shared resource.

**Comment by chambridge** [comment]
Try creating the source with the `--ssl-cert-verify False` option.

**Comment by chambridge** [comment]
reopen if that doesn't resolve your problem with cert validation.

**Comment by mdvickst** [comment]
Thanks, didn't know that was an option on the sources, I'll open something to get that added into the docs since I imagine that's going to be a common question for the pilot in test/non-prod environments.

**Comment by chambridge** [comment]
Its mentioned in the docs here:
http://quipucords.readthedocs.io/en/beta/beta.html#creating-a-satellite-source
Under **IMPORTANT**.

**Comment by mdvickst** [comment]
Doh! Thanks for pointing that out. I clearly just need to RTFM :)
