### ISSUE TITLE
Make scan name optional for qpc scan job

### ISSUE THREAD

**Issue by kholdaway** [quipucords/quipucords#811]
# Opening a new issue
___

## Specify type:
- Enhancement

## Description:
Today: 
**qpc scan job** --name** *scan_name* | **--id=** *scan_job_identifier* **--status=** *(created | pending | running | paused | canceled | completed | failed)*
 Proposed:
Either scan name or id could be specified.  Name gives all jobs for a scan.  Id gives the exact scan.
**qpc scan job** (--name** *scan_name* | **--id=** *scan_job_identifier*) **--status=** *(created | pending | running | paused | canceled | completed | failed)*

**Comment by kdelee** [comment]
@kholdaway 
I'm confirming I understand -- on the API side I have to give a scan a name -- but then it gets assigned an ID and that is how scan jobs are triggered and if the CLI user wants to use the id in lieu of the name, that is an option.

**Comment by kholdaway** [comment]
@kdelee The scan requires a name.  The CLI requires a name.  If you call the API directly, you must use the ID not the name.
