### ISSUE TITLE
UI: Add Source Wizard issues

### ISSUE THREAD

**Issue by jeff-phillips-18** [quipucords/quipucords#827]
## Type:
- Bug

### Bug severity:
- Medium
___

## Description:
A couple of issues with the Add Source Wizard:

- Second page should auto focus on the source name field
- After adding a credential, the credential does not appear in the list
- Selecting a credential doesn't show it as selected when I bring up the list again. It does if I select another credential. But then that one doesn't show up.
- The last page of the wizard says I will get notified, I never do. We should probably just refresh the sources page on an add, it shows up then.

**Comment by cdcabrera** [comment]
Relates to #690

**Comment by cdcabrera** [comment]
Note: Issues found with the wizard

- Endpoint for editing a source needs to be fixed
- Wizard isn't limiting the credential types... they are specific and need to be filtered for "network", "satellite", and "vcenter"... I think this is the issue @bclarhk  came across.
- Looks like the validation on the wizard screws up after adding a credential, it needs to be reset for some reason, after blanking the fields it then fires again... 
- Need to fire a refresh when closing the wizard down, dependent on the view you're in

**Comment by cdcabrera** [comment]
relates to #931
