### ISSUE TITLE
I want to be able to determine if JBoss EAP 5 is present on any target systems

### ISSUE THREAD

**Issue by chambridge** [quipucords/quipucords#847]
## Specify type:
- Enhancement

## Description:
Capture whether JBoss EAP 5 is running on target systems.

### Ansible Role:
- process list
- init files (chckconfig, systemctl)
- documented installation paths

### Scanner Post-processing:
Add any necessary post-processing logic to capture the eap5 "raw" facts needed to determine presence.

### Fingerprinting Engine:
Update fingerprinting engine to process JBoss EAP 5 facts to determine presence

___
Work items:
- [x] https://github.com/quipucords/quipucords/issues/848
- [x] https://github.com/quipucords/quipucords/issues/849
- [x] https://github.com/quipucords/quipucords/issues/850

**Comment by noahl** [comment]
All parts of this are done, so closing.
