### ISSUE TITLE
Add necessary network post processing for determining JBoss EAP 5 presence

### ISSUE THREAD

**Issue by chambridge** [quipucords/quipucords#849]
## Specify type:
- Enhancement

## Description:
Provide any necessary post processing logic from the Ansible tasks to gather the necessary "raw" facts for determining JBoss EAP 5 presence.

## Acceptance Criteria: 

- [ ] Verify that new or existing raw facts are populated and sent to the fingerprinting engine and that they are proper JSON.
___

Associated with:  https://github.com/quipucords/quipucords/issues/847

**Comment by noahl** [comment]
Fixed by #879 .
