### ISSUE TITLE
Ability to combine multiple scans into a single report

### ISSUE THREAD

**Issue by mdvickst** [quipucords/quipucords#851]
## Specify type:
- Enhancement

## Description:
Right now a report can only be generated from a single scan job but it would be really helpful to enable a report generation from multiple scan jobs. 

Either have a merge task or be able to provide multiple scan job IDs to the report object.

**Comment by chambridge** [comment]
Suggesting the following:

###  CLI
```
# qpc report merge --ids scan_job_A ...
Report created with id <report_id>.
Use "qpc report summary" or "qpc report detail" command to view the report.
```
Then update `qpc report summary` and `qpc report detail` to take either a scan job ID or a report ID.
```
qpc report summary [-h] (--scan-job SCAN_ID | --report REPORT_ID) (--json | --csv) --output-file


qpc report detail [-h] (--scan-job SCAN_ID | --report REPORT_ID) (--json | --csv) --output-file
```

### API
Merge endpoint:
**Method:** PUT
**URL:** `api/v1/jobs/merge`
**Body:**
```
{
"jobs": [ <job_id_1>, <job_id_2> ]
}
```
**Response:**
- status_code: 201
   json:
```
{
"report_id": <id>
}
```

- status_code: 400
An error can be produced if given invalid job ids, or none of the jobs have inspections facts

____
Acceptance Criteria:
- Validate that a user can create a new report ID by merging several scan job inspection facts
- Validate that a user gets an error if they supply invalid scan job ids
- Validate that a user gets an error if they supply scan jobs without any inspection facts
