### ISSUE TITLE
Network scans broken because of attempt to access None type

### ISSUE THREAD

**Issue by kdelee** [quipucords/quipucords#895]
## Specify type:
- Bug

### Bug severity (if applicable):
- High
- Blocker
___

## Description:
Runtime error caused by None type object being accessed causes scan to completely halt/fail.
___

### Expected behavior:
Scan does not fail because of internal syntax errors.

### Actual behavior:
Excerpt from logs:

```
INFO 2018-03-01 15:06:48,923 model 30 140451933644544 Task 4 (inspect, network, sonarmachines, elapsed_time: 0s) - INITIAL NETWORK INSPECT STATS Stats: systems_count=23, systems_scanned=0, systems_failed=0
ERROR 2018-03-01 15:06:48,938 model 30 140451933644544 Job 1 (inspect, elapsed_time: 16s) - 'NoneType' object has no attribute 'search_directories'
INFO 2018-03-01 15:06:48,944 model 30 140451933644544 Job 1 (inspect, elapsed_time: 16s) - FAILURE STATS. Stats: systems_count=23, systems_scanned=0, systems_failed=0
ERROR 2018-03-01 15:06:48,945 model 30 140451933644544 Job 1 (inspect, elapsed_time: 16s) - STATE UPDATE (failed).  Additional State information: 'NoneType' object has no attribute 'search_directories'
Process ScanJobRunner-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/app/quipucords/scanner/job.py", line 78, in run
    raise error
  File "/app/quipucords/scanner/job.py", line 75, in run
    status_message, task_status = runner.run()
  File "/app/quipucords/scanner/network/inspect.py", line 127, in run
    scan_message, scan_result = self._inspect_scan(remaining)
  File "/app/quipucords/scanner/network/inspect.py", line 179, in _inspect_scan
    extra_vars = self.scan_job.options.get_extra_vars()
  File "/app/quipucords/api/scan/model.py", line 156, in get_extra_vars
    if extended_search.search_directories is not None:
AttributeError: 'NoneType' object has no attribute 'search_directories'
```

### Steps to reproduce:
I was able to reproduce this by attempting to scan 1 live network source. (i.e. I could ssh into it, the connect scan succeeded.)

### Environment information:
Provide detailed information on the *scanning* and *target* systems (if applicable); see example below.

Type            | Operating System | OS Version | Python Version | Virtualization
--------------- | ---------------- | ---------- | -------------- | --------------
Scanning System | Fedora            | 26        | 3.6            | Bare Metal
Target System   | RHEL             | 6.9        | 2.6.6          | ESXi
quipucords server | docker container built from master | 5bbea1d9814e20ac19e8ba8fbc224b49db950908 
qpc | pip install from master ( bit stale -- from tuesday. But this seems to be API side)

**Comment by kholdaway** [comment]
This looks like a duplicate of https://github.com/quipucords/quipucords/issues/891.  @kdelee can you confirm?

**Comment by kdelee** [comment]
:+1: appears to be duplicate, and the fix works for me! Thanks
