### ISSUE TITLE
Scan is present and absent at the same time

### ISSUE THREAD

**Issue by noahl** [quipucords/quipucords#897]
My terminal:
```
(venv) [nlavine@nlavine quipucords]$ python bin/qpc scan start --name sonar-jbosseap-rhel-5-vc
Scan "sonar-jbosseap-rhel-5-vc" does not exist.
(venv) [nlavine@nlavine quipucords]$ python bin/qpc scan add --name sonar-jbosseap-rhel-5-vc --source sonar-jbosseap-rhel-5-vc
name: Scan with name=sonar-jbosseap-rhel-5-vc already exists
```

I'm not sure right now what's causing this, but I will try to figure it out.

**Comment by noahl** [comment]
The server logs show that the server was erroring and returning 500s because it needed to apply database migrations. The question is, why were those 500s displayed as the messages above?

**Comment by noahl** [comment]
The error in `scan start` was coming from `qpc.scan.utils._get_scan_object_id`, which prints the scan does not exist message for all error codesa.

**Comment by noahl** [comment]
The error from `scan add` was correct - there was an existing scan by the name. It just wasn't usable because of the database migration issue.

**Comment by chambridge** [comment]
You can just update `handle_token_errors`:
https://github.com/quipucords/quipucords/blob/master/qpc/request.py#L40

to be `handle_general_errors`: where we catch 500s and give print the error and perform a system exit.

**Comment by noahl** [comment]
Good news: since users should never change their code while forgetting to migrate their database, they should never hit this.

Bad news: it's still possible for them to hit *some* kind of 500, and the error reporting here is not good. I am going to file another issue to make sure that qpc prints a good error message for 500s in general, referencing this one, and then close this.

**Comment by noahl** [comment]
@chambridge thanks!
