### ISSUE TITLE
"name" column in summary report is IP address for network sources

### ISSUE THREAD

**Issue by mdvickst** [quipucords/quipucords#903]
# Opening a new issue
___

## Specify type:
- Bug

### Bug severity (if applicable):
- Medium
___

## Description:
When creating a summary report with network and satellite 6.2 source, the "name" column for network sources shows the IP address not the hostname. 
___

### Expected behavior:
show hostname

### Actual behavior:
shows ip addr

### Steps to reproduce:
run scan with network source and satellite 6.2 source, run summary report. 

### Environment information:
Provide detailed information on the *scanning* and *target* systems (if applicable); see example below.

Type            | Operating System | OS Version | Python Version | Virtualization
--------------- | ---------------- | ---------- | -------------- | --------------
Scanning System | RHEL             | 7.4        | 3.6            | Bare Metal
Target System   | RHEL             | 5.9        | 2.4.6          | RHEV

**Comment by chambridge** [comment]
We use the inventory name from Ansible for this which is most often the ip address when running a range. You want use to add something like a command that does:
`$ hostname`
And uses that result for hostname?

**Comment by mdvickst** [comment]
Could we use the value from the uname_hostname fact from the detail report?

**Comment by chambridge** [comment]
sure
