### ISSUE TITLE
UI: Wizard, Editing a Network source does not save the changes

### ISSUE THREAD

**Issue by bclarhk** [quipucords/quipucords#908]
# Opening a new issue for the first time. Go easy on me ;-)
___

## Specify type:
- Bug

### Bug severity:
- Medium
___

## Description:
Editing a Network source should bring up the wizard with step 1 (select type) hidden
Saving should save the changes.

### Build information:
kholdaway Improve logging message (#893)

**Comment by cdcabrera** [comment]
Relates to #839

**Comment by cdcabrera** [comment]
Note: this looks like it could be around the use of the wrong endpoint

**Comment by cdcabrera** [comment]
Relates to #931

**Comment by cdcabrera** [comment]
@bclarhk can you confirm the updates from PR #931 resolve this issue?

**Comment by cdcabrera** [comment]
@bclarhk closing this, the fixes appear to work. We can re-open the issue if another problem exists
