### ISSUE TITLE
UI: Wizard, Multiselect dropdown doesn't match Patternfly

### ISSUE THREAD

**Issue by bclarhk** [quipucords/quipucords#910]
## Specify type:
- Enhancement

### Bug severity (if applicable):
- Medium
___

## Description:
Change the credential multiple select dropdown to match the patternfly/bootstrap implementation
https://www.patternfly.org/pattern-library/widgets/#bootstrap-select

Editing which credentials should be used is broken

### Environment information:
kholdaway Improve logging message (#893)

**Comment by cdcabrera** [comment]
Relates to #839

**Comment by cdcabrera** [comment]
Relates to #972
