### ISSUE TITLE
UI: sorting and filtering not working

### ISSUE THREAD

**Issue by bclarhk** [quipucords/quipucords#913]
## Specify type:
- Bug

### Bug severity (if applicable):
- High
___

## Description:
Filters should follow the PF spec:
     http://www.patternfly.org/pattern-library/forms-and-controls/filter/

# Sources
### Filters:
- [x] Name should work on partial match and not be case sensitive
- [ ] Credential - should work on partial match and not be case sensitive (and not return duplicate results)
- [x] Source Type - the filters appear to stack but only obey the most recent choice
~- [ ] IP Address should work on partial match~
~- [ ] Connection status~
~- [ ] Credentials should present a list of options (like status does)~

### Sorting:
- [x] Name
- [x] Source Type
~- [ ] Connection Status~
~- [ ] Credentials Count~
~- [ ] Systems Count~
~- [ ] Successful Authentications~
~- [ ] Failed Authentications~

# Scans
### Filters:
- [x] Name should work on partial match and not be case sensitive
- [x] Status (complete, pending, etc)
~- [ ] Source should work on partial match and not be case sensitive~

### Sorting:
- [x] Name
- [x] Status
~- [ ] Time~
~- [ ] System Count~
~- [ ] Successful System Scans~
~- [ ] Failed System Scans~
~- [ ] Sources Count~
~- [ ] Scans Count~

# Credentials
### Filters:
- [x] Name should work on partial match and not be case sensitive
- [x] Credential Type - the filters appear to stack but only obey the most recent choice

### Sorting:
- [x] Name
- [x] Credential Type

___

### Environment information:
Relates to #839 #923 #925

**Comment by jeff-phillips-18** [comment]
For filtering on sources, I think a partial match on credentials would be more reasonable since there may be a large number of credentials (paging could be involved). Thoughts?

**Comment by bclarhk** [comment]
Items removed from the UX "wishlist" have strikethroughs. We need the remaining items across the 3 views.
@chambridge

**Comment by cdcabrera** [comment]
PR #1047 filtering by names should take care of some of this issue. @bclarhk can you verify and update the issue

**Comment by bclarhk** [comment]
Sources: "Most Recent Connection Scan" should be "Most Recent"
Scans: "Most Recent Time" should be "Most Recent"
Both "Most Recent" sorts are sorting backwards. Timestamp is the reverse of most recent.

**Comment by cdcabrera** [comment]
Had trouble locating this within the Swagger spec, the possible values for `ordering`...  this took me a min or two going back over the past PRs... for reference start with issue #925

- Scans, PR #1004 PR #1006 
  - Ordering - Enum, possible values: 
    - `id`
    - `name`
    - `scan_type`
    - `most_recent_scanjob__start_time`
    - `most_recent_scanjob__status`

- Sources - PR #1021 
  - Ordering - Enum, possible values: 
    - `name`
    - `source_type`
    - `most_recent_connect_scan__start_time`

**Comment by kholdaway** [comment]
Issue moved to [quipucords/quipucords-ui #11](https://github.com/quipucords/quipucords-ui/issues/11) via [**ZenHub**](https://www.zenhub.com/)
