### ISSUE TITLE
Need to filter by partial matches for source fields and scan fields

### ISSUE THREAD

**Issue by jeff-phillips-18** [quipucords/quipucords#923]
- Enhancement
- Medium
___

## Description:
The UI is designed to filter on certain fields where the user would expect partial non-case sensitive matches to return results. 

Sources:
  - Name
  - IP Address
  - Credential name

Scans:
  - Name
  - Source name

Credentials:
  - Name

## Acceptance Criteria: 
- [ ] Verify that partial non-case sensitive matches for Source Names are returned in Source queries
- [ ] Verify that partial matches for Ip Addresses are returned in Source queries
- [ ] Verify that partial non-case sensitive matches for Credential Names are returned in Source queries

- [ ] Verify that partial non-case sensitive matches for Scan Names are returned in Scan queries
- [ ] Verify that partial non-case sensitive matches for Source Names are returned in Scan queries

- [ ] Verify that partial non-case sensitive matches for Credential Names are returned in Credential queries

**Comment by cdcabrera** [comment]
Relates #913

**Comment by jeff-phillips-18** [comment]
@chambridge Any chance of this working or should I pull out these filters?

@serenamarie125 @bclarhk

**Comment by chambridge** [comment]
@jeff-phillips-18 I think this is reasonably doable for searching the name of the primary resource.

Searching the name of a secondary resource may be doable. I haven't had a chance to look at it.

Our db isn't setup for searching the IPs, so that one isn't doable.

**Comment by jeff-phillips-18** [comment]
The current API supports a single 'search' which searches multiple fields. The UI is designed to filter on individual fields. The user selects the field, then types the text they wish to filter on:

![image](https://user-images.githubusercontent.com/11633780/37431634-28f8616a-27ac-11e8-97d2-2adb4f8b89b2.png)

The current implementation would return matches for both Name and Credential Name

**Comment by chambridge** [comment]
Thanks for the clarification @jeff-phillips-18. I'll try to rework it today, unfortunately we wont get the easy benefit from the Django Rest Framework Search Filter.

**Comment by jeff-phillips-18** [comment]
Thanks @chambridge, sorry for the confusion.

**Comment by jeff-phillips-18** [comment]
Thanks @chambridge !
