### ISSUE TITLE
Need the ability to sort by counts in queries

### ISSUE THREAD

**Issue by jeff-phillips-18** [quipucords/quipucords#925]
- Enhancement
- Medium
___

## Description:
The UI is designed to sort on counts of different items on certain fields:

Sources:
  - Number of credentials
  - Number of Systems
  - Number of successful authentications for most recent scan
  - Number of faild authentications for most recent scan

Scans:
  - Number of systems
  - Successful system scans
  - Failed System scans
  - Number of Sources
  - Number of scans run

**Comment by cdcabrera** [comment]
Relates to #913

**Comment by chambridge** [comment]
Most of these are not feasible ordering as you are trying to have us order the primary object like a source by the values in a secondary object a scan job.

We could potentially do the order by number of credentials in a source or number of sources in a scan, but I don't really understand a real use case for a user.

**Comment by jeff-phillips-18** [comment]
@bclarhk Can you explain the use case here?

**Comment by jeff-phillips-18** [comment]
@serenamarie125 @bclarhk Do we have need for these use cases?

**Comment by serenamarie125** [comment]
@jeff-phillips-18 might you be able to add screenshots of each of the views (scans & sources) and indicate which are currently sorting successfully?

**Comment by serenamarie125** [comment]
Just spoke with Mark Vickstrom.  

For **Sources** ... to be able to sort by name, date & source type
For **Scans** to be able to sort by name, date & overall status

@bclarhk can you update the mocks/notes stating this?
@jlprevatt FYI
@chambridge I'm not sure what API work is needed based on this news 🗞 

@jeff-phillips-18 sort by name & source type are currently working, correct?

**Comment by chambridge** [comment]
I think we are still conflating multiple resources here.

- Sources don't have a date
- Scans don't have a date or "overall status"

I assume you mean that sources should be sortable by the latest connection scan job. 
I assume you mean scans should be sortable by most recent scan job
I assume you mean scans should be sortable by most recent scan job status

Based on this, please close this issue and open 3 issues for the API for each of my clarifications above, if they are correct.

**Comment by jeff-phillips-18** [comment]
Yes, sort sources by name and type are working (well, small ui bug on type, but fixed soon).

**Comment by serenamarie125** [comment]
Opened 3 new issues to track specific API needs:
#982 
#983 
#984 

@jeff-phillips-18 can you close this ?  I don't have access.

**Comment by jeff-phillips-18** [comment]
thanks @chambridge , @serenamarie125 .
