### ISSUE TITLE
DOC or kickoff materials: info for troubleshooting/support, brainstorming for ideas

### ISSUE THREAD

**Issue by jlprevatt** [quipucords/quipucords#930]
This is a "nice to have" for the future or "really nice to have" for the pilot if we can get the basics before the pilot goes out. Mentioned in #807. Attending the MBU sessions ate into my time to look into this.

Have not looked to see how other products do this--e.g., does the support team normally write a solution with this information (support engagement agreement)? Not sure if appropriate to add this information to doc, could be Customer Portal solution or could be in kickoff slides.

Document the basics of how to work with pilot support:
Contact info (generic email?) for the pilot support team (Dan? Mark? Kathryn?)
Info you must supply to support in your email, for example:

- Problem details, environment details, etc. (will the pilot kickoff materials contain a problem report template for customers? can add reminder in doc about detailed process being in kickoff materials.) (Dan/Kathryn?)
- Include detailed scan report if problem encountered during a scan (preferred file format?) (Chris?)
- Include server log? How do you view, how do you generate, how do you save/send, etc. (Chris?)

Just capturing ideas here, can be closed in favor of well-framed issues resulting from this brainstorming.

**Comment by kholdaway** [comment]
Issue moved to [quipucords/quipudocs #11](https://github.com/quipucords/quipudocs/issues/11) via [**ZenHub**](https://www.zenhub.com/)
