### ISSUE TITLE
Error message is not easily determined from API response.

### ISSUE THREAD

**Issue by jeff-phillips-18** [quipucords/quipucords#940]
## Type:
- Bug

### Bug severity:
- Medium
___

## Description:
Error when attempting to create a source or scan with a duplicate name puts error message in the response's data.name field. This is difficult to use since we cannot predict which data field will contain the error message.

Is there some mechanism for knowing where to get the error message from?

**Comment by chambridge** [comment]
@jeff-phillips-18  
Most of this is default error messaging from Django Rest Framework:

For example providing credential with empty body:
```
  {
    "name": [
        "This field is required."
    ],
    "username": [
        "This field is required."
    ]
}
```

Each field is an error.

http://www.django-rest-framework.org/api-guide/exceptions/#exceptions

Not sure what additional details you are looking for. We do have the following in the CLI that has solved most of our issues in the CLI:
https://github.com/quipucords/quipucords/blob/master/qpc/utils.py#L262

**Comment by jeff-phillips-18** [comment]
Thanks @kholdaway .  I should have closed this after implementing similar to you suggestion from `utils.py`.

**Comment by kholdaway** [comment]
👍 Yep, I was pretty sure we fixed this one.
