### ISSUE TITLE
Provide source_type and sources information summary report

### ISSUE THREAD

**Issue by chambridge** [quipucords/quipucords#952]
## Specify type:
- Enhancement

## Description:

For each source type tell whether they system was present.
(network, satellite, vcenter)

List of source names the system was found in

## Acceptance Criteria: 

- [ ] Verify that report users can determine what kinds of sources types the system was inspected with
- [ ] Verify that report users can see the list of sources the system was found in.

____
Associated with: https://github.com/quipucords/quipucords/issues/947

**Comment by kholdaway** [comment]
@chambridge Are you saying to add a top level `sources` array?  I guess it could be in meta-data too.
For example,
```
{
    "report_id": "1",
    "report": [
        {
            "id": 1,
            "report_id": 1,
            "name": "dhcp182-46.gsslab.rdu2.redhat.com",
            "os_release": "Fedora release 26 (Twenty Six)",
            "sources": [
                {
                    "source_name": "name",
                    "source_type": "network"
                },
                {
                    "source_name": "name",
                    "source_type": "vcenter"
                }
            ],
            "products": [],
            "entitlements": [],
            "metadata": {
                "name": {
                    "source_id": 8,
                    "source_name": "NSmallSource",
                    "source_type": "network",
                    "raw_fact_key": "uname_hostname"
                }
            }
        }
    ]
}
```
