### ISSUE TITLE
500 error because of database lock

### ISSUE THREAD

**Issue by kdelee** [quipucords/quipucords#954]
## Specify type:
- Bug

### Bug severity (if applicable):
- Medium
___

## Description:
If requests are timed just right, it is possible to get a 500 error when attempting to pause or cancel a scan. NOTE: This has been observed with the pilot container, but probably is still an issue in master.

### Expected behavior:
If I make a poorly timed request because some other task is accessing the object I'm attempting to modify, the server does something graceful.

### Actual behavior:
The server tells me it is broken.

For the following satellite source:
```
 'source_type': 'satellite'}]
source = {'credentials': ['sat6'], 'hosts': ['sat-r220-07.lab.eng.rdu2.redhat.com'], 'name': 'sat6', 'options': {'satellite_version': '6.2', 'ssl_cert_verify': False}}
scan_type = 'inspect'
```

After the scan has started, if I attempt to pause it, I get the following 500:
```
E           request path : '/api/v1/scans/29/pause/'
E           
E           request body : b'{}'
E           
E           request headers : {'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Authorization': 'Token 2c1aa5e4d44ec1069c25982a20375550b808553d', 'Content-Length': '2', 'Content-Type': 'application/json'}
E           
E           response code : 500
E           
E           text_error_message : ('OperationalError at /api/v1/scans/29/pause/\n'
E            'database is locked\n'
E            '\n'
E            'Request Method: PUT\n'
E            'Request URL: https://127.0.0.1/api/v1/scans/29/pause/\n'
E            'Django Version: 1.11.5\n'
E            'Python Executable: /root/venv/bin/python3\n'
E            'Python Version: 3.6.4\n'
```

### Steps to reproduce:
I've not been able to reproduce manually yet, but this is happening with some regularity on one of our automation jobs -- I can point you to the logs.

### Environment information:
Provide detailed information on the *scanning* and *target* systems (if applicable); see example below.

Type            | Operating System | OS Version | Python Version | Virtualization
--------------- | ---------------- | ---------- | -------------- | --------------
Scanning System | RHEL             | 7.4        | 3.6            | Bare Metal
Target System   | RHEL             | 5.9        | 2.4.6          | RHEV
quipucords | docker container | pilot | |

**Comment by chambridge** [comment]
I think this is due to are use of sqlite to keep our server setup light-weight (i.e. don't require the user to setup a db as well).
https://stackoverflow.com/a/31547325

I think the best we can do is put a try/catch around this and attempt X number of retries.

**Comment by kdelee** [comment]
That seems reasonable for now

**Comment by kdelee** [comment]
This just came up when deleting sources in rapid succession ...
```
request path : '/api/v1/sources/779/'

request body : None

request headers : {'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Authorization': 'Token 620ebaa014590da2f4d08cd422d75682f39301f9', 'Content-Length': '0'}

response code : 500

text_error_message : ('OperationalError at /api/v1/sources/779/\n'
 'database is locked\n'
 '\n'
```

**Comment by kholdaway** [comment]
@kdelee Can you open a separate issue for the deletion of sources.  Its not related.  Additionally, it would be useful to have steps to reproduce for that one also.

**Comment by kdelee** [comment]
@kholdaway will do
