### ISSUE TITLE
We need disabled_optional_products to be more intuitive 

### ISSUE THREAD

**Issue by abaiken** [quipucords/quipucords#960]
# Opening a new issue
___

## Specify type:
- Enhancement

## Description:
Right now the defaults for disabled_optional_products are a bit confusing when taken in context with the name.
IE. 
`disabled_optional_products= {'jboss_eap': True,
                        'jboss_brms': True,
                        'jboss_fuse': True}`

The dictionary is named `disabled_optional_products` and the default values for each of the products is `True`. This makes it seem like the products are automatically disabled which is not the case. If we want this to be more intuitive, we should either find a better name, or change the defaults. 

## Acceptance Criteria: 
_(for enhancements)_

- [ ] Verify that defaults make sense in the context of the name
___

**Comment by kdelee** [comment]
I think something like
```
{'options':
    'optional_products':
        { 'jboss_eap' : True,
          'jboss_fuse': False,
          'jboss_brms': False,
        },
    'extended_product_search':
         { 'jboss_eap' : True,
           'jboss_fuse': False,
           'jboss_brms': False,
           'search_directories' : [ '/opt', '/afs/shared', '/home/user/bin']
        }
}
```

Having the enabled/disabled word in the key name is confusing and makes me feel like I'm trying to do some kind of logic exercise when then reading the booleans associated with each item.

**Comment by abaiken** [comment]
The issue with changing `disabled_optional_products` to `optional_products` is that it is difficult for users to understand what this does. For example a user of the CLI passing the flag `--optional_products jboss_brms` is not going to understand that they are disabling jboss_brms. I am not sure what the best thing to do here is. 

Any thoughts @kdelee @chambridge @noahl @kholdaway ?

**Comment by kholdaway** [comment]
I agree that `optional_products` is too vague

**Comment by kholdaway** [comment]
I prefer disable_optional_products because this is what it does.  Perhaps the logic needs to be reversed so it make sense.  
`disabled_optional_products= {'jboss_eap': False, 'jboss_brms': False, 'jboss_fuse': True}` would mean only jboss_fuse is disabled.  And defaults are False not True.
